### ISSUE TITLE
Zombie Noises

### ISSUE THREAD

**Issue by Flugel3** [henkelmax/sound-physics-remastered#10]
**Bug description**
So when I'm on the surface I can still hear zombie growls even if they are completely covered by many many blocks. I don't know if this is a bug or not but it is certainly very strange. I tend to keep my volume fairly high and it is extremely noticeable actually. It's very strange actually the zombie noises are so far away that it at first sounded just like an ominous wind which I thought was a feature until further investigation.

**Steps to reproduce the issue**
1. Go to a 1.18 world, with the new generation as well as this mod (obviously)
2. Make sure your volume is up so that you can notice
3. Walk around to different areas that might have large caves underneath you
4. Listen carefully

**Expected behavior**
Normally I wouldn't expect to hear the zombies until I'm closer to them

**Log files**
I'm not sure if providing log files would be useful here but let me know otherwise and I'll provide them of course.

**Versions**
- Java 1.18
- Forge 38.0.8
- Forge-1.18-1.0.2
**Other mods**
Collective (Forge) (by Serilum)
Trample Stopper (by UnRealDinnerbone)
Areas (Forge) (by Serilum)
Sound Physics Remastered (by henkelmax)
Chalk (by mortuus_art)
World Pre Generator (by GeheimagentNr1)
Configured (by MrCrayfish)
Jade 🔍 (by Snownee_)
Clumps (by Jaredlll08)
Chunk Animator (by Lumien231)
Random Village Names (Forge) (by Serilum)
My Server Is Compatible (by Focamacho)
Restored Earth (by itayfeder)
Seamless Loading Screen (Forge) (by TimScript)

**Screenshots (Optional)**
Can't provide a screenshot of the sounds as far as I'm aware.

**Comment by henkelmax** [comment]
This mod does make very complex bounces of the sound. Please set "Render sound bounces" and "Render occlusion" in the debug config section. Sometimes you don't understand where sounds come from, since you don't see it. This should help you understanding it..

**Comment by Flugel3** [comment]
I understand it better now I checked the config but didn't know this debug option was there. It's actually really cool to see the sounds and how they interact with the environment. But, I must say that there are very few places in my world where I cannot hear the distant low groans of zombies and this just seems a little strange to me. Even when there doesn't appear to be any caves nearby. This is an extremely minor issue though because it's only really noticeable with volume cranked up.

What's particularly strange though is that I can hear the distant zombie noises and not see any traced lines appear with the debug turned on so.

**Comment by henkelmax** [comment]
I tried everything, but I can't confirm this. Please make sure you have no zombies that picked up items in some small holes somewhere around you.

**Comment by henkelmax** [comment]
I will further investigate this issue though.

**Comment by henkelmax** [comment]
Alright setting `max_occlusion` to `64` should solve your issue.

**Comment by henkelmax** [comment]
I also tweaked the default value of this option in the next version.

**Comment by Flugel3** [comment]
Yeah that totally solved it. Thanks for your help you're awesome!
