### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Herobattler** [henkelmax/sound-physics-remastered#101]
**Bug description**

-Crash report

**Expected behavior**

-No crash report

**Log files**

[crash-2023-04-05_10.03.56-fml.txt](https://github.com/henkelmax/sound-physics-remastered/files/11156576/crash-2023-04-05_10.03.56-fml.txt)

**Versions**

1.19.2-1.0.18

**Other mods**

[mods.txt](https://github.com/henkelmax/sound-physics-remastered/files/11156609/mods.txt)

**Comment by henkelmax** [comment]
```
Failure message: Macaw's Bridges - BOP (macawsbridgesbop) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19.2-1.2
	Mod Issue URL: https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues
	Exception message: java.lang.ClassNotFoundException: com.mcwbridges.kikoz.objects.Log_Bridge
```
