### ISSUE TITLE
Warden Noises

### ISSUE THREAD

**Issue by F3R07** [henkelmax/sound-physics-remastered#107]
I wasn't sure if I should submit this under bug report or feature suggestion, I clearly decided on the former.
Though in this instance I believe the mod is working as intended, if you are on terrain (a different cave or on an overhang) above a warden, you cannot hear the warden's noises, with other mobs this is no issue, but with the warden being able to attack through blocks this could become a serious issue with not knowing a warden is nearby while being within its attack range, I hope pointing out this issue helps! 

Minecraft version 1.19.3
Fabric
Mod Version: soundphysics-fabric-1.19.3-1.0.18

**Bug description**

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge/Fabric version
- Mod version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This is completely intentional. If you want these sounds ignored by the mod, add them to the config.
