### ISSUE TITLE
in game toggle, or just some kind of solution

### ISSUE THREAD

**Issue by itsdeadfrosty** [henkelmax/sound-physics-remastered#109]
I adore this mod, However, it's terribly annoying in the Nether, especially with mods like Incendium and Infernal Expansion. Some of the mobs are just ridiculous cause of distance, reverb, etc. But generally speaking, for all mobs it's a little overwhelming because you can hear them from further away.

https://github.com/henkelmax/sound-physics-remastered/assets/132015237/d8b66410-4791-4177-9594-be80fb332af6

**Comment by henkelmax** [comment]
Then just disable the mod in the cloth config GUI.

**Comment by itsdeadfrosty** [comment]
i mean i like the mod i dont wanna turn it off

**Comment by henkelmax** [comment]
You said you wanted a toggle.
Else you can just disable the sounds that are annoying you.
