### ISSUE TITLE
Massive frame drops with a lot of entities

### ISSUE THREAD

**Issue by Aceplante2** [henkelmax/sound-physics-remastered#111]
**Bug description**
I have a pen with a lot of animals in it. Without your mod, I get upwards of 50 fps, but with it enabled, it drops to about 6. In testing I noticed I do not get the frame drop if I turn off my sound.

**Steps to reproduce the issue**
1. Spawn a ton of animals in a fenced area
2. Take note of your average fps
3. Enable your mod
4. Repeat step 2

**Expected behavior**
I should not have a frame drop

**Log files**
Not relevant?

**Versions**
- 1.18.2
- Forge 40.2
- 1.0.6

**Other mods**
I do have others but this seems to be due to your mod, not a conflict.

**Comment by henkelmax** [comment]
This version is no longer actively developed. This bug was fixed on 1.19+

**Comment by Aceplante2** [comment]
Ah, that was fast. Thank you for the reply. I currently use 1.18.2 becuase that seems to be the version most likely to be supported by most mods, so I hope this can be a simple fix for 1.18.2 as well? If not I guess I understand
