### ISSUE TITLE
Infernal Expansion - mob Volin cause crash of game sounds over time

### ISSUE THREAD

**Issue by matzar24** [henkelmax/sound-physics-remastered#115]
**Bug description**
After playing a while in nether sounds starts to diminish, and after next few minutes it's completely gone...

**Detailed description**
I played a lot in overworld and it never happened.
Only when playing in nether, no matter if you dig or just wandering around and traveling.
It's starts occuring like around 7min after being in nether, and in next few minutes it's starting completely die out.
Resulting in complete lack of every sound. 
Only exiting world and joining again revive everything back to normal, but still after 10min it would happen again.
Also memory use doesnt exceed 90% allocated memory.
For me it looks like it is overloading with some sounds, it more like builds up over time, rather than being triggered by location in which may be custom mob. As soon I enter nether portal and teleport to overworld, every sound is back to normal.
And If I eneter again to nether everything is alright, and after some time in nether sounds start to disappearing again.

**Expected behavior**
I would expect it not to happen, playing without game sounds you start to feel like a deaf person.

**Versions**
- MC 1.19.2
- Forge 43.2.0
- Sound Physics Rem 1.0.18

Infernal Expansion solely is causing this issue.

**Other mods** 
170mods, in short:
No sound-changing related mods
Optimalization mods: Rubidium, Oculus
Nether related mods: Infernal expansion, nether depths upgrade, sapience, immersive weathering, clumps, 
advanced netherite, yungs better nether fortresses, 

**Video record**
64MB it too much for github, I uploaded it to Google drive:
#1 First video 64MB sounds starts to diminish and not every block or activity is making sounds
#2 Second video 46MB sound is completely gone, volume is up but it feels like being deaf person.
https://drive.google.com/drive/folders/1eA1TWMBEngvT4iUUxq5atPVgK4stIaZH?usp=sharing

**Comment by matzar24** [comment]
Correction: Memory is flactuating beetwen 75%-95% in nether and overworld also, but... in overworld sounds are working fine.
I'm teleporting to nether and after some time AFK no moving my user character sounds still are disappearing...
Maybe more like 10min, rather than 7min.

**Comment by matzar24** [comment]
Infernal Expansion is causing this. 
But IDK what exactly?
I tested this just by playing only on SoundPhysicRem and infernal expansion, 
and after AFK some time, sound is completely gone...

**Comment by henkelmax** [comment]
Does that also happen in the latest version of the mod?

**Comment by matzar24** [comment]
> Does that also happen in the latest version of the mod? Yeah, I installed both of them recently. 
Most recent update as I see is from a half year ago in case of both mods.

**Comment by matzar24** [comment]
For me fixing this bug isnt important, 
I can disable his spawn in config, also 
I didnt liked this mob from the start.
I would be only interested in future info, why
only this mob is causing sound to crash?

**Comment by villainous-j** [comment]
I know it's been a while since this, but I have the same issue! Will take a look into preventing that mob from spawning and see if anything changes at all.

**Comment by villainous-j** [comment]
And can confirm that disabling the spawning of Volines stops the issue from happening! Bizarre!
