### ISSUE TITLE
Rework occlusion and reflectivity config

### ISSUE THREAD

**Issue by pen9go** [henkelmax/sound-physics-remastered#117]
I was looking through the config because it was sometimes hard to hear other players (with simple voice chat) in forests. I wanted to lower occlusion for leaves but could not find a section in it to change that. Is it under another name, or is it just not there?

**Comment by henkelmax** [comment]
Currently you can only change the blocks properties by their sound types.
I'm planning on rewriting the configs to use actual block IDs instead of grouping them by their sound type.
