### ISSUE TITLE
Give customization to the voice chat integration

### ISSUE THREAD

**Issue by dbrighthd** [henkelmax/sound-physics-remastered#119]
Basically I really like how the voicechat mod makes voices echo, but i think it is way too much and nothing i change seems to affect the voices (it affects all other sounds however). 

I think a slider or something would be good to be able to change the reflectivity of voices

**Comment by henkelmax** [comment]
You can already do that in the configs. The voice chat sounds are treated the exact same as all other sounds.

**Comment by dbrighthd** [comment]
What I mean is that the configs don't seem to effect the voicechat sounds, and if they do it is not proportional to any other sounds

I can send clips to show what I mean
