### ISSUE TITLE
Extreme echo in small but empty rooms

### ISSUE THREAD

**Issue by Luke322** [henkelmax/sound-physics-remastered#12]
**Bug description**
while standing in a small empty stone room the sound is no different to the sound of a large room.

**Steps to reproduce the issue**
1. Go to a small stone room
2. Listen to the echo
3. Go to a large stone room
4. Listen to the echo
5. Echos are the same

**Expected behavior**
In a small room the length of the echo should be shorter.

**Log files**
None needed

**Versions**
- 1.18
- Fabric - 0.12.8
- 1.0.3

**Other mods**
Only other sound mod is Presence Footsteps

**Screenshots (Optional)**
None

**Comment by henkelmax** [comment]
Unfortunately there is no easy way to resource efficiently determine the size of a room. It's purely determined by the material it is built of.
