### ISSUE TITLE
Config options are not available in ModMenu 1.19.4

### ISSUE THREAD

**Issue by Barerock** [henkelmax/sound-physics-remastered#120]
![image](https://github.com/henkelmax/sound-physics-remastered/assets/38869993/d6af0f55-df44-440c-8625-bb737b3ee4e4)

![image](https://github.com/henkelmax/sound-physics-remastered/assets/38869993/6eedc751-146b-4597-88b7-663ed8a492b1)

I have cloth config and I have the necessary fabric API version, and I am on Fabric loader 0.14.21-1.19.4

This seems to be a commonly reported issue, and, judging by other reports, a side issue not everyone knows about. Referencing the nether sounds report a while ago, that person probably didn't have settings options to know they could manipulate which things play sounds.

**Comment by henkelmax** [comment]
Thats cloth config for Forge
