### ISSUE TITLE
Server config not forced on connected clients.

### ISSUE THREAD

**Issue by PrintStringName** [henkelmax/sound-physics-remastered#124]
**Bug**
After updating my server to 1.20.1, people connecting to the server no longer have their configs changed to that of the server.
This is an issue since I want to have the Simple Voice Chat integration disabled for all players.

**Steps to reproduce the issue**
1. Set the config file on the server to disable the Voice Chat integration.
2. Connect with a client with the mod installed.
3. Set the client to have the integration enabled.
4. The server config is not forced on the client and the client still has other people's voices muffled.

**Expected behavior**
The clients should all have the server config forced on them while connected.

**Versions**
- Minecraft version: 1.20.1
- Fabric version: Latest

**Other mods**
Simple Voice Chat

**Comment by henkelmax** [comment]
This has never been like this. The mod is client sided and doesn't sync anything from the server. You might mistake this mod for another mod.

**Comment by PrintStringName** [comment]
Hmm. Perhaps I had a mod that forced config files onto the client before? Since this isn't actually a correct issue, perhaps it should be made into a feature request. Having the server config synced with the client would be very useful to have, especially when you are playing with less technically inclined players.

**Comment by henkelmax** [comment]
Thats what modpacks are for. This is a client side mod.

**Comment by PrintStringName** [comment]
My point was that I want the config to be forced onto the client, or have an option to do so.
The issue with modpacks is that people can still change the config files after download. I had a look as well but I can't find any mods for 1.20 Fabric that sync config files between server and client.
