### ISSUE TITLE
Game Crash when Looking at Enderman inside a Cave/Basement

### ISSUE THREAD

**Issue by kleytenlive** [henkelmax/sound-physics-remastered#125]
**Bug description**
The game crashes as soon as you look at an enderman inside a cave/basement and the sound of him agroing you should start

**Steps to reproduce the issue**
1. Go to 'cave/basement' where the reverb should start
2. look at enderman

**Expected behavior**
No crash

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use https://gist.github.com/kleytenlive/068d4e0d44642116b6dbae85a7ebae63.
Error is at line 5863
again at 5936
and at 5963

**Versions**
- Minecraft version 1.19.2
- Forge 43.2.14
- Mod version soundphysics-forge-1.19.2-1.0.18.jar

**Other mods**
the error appears even on a install that has only this mod installed.

**Comment by henkelmax** [comment]
This version is no longer supported. Does this also happen with version 1.1 of the mod?

**Comment by kleytenlive** [comment]
> 

i cant install 1.1 . its not available for 1.19.2 and the modpack im using / creating is for 1.19.2

**Comment by henkelmax** [comment]
Yeah, thats not supported anymore. I think this has been fixed in newer versions.
