### ISSUE TITLE
Crashes when opening mod settings.

### ISSUE THREAD

**Issue by Anonym0us-13** [henkelmax/sound-physics-remastered#126]
**Bug description**
When I try customizing the options for the mod it instantly crashes the game after saving. I am using Fabric, Iris, and Sodium.

**Steps to reproduce the issue**
1. Go to Mods
2. Click on Sound Physics
3. Click on Settings Cogwheel

**Expected behavior**
This should normally let me customize settings.

**Log files**
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7950(net.minecraft.class_1657, net.minecraft.class_1836)" because "$$0" is null

**Versions**
- 1.19.2
- Fabric version
- 1.0.18

**Other mods**
![image_2023-07-28_153000922](https://github.com/henkelmax/sound-physics-remastered/assets/140850942/e4573159-ff83-4594-a19b-7c3cd7df6f68)

**Comment by henkelmax** [comment]
Please post your logs like stated in the template.

**Comment by henkelmax** [comment]
Closed due to inactivity
