### ISSUE TITLE
Sound Physics make massive lag with entities

### ISSUE THREAD

**Issue by resiresi1** [henkelmax/sound-physics-remastered#127]
**Bug description**
Sound Physics massive lag game with tons of noise making entities rendered

**Steps to reproduce the issue**
1. download fabric 1.20.1 sound physics mod
2. make any xp farm 
3. wait for mobs to pile up
5. game lags

**Expected behavior**
I expected the game to not lag 

**Log files**
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/12245053/latest.log)

info
- 1.20.1
- Fabric 0.14.21
- 1.1.1

**Screenshots (Optional)**
![2023-08-02_17 43 14](https://github.com/henkelmax/sound-physics-remastered/assets/139589337/95cc375f-5e0a-48da-91a6-e7d6d4f0007e)

**Comment by henkelmax** [comment]
Please send me your mods configs

**Comment by resiresi1** [comment]
> Please send me your mods configs

it is the default configs, made a new curseforge instance with it so none could of changed

**Comment by henkelmax** [comment]
Please send me your client logs and all your mod configs.

**Comment by resiresi1** [comment]
> Please send me your client logs and all your mod configs.

It seems not to cause lag anymore

Log and config
[SFC.zip](https://github.com/henkelmax/sound-physics-remastered/files/12263668/SFC.zip)
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/12263662/latest.log)

I can give you the log and config for the client I originally experienced this issue on. However I ran into this issue again when only using the sound physics mod

**Comment by henkelmax** [comment]
Thank you for providing your logs and configs. I will investigate this issue.
