### ISSUE TITLE
My Server crashing.

### ISSUE THREAD

**Issue by KdGaming0** [henkelmax/sound-physics-remastered#128]
**Bug description**
My server crashes out of nothing when the mod is installed. I don't get anything in the console.

It just restarts.

Version
Fabric 1.20.2

Mods

![Screenshot 2023-08-07 125357](https://github.com/henkelmax/sound-physics-remastered/assets/97355992/315516b9-b820-458f-9aa1-2b8f6df5b697)
![Screenshot 2023-08-07 125339](https://github.com/henkelmax/sound-physics-remastered/assets/97355992/749a6ab8-57c4-43a6-97aa-2bde49dcabc5)

**Comment by henkelmax** [comment]
This mod is not available for 1.20.2 yet.

**Comment by KdGaming0** [comment]
> This mod is not available for 1.20.2 yet.

Soory meant and write 1.20.1

**Comment by henkelmax** [comment]
Then please open another ticket and actually fill out the template including logs.
