### ISSUE TITLE
Server restarts out of nowhere.

### ISSUE THREAD

**Issue by KdGaming0** [henkelmax/sound-physics-remastered#129]
**Bug description**
My server restarts out of nowhere when the mod is installed.
I can fly around on the server for hours and everything is fine until suddenly it restarts. after that it can happen many times in a row before it stops.

**Expected behavior**
The server not restarting out of nowhere.

Logs for server.  You won't find anything it restarts without anything in the console
[2023-08-07-3.log](https://github.com/henkelmax/sound-physics-remastered/files/12280729/2023-08-07-3.log)
[2023-08-07-2.log](https://github.com/henkelmax/sound-physics-remastered/files/12280723/2023-08-07-2.log)
[2023-08-07-1.log](https://github.com/henkelmax/sound-physics-remastered/files/12280725/2023-08-07-1.log)

![Screenshot 2023-08-07 125357](https://github.com/henkelmax/sound-physics-remastered/assets/97355992/82596593-53e0-42a1-8f62-a7729c2cc5de)
![Screenshot 2023-08-07 125339](https://github.com/henkelmax/sound-physics-remastered/assets/97355992/1dc10679-9b61-4e93-a359-c94609284099)
I also have this mod but not in the pictures.
**Versions**
- 1.20.1
- 0.14.22 fabric
- 1.1.2

Logs from when I had the 1.1.1 version of the mod installed then I got an error in the console. The exact same thing happens.

Can't find the log file but her is a copy of what I gave chat gpt

Error loading class: net/minecraft/class_4224 (java.lang.ClassNotFoundException: net/minecraft/class_4224)
@Mixin target net.minecraft.class_4224 was not found sound_physics_remastered.mixins.json:ChannelAccessor from mod sound_physics_remastered
main/INFO21:46:39
Mixing common.MixinFriendlyByteBuf from mixins/common/nochatreports.mixins.json into net.minecraft.class_2540
Renaming synthetic method lambda$onWriteJsonWithCodec$1(Ljava/lang/Object;Ljava/lang/String;)Lio/netty/handler/codec/EncoderException; to mdbdee16$nochatreports$lambda$onWriteJsonWithCodec$1$0 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
Renaming synthetic method lambda$onReadJsonWithCodec$0(Ljava/lang/String;)Lio/netty/handler/codec/DecoderException; to mdbdee16$nochatreports$lambda$onReadJsonWithCodec$0$1 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
21:46:43
Mixing server.MixinServerGamePacketListenerImpl from mixins/common/nochatreports.mixins.json into net.minecraft.class_3244

**Comment by henkelmax** [comment]
Sound Physics is a client side mod. It's not needed on the server. Despite this, I can't see any errors related to the mod.

**Comment by KdGaming0** [comment]
> Sound Physics is a client side mod. It's not needed on the server. Despite this, I can't see any errors related to the mod.

There are no advantages to having it on the server as well. From what I have noticed, it seems that it works a little better with it on the server, with the sound working in my house and not just in caves

**Comment by henkelmax** [comment]
Can you please send me the full logs as a file?

**Comment by KdGaming0** [comment]
> Can you please send me the full logs as a file?

Can't find it. Her is a copy of very thing I gave to chat gpt. And what are the benefits of having it on the server?

main/WARN21:46:38
Error loading class: net/minecraft/class_4224 (java.lang.ClassNotFoundException: net/minecraft/class_4224)
@Mixin target net.minecraft.class_4224 was not found sound_physics_remastered.mixins.json:ChannelAccessor from mod sound_physics_remastered
main/INFO21:46:39
Mixing common.MixinFriendlyByteBuf from mixins/common/nochatreports.mixins.json into net.minecraft.class_2540
Renaming synthetic method lambda$onWriteJsonWithCodec$1(Ljava/lang/Object;Ljava/lang/String;)Lio/netty/handler/codec/EncoderException; to mdbdee16$nochatreports$lambda$onWriteJsonWithCodec$1$0 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
Renaming synthetic method lambda$onReadJsonWithCodec$0(Ljava/lang/String;)Lio/netty/handler/codec/DecoderException; to mdbdee16$nochatreports$lambda$onReadJsonWithCodec$0$1 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
21:46:43
Mixing server.MixinServerGamePacketListenerImpl from mixins/common/nochatreports.mixins.json into net.minecraft.class_3244
21:46:44
[Dynmap]: Mod Support API available
Loaded fabric-tab
21:46:46
Loading extensions...
Loaded 0 extension(s)
Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
KONNICHIWA ZA WARUDO!
Default JVM text encoding is: UTF-8
Reading config file NoChatReports/NCR-Common.json...
Writing config file NoChatReports/NCR-Common.json...
Reloading reverb parameters
Done initializing TabTPS.
Compatibility version 17
Loading plugins
Loaded 3 plugin(s)
Initializing plugins
Initializing Simple Voice Chat integration
Initialized 3 plugin(s)
Registering events for enhancedgroups
Registering events for sound_physics_remastered
Registering events for vcinteraction
Successfully initialized antixray on fabric
Krypton is now accelerating your Minecraft server's networking stack 🚀
-----------------------------------------
MCDiscordChat (MCDC) 2.2.0
By Xujiayao
Console21:46:46
[19:46:46] [main/INFO]:
main/INFO21:46:46
More information + Docs:
https://blog.xujiayao.top/posts/4ba0a17a/
-----------------------------------------
21:46:47
Login Successful!
JDA MainWS-ReadThread/INFO21:46:47
Connected to WebSocket
21:46:48
Finished Loading!
Thread-13/INFO21:46:48
[ConsoleLog]: Starting new ConsoleLogListener
[ConsoleLog]: Listening to new latest.log
main/INFO21:46:48
Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
21:46:49
[Dynmap]: Register commands
21:46:50
Loaded 7 recipes
Loaded 1271 advancements
Mixing server.MixinDedicatedServer from mixins/common/nochatreports.mixins.json into net.minecraft.class_3176
Mixing server.MixinPlayerList from mixins/common/nochatreports.mixins.json into net.minecraft.class_3324
Applied 0 biome modifications to 0 of 64 new biomes in 1.431 ms
Server thread/INFO21:46:50
[Dynmap]: Added 20 custom biome mappings
[Dynmap]: Using fabric-permissions-api for access control
Starting minecraft server version 1.20.1
Loading properties
Default game type: SURVIVAL
Generating keypair
Starting Minecraft server on 0.0.0.0:25565
21:46:51
Using epoll channel type
Preparing level "world"
[Dynmap]: Mod Support processing completed
21:46:53
[Dynmap]: Loaded 28 shaders.
[Dynmap]: Loaded 83 perspectives.
[Dynmap]: Loaded 22 lightings.
[Dynmap]: Starting enter/exit processing
Dynmap Render Thread/INFO21:46:53
[Dynmap]: Finish marker initialization
Server thread/INFO21:46:54
[Dynmap]: Web server started on address 0.0.0.0:8123
[Dynmap]: version 3.6 is enabled - core version 3.6-899
[Dynmap]: For support, visit our Discord at https://discord.gg/s3rd5qn
[Dynmap]: For news, visit https://reddit.com/r/Dynmap or follow https://universeodon.com/@dynmap
[Dynmap]: To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[Dynmap]: If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
[Dynmap]: Loaded 3 maps of world 'world'.
[Dynmap]: Loaded 2 maps of world 'DIM-1'.
[Dynmap]: Loaded 2 maps of world 'DIM1'.
[Dynmap]: Loaded 177 pending tile renders for world 'world'
[Dynmap]: Full render for world 'world' restored
[Dynmap]: Register events
[Dynmap]: Enabled
21:46:56
Preparing start region for dimension minecraft:overworld
Netty Epoll Server IO #1/INFO21:46:58
Mixing server.MixinServerboundChatCommandPacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_7472
Mixing server.MixinServerboundChatPacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_2797
Mixing server.MixinServerboundChatSessionUpdatePacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_7861
Worker-Main-1/INFO21:46:59
Preparing spawn area: 0%
Worker-Main-3/INFO21:47:01
Preparing spawn area: 70%
Server thread/INFO21:47:02
Time elapsed: 5812 ms
Done (11.110s)! For help, type "help"
Mixing common.MixinServerStatus from mixins/common/nochatreports.mixins.json into net.minecraft.class_2926
Took 31ms to boot Floodgate
******************************************
Console21:47:02
[19:47:02] [Server thread/INFO]:
Server thread/INFO21:47:02
Loading Geyser version 2.1.2-SNAPSHOT (git-master-7b409fd)
Console21:47:02
[19:47:02] [Server thread/INFO]:
Server thread/INFO21:47:02
******************************************
21:47:05
Started Geyser on 0.0.0.0:19132
Done (3.166s)! Run /geyser help for help!
Added 0 persistent groups
VoiceChatServerThread/INFO21:47:05
Using server-ip as bind address: 0.0.0.0
Server thread/WARN21:47:05
Can't keep up! Is the server overloaded? Running 3334ms or 66 ticks behind
VoiceChatServerThread/INFO21:47:05
Voice chat server started at 0.0.0.0:24454
Server thread/INFO21:47:05
[Dynmap]: Loaded 135 pending tile renders for world 'world'
Dynmap Render Thread/INFO21:47:06
[Dynmap]: Loading default resource pack
21:47:21
[Dynmap]: Full render of map 'flat' of 'world' in progress - 60900 tiles rendered (191.81 msec/tile, 151.33 msec per render)
21:47:38
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61000 tiles rendered (191.77 msec/tile, 127.47 msec per render)
User Authenticator #1/INFO21:47:45
UUID of player Kd_Gaming1 is b3ac1fe2-a449-4c48-bceb-8d2006f2cdaf
Server thread/INFO21:47:46
Kd_Gaming1[/85.165.32.32:60396]: logged in with entity id 199 at (1131.5520503241116, -58.0, -345.2812018903239)
Using Fabric Permissions API
Kd_Gaming1 joined the game
21:47:47
Received secret request of Kd_Gaming1 (17)
Sent secret to Kd_Gaming1
VoiceChatPacketProcessingThread/INFO21:47:47
Successfully authenticated player b3ac1fe2-a449-4c48-bceb-8d2006f2cdaf
21:47:48
Successfully validated connection of player b3ac1fe2-a449-4c48-bceb-8d2006f2cdaf
Player Kd_Gaming1 (b3ac1fe2-a449-4c48-bceb-8d2006f2cdaf) successfully connected to voice chat
User Authenticator #2/INFO21:47:59
UUID of player _P00_ is 1fd13887-ff41-42fe-afe1-b187e6201957
Server thread/INFO21:47:59
_P00_[/85.165.3.16:52002]: logged in with entity id 489 at (598.4610754480562, 252.03038462360283, 608.083799576171)
_P00_ joined the game
21:48:00
Unknown or incomplete command, see below for error
spark tps<--[HERE]
Received secret request of _P00_ (17)
Sent secret to _P00_
VoiceChatPacketProcessingThread/INFO21:48:00
Successfully authenticated player 1fd13887-ff41-42fe-afe1-b187e6201957
Dynmap Render Thread/INFO21:48:01
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61100 tiles rendered (191.81 msec/tile, 133.83 msec per render)
VoiceChatPacketProcessingThread/INFO21:48:01
Successfully validated connection of player 1fd13887-ff41-42fe-afe1-b187e6201957
Player _P00_ (1fd13887-ff41-42fe-afe1-b187e6201957) successfully connected to voice chat
Server thread/INFO21:48:05
Mean tick: 14ms increasing chunk view distance to: 20
Dynmap Render Thread/INFO21:48:21
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61200 tiles rendered (191.83 msec/tile, 140.33 msec per render)
Server thread/INFO21:48:35
Mean tick: 25ms increasing simulation distance to: 15
Dynmap Render Thread/INFO21:48:37
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61300 tiles rendered (191.78 msec/tile, 135.23 msec per render)
21:48:53
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61400 tiles rendered (191.72 msec/tile, 130.41 msec per render)
Server thread/INFO21:49:05
Mean tick: 21ms increasing chunk view distance to: 21
Dynmap Render Thread/INFO21:49:11
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61500 tiles rendered (191.69 msec/tile, 130.65 msec per render)
21:49:28
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61600 tiles rendered (191.66 msec/tile, 130.36 msec per render)
Kd_Gaming121:49:28
group
Server thread/INFO21:49:35
Mean tick: 22ms increasing simulation distance to: 16
Dynmap Render Thread/INFO21:49:46
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61700 tiles rendered (191.63 msec/tile, 129.57 msec per render)
21:50:02
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61800 tiles rendered (191.59 msec/tile, 128.52 msec per render)
Server thread/INFO21:50:05
Mean tick: 19ms increasing chunk view distance to: 22
Dynmap Render Thread/INFO21:50:21
[Dynmap]: Full render of map 'flat' of 'world' in progress - 61900 tiles rendered (191.58 msec/tile, 129.16 msec per render)
Server thread/INFO21:50:35
Mean tick: 18ms increasing simulation distance to: 17
Dynmap Render Thread/INFO21:50:38
[Dynmap]: Full render of map 'flat' of 'world' in progress - 62000 tiles rendered (191.53 msec/tile, 128.58 msec per render)
21:50:54
[Dynmap]: Full render of map 'flat' of 'world' in progress - 62100 tiles rendered (191.48 msec/tile, 127.82 msec per render)

**Comment by henkelmax** [comment]
Posing it in plain text is basically unreadable.

**Comment by KdGaming0** [comment]
> Posing it in plain text is basically unreadable.

Sorry, don't have the log file. but want to know what are the advantages of having it on the server.

**Comment by henkelmax** [comment]
The only thing the mod does on the server is send sounds to the player that are further away.

**Comment by KdGaming0** [comment]
> The only thing the mod does on the server is send sounds to the player that are further away.

[crash-2023-07-30_18.03.56-server.txt](https://github.com/henkelmax/sound-physics-remastered/files/12283165/crash-2023-07-30_18.03.56-server.txt)
Tanks fund a crash report but ar not 100% sure it's a crash from the mod or something else.

**Comment by henkelmax** [comment]
Yeah this error is not caused by the mod.

**Comment by KdGaming0** [comment]
ok tanks do you now what the reason for it is. because it only happens with this mod.
