### ISSUE TITLE
Mod File soundphysics-forge-1.20.1-1.1.1.jar needs language provider javafml:47 or above to load

### ISSUE THREAD

**Issue by KhevanT** [henkelmax/sound-physics-remastered#130]
**Bug description**
Error message that prevents forge from launching

**Steps to reproduce the issue**
1. Load version soundphysics-forge-1.20.1-1.1.1.jar in forge-1.20-46.0.14

**Expected behavior**
An error-free loading of the mod in forge

**Log files**
File has been attached with this issue.
[crash-2023-08-07_22.46.11-fml.txt](https://github.com/henkelmax/sound-physics-remastered/files/12283438/crash-2023-08-07_22.46.11-fml.txt)

**Versions**
- Minecraft version - 1.20
- Forge/Fabric loader version - forge-1.20-46.0.14-installer
- Mod version - soundphysics-forge-1.20.1-1.1.1.jar

**Other mods**
A list of the other mods that were installed when this problem occurred:
(Can be found in the screenshot attached)
![Screenshot 2023-08-07 225220](https://github.com/henkelmax/sound-physics-remastered/assets/65601486/193b1ddb-8197-4e8e-9a28-51953b8e4b9c)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
You are using 1.20 but the mod is for 1.20.1

**Comment by KhevanT** [comment]
Oh I'm so sorry I didn't know that. Thank you for letting me know!
