### ISSUE TITLE
Sound Physics bug when using [Let's Do] Beachparty mod

### ISSUE THREAD

**Issue by EnderGirl1500** [henkelmax/sound-physics-remastered#131]
**Bug description**
When using both Sound Physics and [Let's Do] Beachparty, we hear pelican sounds constantly as if they were next to us. This happens when there are pelicans in the same chunk as us.

**Steps to reproduce the issue**
1. Install both Sound Physics and [Let's Do] Beachparty
2. Create a new world
3. Find or spawn pelicans
4. See how even if you go away, their sounds continue super loud until you leave the chunk

**Expected behavior**
Pelican sounds should behave as the other ones - the further, the lower.

**Versions**
- Minecraft version: 1.20.1
- Fabric loader version: 0.14.22
- Mod version: both 1.1.1 and 1.1.2

**Comment by henkelmax** [comment]
`Let's Do: Beachparty` uses stereo sound files, which are not properly supported by Minecraft.
See here:
https://forge.gemwire.uk/wiki/Sounds
![image](https://github.com/henkelmax/sound-physics-remastered/assets/13237524/412d06b9-5470-490d-a2e6-b53731b5c167)

Here you can see that they are using stereo sound files.
![image](https://github.com/henkelmax/sound-physics-remastered/assets/13237524/a540b646-2c4b-4586-93d1-528f943c4b23)
