### ISSUE TITLE
Ecthed radios sound do not update when moving

### ISSUE THREAD

**Issue by Benoxiid** [henkelmax/sound-physics-remastered#133]
**Bug description**
When using radios from the "Etched" mod (and playing an mp3 live audio stream), the filter will not update.
The sound will correctly play at the right intensity, but the muffled (low-pass filter) effect will not update, it will stay at the state it last had when starting the radio OR reloading sounds.

**Steps to reproduce the issue**
Install "Etched" 2.3.1
Install "Sound Physics Remastered" 1.0.18
Give yourself a radio from etched, place it into the world, and make it play an audio stream (Was using bassdrive.radioca.st/stream )
Reload sound when behind a wall, then move out of the way of the wall. Notice how the low-pass updates only when reloading.

**Expected behavior**
When having direct LoS to the radio, the sound should become unmuffled, and vice-versa

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft 1.19.2
- Forge 43.2.21
- Etched 2.3.1
- Sound Physics Remastered 1.0.18

**Other mods**

AI-Improvements-1.19.2-0.5.2.jar
AkashicTome-1.6-23.jar
Alexs Armoury v1.4.1-1.19.2.jar
alexsdelight-1.4.1.jar
alexsmobs-1.21.1.jar
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.5.85-forge.jar
ars_creo-1.19.2-3.2.1.jar
ars_elemental-1.19.2-0.5.9.1.2b.jar
ars_nouveau-1.19.2-3.17.10.jar
art_of_forging-1.6.7-1.19.2.jar
AttributeFix-Forge-1.19.2-17.2.7.jar
AutoRegLib-1.8.2-55.jar
balm-forge-1.19.2-4.5.7.jar
bettercombat-forge-1.7.1+1.19.jar
chipped-forge-1.19.2-2.1.5.jar
citadel-2.1.4-1.19.jar
cloth-config-8.3.103-forge.jar
Clumps-forge-1.19.2-9.0.0+14.jar
configured-2.1.1-1.19.2.jar
Controlling-forge-1.19.2-10.0+7.jar
CorgiLib-forge-1.19.2-1.0.0.34.jar
corpse-1.19.2-1.0.0.jar
craftingtweaks-forge-1.19.2-15.1.8.jar
create-1.19.2-0.5.1.c.jar
create-stuff-additions1.19.2_v2.0.3b.jar
createdeco-1.3.3-1.19.2.jar
create_central_kitchen-1.19.2-for-create-0.5.1.c-1.3.9.c.jar
create_crystal_clear-0.2.1-1.19.2.jar
create_enchantment_industry-1.19.2-for-create-0.5.1.c-1.2.6.jar
create_sabers-1.19.2-1.3.0.jar
CTM-1.19.2-1.1.6+8.jar
culturaldelights-1.19.2-0.15.4.jar
curios-forge-1.19.2-5.1.4.1.jar
Decorative Blocks-forge-1.19.2-3.0.0.jar
Delightful-1.19.2-3.3.jar
Ding-1.19.2-Forge-1.4.1.jar
endsdelight-1.19.2-1.2.1.jar
entityculling-forge-1.6.1-mc1.19.2.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
etched-forge-2.3.1.jar
FarmersDelight-1.19.2-1.2.3.jar
FastLeafDecay-30.jar
Fastload-Reforged-8.2.1+1.19.2.jar
FastSuite-1.19.2-4.1.1.jar
flywheel-forge-1.19.2-0.6.8.a.jar.disabled
ftb-chunks-forge-1902.4.1-build.290.jar
ftb-library-forge-1902.4.1-build.236.jar
ftb-teams-forge-1902.2.14-build.123.jar
ftbbackups2-forge-1.19.2-1.0.19.jar
geckolib-forge-1.19-3.1.40.jar
jei-1.19.2-forge-11.6.0.1016.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.2.236.jar
lazydfu-1.19-1.0.2.jar
lightspeed-1.19.2-1.0.5.jar
lootr-1.19-0.4.24.64.jar
mcw-bridges-2.1.1-mc1.19.2forge.jar
mcw-doors-1.1.0forge-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-furniture-3.1.0-mc1.19.2forge.jar
mcw-lights-1.0.6-mc1.19.2forge.jar
mcw-paths-1.0.3forge-mc1.19.2.jar
mcw-roofs-2.2.4-mc1.19.2forge.jar
mcw-trapdoors-1.1.1-mc1.19.2forge.jar
mcw-windows-2.1.1-mc1.19.2forge.jar
memoryleakfix-forge-1.17+-1.0.0.jar
modelfix-1.8.jar
molten_vents-1.19.2-0.2.0.jar
moonlight-1.19.2-2.2.43-forge.jar
moreminecarts-1.5.7.jar
MouseTweaks-forge-mc1.19-2.23.jar
mutil-1.19.2-5.1.0.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
netherportalfix-forge-1.19-10.0.1.jar
NethersDelight-1.19-3.0.jar
NoChatReports-FORGE-1.19.2-v1.5.1.jar
oceansdelight-1.0.2-1.19.2.jar
oculus-flywheel-compat-1.19.2-0.2.1.jar.disabled
oculus-mc1.19.2-1.6.4.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4.jar
Patchouli-1.19.2-77.jar
Placebo-1.19.2-7.3.2.jar
player-animation-lib-forge-1.0.2.jar
pollen-forge-2.1.0.jar
polylib-forge-1900.0.2-build.73.jar
polymorph-forge-0.46.4+1.19.2.jar
PrettyPipes-1.13.6.jar
Quark-3.4-405.jar
ReAuth-1.19-Forge-4.0.7.jar
resourcefullib-forge-1.19.2-1.1.24.jar
rubidium-0.6.2b.jar
ShoulderSurfing-Forge-1.19.2-2.4.1.jar
shutupexperimentalsettings-1.0.5.jar
sophisticatedbackpacks-1.19.2-3.18.55.889.jar
sophisticatedcore-1.19.2-0.5.83.394.jar
sophisticatedstorage-1.19.2-0.8.40.581.jar
soundphysics-forge-1.19.2-1.0.18.jar
spark-1.10.37-forge.jar
starlight-1.1.1+forge.cf5b10b.jar
Steam_Rails-1.4.3+forge-mc1.19.2.jar
StorageDrawers-1.19-11.1.2.jar
supplementaries-1.19.2-2.3.20.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
tetra-1.19.2-5.4.0.jar
tetrasdelight-1.19.2-1.jar
tetratic-combat-1.19-2.6.1.jar
ToastControl-1.19.2-7.0.0.jar
XaerosWorldMap_1.31.0_Forge_1.19.1.jar
Xaeros_Minimap_23.6.0_Forge_1.19.1.jar
YungsApi-1.19.2-Forge-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsBridges-1.19.2-Forge-3.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar

**Additionnal notes**
Do not hesitate to contact me if you need more context and/or help. I do have a lot of free time.

**Comment by henkelmax** [comment]
Did you enable moving sounds in the config?

**Comment by Benoxiid** [comment]
Yes, but I did not restart the game, It works now !
Thank you for your time :)

**Comment by Benoxiid** [comment]
I do suggest adding interpolation between filter values over time, though !
