### ISSUE TITLE
Valkyrie Skies Issues

### ISSUE THREAD

**Issue by Autumnlight02** [henkelmax/sound-physics-remastered#136]
**Bug description**
Crashes the Game When in use with Valkyrie Skies under special circumstances.

**Steps to reproduce the issue**
1. Install ValkyrieSkies with Eureka and install Waystones + this mod.
2. Place a waystone at spawn.
3. Fly 60 chunks away (If you load the chunk you teleport to sometimes it survives the crash)
4. Now build a really small eureka vessel, assemble it and add a waystone on it.
![image](https://github.com/henkelmax/sound-physics-remastered/assets/68244453/6902a25c-d382-4383-890b-3d467e02998a)

5. Go back to the waystone at the spawn and wait there 10 seconds to let the game unload the chunks.
6. Now teleport to it and crash

**Expected behavior**
That you can use the Waystone on the ship (It worked for me aslong as i had sound disabled)

**Log files**
[Logs](https://gist.github.com/Autumnlight02/065add1c7bf33a80d4604fb9e9164560)

--------------------------- **Why Does This happen?** ---------------------------
Valkyrie Skies Is an new upcomming amazing engine Which allows you to build ships and fully interact with them.
The way it works is as following:
When you assemble your Ship it basically duplicates all blocks on the world border. And then sends you a mirror, with which you can fully interact (chest block placing etc) And it feels like having a secondary coordinate system in minecraft)
Basically When you do an interaction like using a Waystone, You teleport to the world border, But that mod detect that teleport and automatically adjust your teleport to your new position (where the ship is). That works great with all kinds of mods. (besides this one).

So My assumption is that the sounds are likely too far away and that its confusing this mod, or that the chunks where the sounds play are not loaded and that causes the crash. 

--------------------------- **Possible fix?** ---------------------------
I could assume a possible fix would be to not play sounds out of bounds (The teleportation is so fast that it wont even render a frame). Or to introduce a special patch if valkyrie is installed

**Versions**
- Minecraft version : 1.18.2 - 40.2.10 && 40.2.7 (tested both)
- Forge/Fabric loader version: Forge 40.2.10
- Mod version : soundphysics-forge-1.18.2-1.0.6.jar

**Other mods**
![image](https://github.com/henkelmax/sound-physics-remastered/assets/68244453/04956196-548f-497f-a895-6a78c6596a0d)

**Screenshots (Optional)**
Screenshots of the issue.

Additional Notes:
Some people mentioned on the Discord that they also crash during ship assemble, This would likely also resolve that issue.

To see where the ship gets generated, simply install journeysmap and place a -beacon- Waystone* on a ship, the automatically generated waypoint will reveal the coordinates of the ship emulation area

**EDIT**
I narrowed it down to the Player sounds:
![image](https://github.com/henkelmax/sound-physics-remastered/assets/68244453/458c5fca-79fc-4d80-8304-15ffb3b4d877)

**Comment by henkelmax** [comment]
This mod version is no longer supported.
