### ISSUE TITLE
[Bug] own player hurt sound gets muffled while head is above lava/water

### ISSUE THREAD

**Issue by EnderMelody** [henkelmax/sound-physics-remastered#137]
**Bug description**
standing in lava/water while being hurt muffles the hurt sounds (burning/damage sfx) even when the players head is above the water/lava

**Steps to reproduce the issue**
jump in lava and start burning
keep head out of the lava but sounds are still muffled

**Expected behavior**
sfx to only be muffled when head is submerged

**Log files**
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/12527515/latest.log)

**Versions**
- Minecraft: 1.20.1
- Quilt: 0.20.2
- SPR: 1.2.1

**Other mods**
none

**Comment by ryleu** [comment]
this also occurs with sounds like leaving the water. i think they emit from the feet rather than the head and that's the issue maybe?

**Comment by qb20nh** [comment]
Sounds that are meant to be made at the water surface should both propagate above and under water.

**Comment by zeid0ne** [comment]
i have the same bug
