### ISSUE TITLE
rowing a boat is silent 

### ISSUE THREAD

**Issue by blingoDaKilla** [henkelmax/sound-physics-remastered#138]
**Bug description**
no boat sounds 

**Steps to reproduce the issue**
get on boat and listen

**Expected behavior**
boat rowing sounds

**Versions**
- Minecraft version 1.20.1
- fabric 0.14.22
- Mod version 1.2.1

**Other mods**
sodium. lithium, indium, mod menu and cloth api

**Comment by icynstant** [comment]
same and its with most (or all) of the sounds underwater. if some1 knows how to fix it tag me pls

**Comment by icynstant** [comment]
mod version 1.2.0 works fine

**Comment by blingoDaKilla** [comment]
> 

the underwater sounds come back when i turn down the filter, but the boats still not there. only comes back when i disable sound physics

**Comment by OneLoneFox** [comment]
Can confirm on 1.2.1 all sounds underwater are almost entirely muted despite having the underwater filter on 0

**Comment by Answordy** [comment]
Yeah, 1.2.1 mc 1.19.2 has this problem, can confirm too

**Comment by Tp-danny** [comment]
Same issue here, when in a boat, on 1.19.2, I get no sounds that you would expect for interactions with the water, ambient sounds still play. When swimming etc. the mod works as expected, so I think it's boat specific.
