### ISSUE TITLE
[Question] How to make a house that doesnt echo

### ISSUE THREAD

**Issue by milkev** [henkelmax/sound-physics-remastered#139]
**Issue description**
I've been using this mod for a while, and exploring the world and going through caves and everything is great. I love how sound bounces around and the echo in caves. The only problem is that i cant seem to make a house that doesnt echo like crazy. Ive tried reducing the reflectivity of wood but it made no difference (i believe) since my floor is made of a stone material. Theres no echo if i make my room fully out of wool or similar low reflectivity materials, but that greatly limits the blocks im able to use to only a handful of niche building blocks.

The echo makes the house feel empty, even ive got lots of stuff in it... it can feel sad sometimes and I'd rather have a solution to this than to disable the mod when im at my base.

**Steps to reproduce the issue**
1. build a house / room
2. make some sound, walk around, open chest, etc
3. echo sounds extremely similar / the same as caves

**Desired behavior**
I dont want my house to feel echo-y and empty.

**Versions**
- Minecraft version: 1.20.1
- Forge/Fabric loader version: Fabric 0.14.22
- Mod version: 1.1.2

**Other mods**
Can provide if you want, but I dont believe its relevant here.

**Screenshots (Optional)**
![image](https://github.com/henkelmax/sound-physics-remastered/assets/22010128/eca27991-f09f-46fd-ac2f-c4a8d38afd8d)
[Medal Clip with audio of echoing](https://medal.tv/games/minecraft/clips/1sSAutvH7Gr8b1/d1337OrQa6Pu?invite=cr-MSxHUDUsOTQ0OTM5NTQs)

**Comment by henkelmax** [comment]
You can change the reflectivity of the blocks you use in your house in the config.

**Comment by milkev** [comment]
I only see config options for generic block types like "stone". so if i reduce that, ill no longer have echo in caves too

**Comment by milkev** [comment]
I updated to the latest alpha version on modrinth, I dont see any options in config to add blocks. How do I do that?

Also with the alpha version, i can hear mobs in caves way below my base as if they were right next to me... maybe an issue with my config? I'll try regenerating it and see if that fixes it...

**Comment by henkelmax** [comment]
>  If this is possible in a future update that would be really cool

Unfortunately thats not possible with cloth config.
