### ISSUE TITLE
Is this sound physics releated to sonic ether?

### ISSUE THREAD

**Issue by SoundEngineDevelopement** [henkelmax/sound-physics-remastered#14]
I just saw this: vlad2305m/Sound-Physics-Fabric
https://github.com/vlad2305m/Sound-Physics-Fabric

Question is if this is sound engine is releated to sonic ether or a completly new one?

**Comment by vlad2305m** [comment]
> I just saw this: vlad2305m/Sound-Physics-Fabric https://github.com/vlad2305m/Sound-Physics-Fabric
> 
> Question is if this is sound engine is releated to sonic ether or a completly new one?

He will not work on it regardless (most likely)

**Comment by SoundEngineDevelopement** [comment]
> > I just saw this: vlad2305m/Sound-Physics-Fabric https://github.com/vlad2305m/Sound-Physics-Fabric
> > Question is if this is sound engine is releated to sonic ether or a completly new one?
> 
> He will not work on it regardless (most likely)

I tryed using this sound engine with 1.18 but its not working. I will stick to fabri over forge from now on.

**Comment by vlad2305m** [comment]
> > > I just saw this: vlad2305m/Sound-Physics-Fabric https://github.com/vlad2305m/Sound-Physics-Fabric
> > > Question is if this is sound engine is releated to sonic ether or a completly new one?
> > 
> > 
> > He will not work on it regardless (most likely)
> 
> I tryed using this sound engine with 1.18 but its not working. I will stick to fabri over forge from now on.

You may as well use iris over optifine.

**Comment by henkelmax** [comment]
> I just saw this: vlad2305m/Sound-Physics-Fabric https://github.com/vlad2305m/Sound-Physics-Fabric
> 
> Question is if this is sound engine is releated to sonic ether or a completly new one?

It builds on top of this project, but almost everything is rewritten. I wouldn't call it a sound engine though.
