### ISSUE TITLE
Confusing Sound Issue related to Biome Makeover

### ISSUE THREAD

**Issue by milkev** [henkelmax/sound-physics-remastered#140]
**Bug description**
Under certain conditions, with Biome Makeover installed, mob sounds are heard even through 30+ blocks of stone.
Due to loading the world initially with many mods, there are voids from blockus/etc, however these voids have not effected this issue at all. This issue occured both before and after loading the world with my original mod list vs cut down list

**Steps to reproduce the issue**
1. I provided a .zip containing the world file I used to repeat this... I wasnt able to replicate this issue on other worlds
[CreatePowerhouse Main Testing.zip](https://github.com/henkelmax/sound-physics-remastered/files/12548634/CreatePowerhouse.Main.Testing.zip)
2. Launch the game with Sound Physics Remastered & Biome Makeover (latest versions as of this post, specific numbers below)
3. Load into world, hear zombies & other mobs. They are in a cave below the large water lake under the player. The cave itself is from Profundis.
4. Remove Biome makeover and repeat, no mobs are heard through stone.
5. Going back to the latest beta version of Sound Physics Remastered (1.1.2) also fixes this issue.

**Expected behavior**
Mobs in caves cannot be heard from the surface

**Log**
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/12548844/latest.log)

**Versions**
- Minecraft version: 1.20.1
- Forge/Fabric loader version: fabric 0.14.22
- Sound Physics Remastered version: Alpha 1.2.1
- Architectury version: 9.1.12
- Biome Makeover version: 1.10.0

**Comment by henkelmax** [comment]
Does this happen with vanilla sounds o only with sounds from mods?

**Comment by milkev** [comment]
the 3 main ones i noticed were zombie, enderman and skeleton idle sounds. The vanilla ones, as far as im aware.
