### ISSUE TITLE
Crashes JVM with SIGFPE

### ISSUE THREAD

**Issue by scarlettekk** [henkelmax/sound-physics-remastered#143]
**Bug description**
On Minecraft 1.20.1 (fabric), attempting to launch the game with Sound Physics Remastered causes a JVM crash with error SIGFPE (0x8). 

**Steps to reproduce the issue**
1. Install Minecraft 1.20.1 with the Fabric modloader (I used Prism Launcher)
2. Launch the game

**Expected behavior**
The game should launch with no fatal errors

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.20.1
- Forge/Fabric loader version 0.14.22
- Mod version 1.2.1

**Other mods**
 Others mods in the instance are the Fabulously Optimized mods, but as you can see in the logs I disabled all of them except for Sound Physics Remastered and the error still occurs

**Screenshots (Optional)**
N/A

**Comment by henkelmax** [comment]
I can't help you without logs and the crash report.

**Comment by scarlettekk** [comment]
Sorry, could have sworn I attached the logs. I'll do it next time I'm at my computer.

**Comment by scarlettekk** [comment]
Here are the logs, is the crash report a different thing? 
https://gist.github.com/scarlettekk/d9db467a9523dd4617adc4d4ce5791cf

**Comment by xexvisualz** [comment]
I use Prism Launcher too and I get the same output as showed in the logs as well.

**Comment by henkelmax** [comment]
Does this happen with the vanilla launcher aswell?
I am not able to reproduce this issue on either of these launchers.

**Comment by KruASe76** [comment]
for me, this issue happens in these situations:
most of the time, while reloading resources the window stops responding and then the game crashes with this error message (however, entering a server with a server resource pack is fine, but exiting it crashes)
also sometimes minecraft crashes while loading when the game window is not focused (unfocused right after the appearance), i assume, due to the same reason (while the resources are loaded)
btw, i also use PrismLauncher

**Comment by mariospicross** [comment]
also crashes for me.
[log](https://github.com/henkelmax/sound-physics-remastered/files/12758412/latest.log)

**Comment by AruMoon** [comment]
It also crashes with other launchers. Tested with llaun.ch

**Comment by AruMoon** [comment]
Found out that OpenAL crashes on the JACK audio backend. No crash on the Pulse backend.
Backend can be changed with `ALSOFT_DRIVERS` env or config

**Comment by flerouwu** [comment]
Can confirm this issue. Tried using the [SeriousPack modpack](https://modrinth.com/modpack/seriouspack/). Adding the environment variable from @AruMoon fixed the issue.

**Logs**
- [Game Log](https://mclo.gs/jZY5lVE)
- [JVM Crash Log](https://mclo.gs/GN0tWut)

**Comment by ffernn-dev** [comment]
> `ALSOFT_DRIVERS=pulse`

Thanks so much this works! I'm using Pipewire and Pipewire-pulse and I have no issues. Maybe add something in the README to the tune of 
> Linux users note: To avoid crash on startup add `ALSOFT_DRIVERS=pulse` to your environment variables. This assumes you have pulseaudio or pipewire-pulse installed.

**Comment by C4PTRAMPAGE** [comment]
"add `ALSOFT_DRIVERS=pulse` to your environment variables."

yeah, i have no idea how to do that.

**Comment by Light034** [comment]
I'm having the exact same issue, I can confirm setting the environment variable fixes the issue.

> "add `ALSOFT_DRIVERS=pulse` to your environment variables."
> 
> yeah, i have no idea how to do that.

You can do it in 2 ways, type `export ALSOFT_DRIVERS=pulse` in the terminal and then launch the launcher that you want to use through the terminal, or if you wish you can also edit your environment file to have it saved permanently, file is located is `/etc/environment` and you need have root to be able to edit it. Just add the same thing to the end of the variable list and save it. That should permanently save the environment variable for the future.

**Comment by henkelmax** [comment]
I think there is nothing that I can do about that in the mod. I will add this

> Found out that OpenAL crashes on the JACK audio backend. No crash on the Pulse backend. Backend can be changed with `ALSOFT_DRIVERS=pulse` env or config

to the documentation.
If anyone has another solution for this issue, please let me know.

**Comment by develcooking** [comment]
@Light034 
> You can do it in 2 ways, type `export ALSOFT_DRIVERS=pulse` in the terminal and then launch the launcher that you want to use through the terminal, or if you wish you can also edit your environment file to have it saved permanently, file is located is `/etc/environment` and you need have root to be able to edit it. Just add the same thing to the end of the variable list and save it. That should permanently save the environment variable for the future.

You also could add the environmet variable to only prism. Edit your .desktop entry for prism launcher its located in `/usr/share/applications/ `if you are using a native packages. The name of mine ist `org.prismlauncher.PrismLauncher.desktop`. 

Edit there as root the Exec command from:
`Exec = prismlauncher %U`
to:
`Exec = env ALSOFT_DRIVERS=pulse prismlauncher %U`

now the environment variable applies only to Prism. Therefor the likely hoot of breaking another app is elemented .

**Comment by enbyd** [comment]
For anyone who may still find their way to this issue:
With some back-and-forth with another person running a near identical environment to me but not experiencing a crash, we were able to find that updating LWJGL 3 to version `3.3.2` (from `3.3.1`) resolved the crash on launch and the mod seems to function as expected.
This is possible in Prism Launcher by going to the "Edit" screen of your selected instance and going to the "Version" tab of the window. Click on the entry for LWJGL and then click "Change Version". Select version 3.3.2 and launch as normal. 
Setting the `ALSOFT_DRIVERS` environment variable is not required for this workaround, though that approach did still work for me when I tested it separately.

**Comment by TheOverpassArsonist** [comment]
> For anyone who may still find their way to this issue: With some back-and-forth with another person running a near identical environment to me but not experiencing a crash, we were able to find that updating LWJGL 3 to version `3.3.2` (from `3.3.1`) resolved the crash on launch and the mod seems to function as expected. This is possible in Prism Launcher by going to the "Edit" screen of your selected instance and going to the "Version" tab of the window. Click on the entry for LWJGL and then click "Change Version". Select version 3.3.2 and launch as normal. Setting the `ALSOFT_DRIVERS` environment variable is not required for this workaround, though that approach did still work for me when I tested it separately.

I just started running into this issue (zero idea why, literally a few days ago it was perfectly fine and now it's happening even inside of my flatpaked GDLauncher Legacy install) but I can't figure out how to change this version or even apply the environment variable to the instance. (either in Legacy GDLauncher or Carbon) 

The closest I've gotten is by adding "-DALSOFT_DRIVERS=pulse" to "Instance Java Arguments" in GDLauncher Carbon's settings for the instance, but even that still crashes with the same error. (everything else I've tried has made it crash _instantly,_ before even reaching the point where it can crash because of this issue)
