### ISSUE TITLE
Underwater sounds not working correctly

### ISSUE THREAD

**Issue by Thelegendking** [henkelmax/sound-physics-remastered#149]
**Bug description**
No sound from mobs under water.

**Steps to reproduce the issue**
1. Go to near a lake, or ocean or anything that has alot of water
2. Click on crouch to go inside water
3. Hurt any monster inside the water
4. You'll hear no sound

**Expected behavior**
No or very very low sound from mob under water even if  they are one block away.

**Versions**
- Minecraft version 1.20.1
- Fabric loader for 1.20.1
- Mod version latest one for 1.20.1
.

**Comment by Allexio** [comment]
Because my issue got closed, here is what I wrote on my side for easy access here (since apparently this is the same issue):
I personally do not hear ANY sound underwater unless I am directly touching the block I am hitting/destroying.
I even tried setting `underwater filter` to 0

I am on 1.20.1 Fabric.
Latest version of Fabric loader for 1.20.1.
Mod version is also latest for 1.20.1 (1.2.1)

No other mods impact sound except for plasmovoice & presence footsteps.

**Comment by DDunda** [comment]
I want to add that I cannot hear any sounds even when standing waist deep in water. I have also tried turning the underwater filter to 0, and decreasing block absorption as well without improvement. I am on 1.2.1 for version 1.19.2, forge.

**Comment by carefreeDesigner** [comment]
As of 11/25/2023 this is still an issue.
I'm on 1.20.1 on mod version 1.2.1. I've tried editing the underwater filter from 1.0 to 0.5 to 0.01 to 0.0 and none had any changes whatsoever. Any sound underwater is so quiet, if it's even there, that it might as well not exist. This also applies when the Player is in one block or water or swimming on the surface. Sounds like eating or entering/exiting the water are next to inaudible.

Here's my modlist, if it'll help fix this issue:
https://pastebin.com/PYq04DDd

**Comment by EGOIST1372** [comment]
Hi
I'm on latest version for fabric 1.21.7 (sound-physics-remastered-fabric-1.21.7-1.4.14)
and I have this issue that I can't hear anything under water no matter what
Unless I'm inside a air pocket (A door under water) so I can hear sounds
If you break blocks or hurt mobs under water you can't hear anything at all
I hope this issue get re-open and fix
Thanks in advance <3

**Comment by EGOIST1372** [comment]
@henkelmax New info
I deleted all the files in config folder of the mod and now everything work as intended
so it was a bugged config file from old versions (I updated from 1.21 to 1.21.7 and something in between seems went wrong between those version's config files
sorry for inconvenience
