### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by xz123456xz** [henkelmax/sound-physics-remastered#15]
**Bug description**
The remote weapons that use the Blue Skies mod will conflict with the soundphysics mod, causing the game to crash.

**Steps to reproduce the issue**
1. Spear shooting

**Expected behavior**

**Log files**
https://gist.github.com/xz123456xz/a57895c6fcc2da78b698896cba7dc043

**Versions**
- Minecraft version : 1.17.1
- Forge/Fabric version : forge
- Mod version : 1.17.1-37.1.0-installer

**Other mods**
Blue Skies

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
Does this happen without the sound pyhsics mod?

**Comment by xz123456xz** [comment]
Except for spear weapons, there are no problems with other weapons. They are all normal.

**Comment by xz123456xz** [comment]
soundphysics mod Everything is normal when not installed

**Comment by henkelmax** [comment]
This seems to be also related to the blue skies mod. I can't look into their code, since it's closed source. So please report this issue to them first.

**Comment by xz123456xz** [comment]
blue skies mod This will reply me.

I will look into it a bit more. If we have a fix, it will make it into 1.18. It's unlikely we'll be updating anything else, but we'll see

**Comment by henkelmax** [comment]
Closed due to inactivity.
