### ISSUE TITLE
No sound underwater 

### ISSUE THREAD

**Issue by Allexio** [henkelmax/sound-physics-remastered#150]
**Bug description**

**Steps to reproduce the issue**
1. Set underwater filter to 0 (to test)
2. Go to water,
3. Hit/destroy any block,
4. Sometimes there is sound, sometimes there isn't (gravel I very rarely hear, so good to test).

It's like there is an extra attenuation *on top of* the water attenuation.

**Expected behavior**
A clear and concise sound of hitting and/or destroying the block

**Log files**
Not sure what log file you want me to provide for this kind of issue.

**Versions**
- Minecraft version: 1.20.1
- Fabric loader version: Latest for 1.20.1
- Mod version: Latest for 1.20.1 (1.2.1)

**Other mods**
No other mods impact sound except for plasmovoice & presence footsteps.

**Comment by henkelmax** [comment]
Duplicate of #149
