### ISSUE TITLE
Game hangs on loading world

### ISSUE THREAD

**Issue by Trblestrife** [henkelmax/sound-physics-remastered#151]
**Bug description**
Game hangs on "Loading world" screen when joining multiplayer server, or sometimes when teleporting

**Steps to reproduce the issue**
1. Join or teleport between places on a multiplayer server
2. Game will hang indefinitely until force quit

**Expected behavior**
Game loads and does not hang

**Log files**
https://gist.github.com/Trblestrife/57e98d0bc3f727a84239b3966f1db71b#file-gistfile1-txt

**Versions**
- 1.20.1
- Fabric loader 0.14.22
- 1.20.1-1.2.1

**Other mods**
Tested with other mods and on its own

**Screenshots (Optional)**

**Comment by Kizzycocoa** [comment]
Can confirm. Happens constantly for me on 2B2T. Narrowed down the problem mod to this one. happens when all alone, 1.2.1.

**Comment by henkelmax** [comment]
Is there a way to reproduce this consistently?
Can you check if this still happens in the latest version?

**Comment by henkelmax** [comment]
Closed due to inactivity. Please feel free to reopen if it still happens in the latest version.
