### ISSUE TITLE
Funky Cavernous Sound Projection

### ISSUE THREAD

**Issue by Peonovic** [henkelmax/sound-physics-remastered#153]
**Bug description**
Various circumstances can cause sound to project absurd distances while sounding like you're inside a cave.

**Steps to reproduce the issue**
1. Find or create a cave.
2. Insert something that generates noise other than fluids (they do not seem to cause problems).
3. Hover away while remaining in line with the cave.

**Expected behavior**
Expected behavior is exhibited in videos 2 and 3 where certain obstructions can cause sounds to behave how one might expect them to. Otherwise the sounds can carry at absurd distances and resonate as though you yourself are inside the cave. This is especially noticeable in the videos where the redstone contraptions are set out in the complete open and yet sound like they are in a cavern (this particular example does not work with mobs). If this is intended, how would you suggest mitigating this without compromising the quality of other aspects of the mod? 

**Log files**
https://gist.github.com/Peonovic/855445deb9c3042d022cdf81e9ac3d0e

**Versions**
- Videos taken in 1.19.2 but this can also be replicated in 1.18.2 (the open field example does NOT happen in 1.18.2) and 1.20.1
- 43.3.2 in videos but used most up to date version in 1.18.2 and 1.20.1 as well
- 1.2.1 but I tested it across multiple versions and results are consistent

**Other mods**
Mods are not required to replicate and are not used in videos, but modded objects and mobs are also affected (for example the open field example works with some Create elements).

**Videos**
1 - https://streamable.com/mhfgf7
2 - https://streamable.com/yg3jrt
3 - https://streamable.com/1bclmx
4 - https://streamable.com/7tv7t8
5 - https://streamable.com/3qtacn
6 - https://streamable.com/wrmhqd
7 - https://streamable.com/83i2bo

**Comment by henkelmax** [comment]
When making videos about weird sound behavior, please always enable the debug visualization. I can't help you without seeing what the sound rays are doing.

**Comment by Peonovic** [comment]
I'm sorry, guess I didn't think about it. If you like I can replicate all of them and repost here?

**Comment by henkelmax** [comment]
Sure. But please make sure you only show things you can't explain by the sound rays.

**Comment by Peonovic** [comment]
Hah. Apologies for my ignorance but just to verify what exactly you mean before I waste our time with more videos you can't make use of, do you simply mean the F3 screen, debug profiling, or something else I'm unaware of?

**Comment by henkelmax** [comment]
You'll find the settings in the debug tab of the the config GUI.

**Comment by Peonovic** [comment]
Hopefully these are more useful.

**New Log**
https://gist.github.com/Peonovic/b9d35e25f870458c245640023ba9e6a5

**Videos**
1 - https://streamable.com/mrrll4
2 - https://streamable.com/dtkyrw
3 - https://streamable.com/5slpnq
4 - https://streamable.com/c0969b

**Comment by henkelmax** [comment]
I can't really see any issues in your videos. You can make the sound evaluation more precise by increasing the ray count, but that will always impact performance.
You can also disable some functionalities in the config file if you are not happy with the directional evaluation.
