### ISSUE TITLE
Please add Actions to the repo

### ISSUE THREAD

**Issue by TAKfsg** [henkelmax/sound-physics-remastered#16]
**Is your feature request related to a problem? Please describe.**
My suggestion is not related to the mod.

**Describe the solution you'd like**
I would like there to be Actions on the repo.

**Describe alternatives you've considered**
In the past, I compiled the code myself but for people without much knowledge of how to compile the code themselves, they may want to just have the artifacts in the Actions tab.

**Comment by henkelmax** [comment]
That's what curseforge is for.
