### ISSUE TITLE
Suggestion - Muffle music underwater

### ISSUE THREAD

**Issue by AdamBrezik** [henkelmax/sound-physics-remastered#161]
This is a suggestion to create a configurable music muffling when underwater.

1. Value of how much the music should be muffled would be an equivalent of low-pass frequency
2. It would be best if it could be toggled whether the muffle starts when player is underwater or camera is underwater (this would probably be best even for sounds, you'd probably like me to start a new suggestion for that, which I won't)

**Comment by henkelmax** [comment]
Game music is completely ignored by the mod.
