### ISSUE TITLE
Sound attenuation

### ISSUE THREAD

**Issue by XSentinelu** [henkelmax/sound-physics-remastered#169]
**Description**
Distant reverbed sounds are too loud.

This example shows how zombie sounds can be heard over a long distance

https://github.com/henkelmax/sound-physics-remastered/assets/102240838/11152b43-e583-4ec5-b1b1-0a3396dac858

Maybe the mod should allow you to set the sound attenuation value to greater than 1

**Versions**
- Minecraft version 1.20.1
- Fabric loader
- Mod version 1.2.1

**Comment by henkelmax** [comment]
Please make sure you have the debug rays enabled when showing videos of sounds

**Comment by XSentinelu** [comment]
So basically everything should look the same as in video, where white lines is bounce rays and the rest are occlusion
![1](https://github.com/henkelmax/sound-physics-remastered/assets/102240838/4e796d8d-9a26-49e0-9d0f-e301918080ce)

**Comment by JacobC6799** [comment]
same problem

**Comment by mosharky** [comment]
I've been having a similar problem for a while as well

**Comment by CalaMariGold** [comment]
Is there a workaround for this in the mean time? In my instance all mobs can be heard from far away as if they're right next to me.

**Comment by Lemonwump** [comment]
I can hear clerics walking in their echoed churches from an abnormal distance in 1.20.4.

**Comment by SharperG7** [comment]
yeah, it's super noticable in villages with churches. I can hear the clerics opening doors from extremely far away.

**Comment by djmrFunnyMan** [comment]
Here I hear this villager from way too far (1.3.1 on 1.20.4 fabric)

https://github.com/henkelmax/sound-physics-remastered/assets/68905776/bad8d7a9-9ca2-4f56-87f5-5e32539db505

https://gist.github.com/djmrFunnyMan/7428c7e1feca1156d029e4798ba54011

**Comment by SirBurb** [comment]
Any fixes yet?
