### ISSUE TITLE
Noteblocks&Jukeboxes

### ISSUE THREAD

**Issue by Taucari** [henkelmax/sound-physics-remastered#17]
**Feature Request:**
Principally, sound physics for note blocks.
Jukeboxes are more of a nice to have but are probably much much harder to get implemented.
Was messing around in a big cave with note blocks and jukeboxes and realised that the note blocks weren't echoing.
Was on 1.18.1 so wasn't sure if this was already implemented in an earlier version, in that case, sorry!

**Comment by SleepyTonia** [comment]
For what it's worth, this has been solved in Sound-Physics-Fabric
https://github.com/vlad2305m/Sound-Physics-Fabric/commit/fd78f0520e168439916ad2457951d19312105873
