### ISSUE TITLE
sudden very loud noise in cave?

### ISSUE THREAD

**Issue by m3owsynth** [henkelmax/sound-physics-remastered#173]
https://github.com/henkelmax/sound-physics-remastered/assets/150852896/2839be5c-f92f-4232-bcc8-71f69e03d085

it keeps happening, idk what is making it but I am very sensitive to loud noises (hence my otherwise low noise settings), please tell me if i can fix it somehow?

**Comment by henkelmax** [comment]
Please fill out the bug template
