### ISSUE TITLE
It would be cool if i could hear my own echos

### ISSUE THREAD

**Issue by awesomedudeer** [henkelmax/sound-physics-remastered#174]
Plz add this it would be awesome with simple voice chat

**Comment by henkelmax** [comment]
This is already a thing.

**Comment by awesomedudeer** [comment]
How?

**Comment by awesomedudeer** [comment]
i can hear other players echos and they can hear mine but i cant

**Comment by henkelmax** [comment]
Just look in the settings.

**Comment by awesomedudeer** [comment]
what settings the voice chat settings
