### ISSUE TITLE
1.20.2/1.20.3 Update Blocker

### ISSUE THREAD

**Issue by henkelmax** [henkelmax/sound-physics-remastered#178]
In Minecraft 1.20.2 Mojang updated [LWJGL](https://github.com/LWJGL/lwjgl3) from [3.3.1](https://github.com/LWJGL/lwjgl3/releases/tag/3.3.1) to [3.3.2](https://github.com/LWJGL/lwjgl3/releases/tag/3.3.2).
This LWJGL update switched from [OpenAL Soft](https://github.com/kcat/openal-soft) from [1.21.1](https://github.com/kcat/openal-soft/blob/master/ChangeLog) to [1.23.0](https://github.com/kcat/openal-soft/blob/master/ChangeLog).

These changes seem to have introduced a bug in OpenAL Soft that causes the Sound Physics Mod to not have any reverb.

**This blocks the mod from getting updated to 1.20.2 or later!**

I would appreciate any help identifying the actual issue with OpenAL Soft/LWJGL.
If anyone has a workaround for that issue in the current Minecraft version, help is also really appreciated!

---

If you really want to use the mod on 1.20.2, you can use the [Prism Launcher](https://prismlauncher.org/) and change the LWJGL version back to 3.3.1.

![image](https://github.com/henkelmax/sound-physics-remastered/assets/13237524/443bff8b-0372-40dc-ae0d-4d8e5150b785)

*I'm not 100% sure this won't cause any other issues but it seemed to have worked fine for me.*

**Comment by s5bug** [comment]
It's a long shot, but would a local Maven repository for using custom Natives versions allow one to bisect the openal-soft change? Noticing that LWJGL 3.3.1 works properly, I wonder if you could shove newer versions of openal-soft into it, pretending to be an older version, and use that to bisect.

I wouldn't even know where to start with that, though.

<hr>

The only _meaningful_ difference I could spot when playing around is that, compared to `examples/almultireverb.c`, SPR doesn't set
- `AL_EAXREVERB_DECAY_LFRATIO`
- `AL_EAXREVERB_REFLECTIONS_DELAY`
- v`AL_EAXREVERB_REFLECTIONS_PAN`
- v`AL_EAXREVERB_LATE_REVERB_PAN`
- `AL_EAXREVERB_ECHO_TIME`
- `AL_EAXREVERB_ECHO_DEPTH`
- `AL_EAXREVERB_MODULATION_TIME`
- `AL_EAXREVERB_MODULATION_DEPTH`
- `AL_EAXREVERB_HFREFERENCE`
- `AL_EAXREVERB_LFREFERENCE`
- `AL_EAXREVERB_DECAY_HFLIMIT`

(I tried making the `effect`/`slot` initialization code more akin to the example code and still couldn't get a reverb in my game, the only thing I haven't tried is modifying these properties. I assume the `PAN`s can't be useful.)

Looking through OpenAL issues regarding reverb, it seems like a lot of `EAXREVERB` code was changed between 1.21.1 and 1.23.0, although I'm not familiar at all with OpenAL or sound development (I was hoping I'd stumble into something working by dumb luck). The maintainer(s?) of openal-soft seem very kind, I want to believe that if an issue was opened there more help could be gained.

**Comment by henkelmax** [comment]
> It's a long shot, but would a local Maven repository for using custom Natives versions allow one to bisect the openal-soft change? Noticing that LWJGL 3.3.1 works properly, I wonder if you could shove newer versions of openal-soft into it, pretending to be an older version, and use that to bisect.

Yeah I tried that, but the game crashed when mixing 3.3.1 natives with the 3.3.2 library. So you would need to pack the whole LWJGL libraries into the mod which would increase the jar size to 100s of megabytes.

> The maintainer(s?) of openal-soft seem very kind, I want to believe that if an issue was opened there more help could be gained.

Yeah the issue is, I am not versed enough with this part of OpenAL to describe the issue to them. But if you know how to describe the issue to them, I would appreciate if you would open a ticket.

But anyways, thanks for sharing your information!

**Comment by henkelmax** [comment]
Thank you for your help @s5bug! Without you the port wouldn't have been possible!

**Comment by TomSipsOnCurry** [comment]
How would I download the 1.20.2 version now?

**Comment by henkelmax** [comment]
> How would I download the 1.20.2 version now?

Same as before. Curseforge or Modrinth
