### ISSUE TITLE
Sound not playing from other side of a modded block's wall.

### ISSUE THREAD

**Issue by LevelNaomi** [henkelmax/sound-physics-remastered#179]
**Bug description**
I can't hear anything from the other side of the Andesite Bricks wall (Andesite Bricks is from Rechiseled).

**Steps to reproduce the issue**
1. Place down the wall of Andesite Bricks (from Rechiseled).
2. Play a sound from the other side of the wall.

**Expected behavior**
There should have been the explosion sound from behind that block, although no sound is heard (the block is Andesite Bricks from Rechiseled).

**Versions**
- 1.19.2
- Forge
- Mod version

**Other mods**
Moonlight Lib
Jade
Magnesium/Rubidium Extras
FramedBlocks
Fusion (Connected Textures)
Rubidium
Identity
WorldEdit
Pollen
Ultimate Car Mod
Supplementaries
GeckoLib
Mannequins
Gauges and Switches
Security Craft
AppleSkin
SuperMartijn642's Config Lib
Jade Addons (Forge)
Walkie-Talkie
MrCrayfish's Furniture Mod
Create
Framework
Simple Voice Chat
Architectury API (Fabric/Forge)
Cave Dweller Reimagined
Presence Footsteps [Forge]
MrCrayfish's Gun Mod
Rechiseled
Create Deco
Oculus
True Darkness
Create Stuff & Additions
SuperMartijn642's Core Lib
Configured
Magnesium/Rubidium Dynamic Lights
Farmer's Delight
Architect's Palette
Cloth Config API (Fabric/Forge)

https://github.com/henkelmax/sound-physics-remastered/assets/85326761/549de37d-596a-4983-a8fe-1da70b5e8fa4

**Comment by LevelNaomi** [comment]
Huh, the audio in the video is not working through Github, just download it, I guess.

**Comment by itsTyrion** [comment]
That's because the first audio track is silent:
![image](https://github.com/henkelmax/sound-physics-remastered/assets/17730120/a8a70710-b1c0-4d21-bdbe-0481f1c94579)

FFMPEG, I choose you (I dropped the silent audio tracks)

https://github.com/henkelmax/sound-physics-remastered/assets/17730120/6fba6ab1-844b-4795-a740-100df6ca1d4b

**Comment by henkelmax** [comment]
You can change the occlusion values for blocks in the config.
These videos also don't really help without debug rays enabled.

**Comment by henkelmax** [comment]
`.minecraft/config/sound_physics_remastered/occlusion.properties`

The comments in that file describe how to add specific blocks.

**Comment by LevelNaomi** [comment]
I figured it out, thanks for the help.
