### ISSUE TITLE
Implementation of Delay/Echo and Doppler effect

### ISSUE THREAD

**Issue by UmbraVivens** [henkelmax/sound-physics-remastered#18]
**Is your feature request related to a problem? Please describe.**
not really a problem beyond having reverb but no delay, because it's something you'd expect within the new caves and cliffs (literally) generation. doppler effect would just be an "attention to detail" feature of a more situational nature, so it not being there wouldn't make a big difference

**Describe the solution you'd like**
just as the mod currently makes reverb with material specific sound absorption levels, delay would be more or less noticeable depending on the material of the surroundings as well as how open the space is.
tbh Doppler sounds like it'd be more complex to achieve. it'd take into account the player's POV, and sound sources' position/momentum/velocity, then calculate and pitch up or down the sound accordingly. The most common occurrence of this would be while riding a minecart or horse, hearing a minecart pass by, flying with elytra, during a big fall (imagine a player's scream as they fall having the doppler effect, remember Mario Kart 64 characters screaming when they're hit and then they fall behind? especially in tunnels that even add delay?).

**Describe alternatives you've considered**
i realise i don't know how Doppler would work with Simple Voice Chat specifically because it involves changing pitch, i can't imagine how it would apply to audio that comes and goes through the internet in real time, but since the effects the mode currently has are compatible with it i think it's probably feasible, if not then it's ok either way. On the other hand, while i think Echo sounds easier to add, it might be inconvenient for some people in Simple Voice Chat so a toggle for it could be needed

**Additional context**
for help on a good analysis on the Doppler effect in a videogame and how it's calculated, i know of [this video](https://www.youtube.com/watch?v=lz5yiVBtPvs)

**Comment by henkelmax** [comment]
There is an OpenAL function to enable the doppler effect, but I deliberately disabled that, because it didn't sound good.

**Comment by UmbraVivens** [comment]
ok then good to know it was thought about, but what about the echo?

**Comment by henkelmax** [comment]
> ok then good to know it was thought about, but what about the echo?

Especially in voice chat, this will get annoying really quick. It would sound awesome at first, but if you use it for longer it's just annoying.

**Comment by UmbraVivens** [comment]
sorry if i sound stubborn in a closed issue, but i want to clarify that the suggestion wasn't exclusively for Simple Voice Chat compatibility

**Comment by henkelmax** [comment]
The same things that I said about voicechat also apply for normal sounds.
Most minecraft sound sources don't even move, so doppler effect wouldn't make sense.

**Comment by henkelmax** [comment]
As I already said before. Most of Minecrafts sounds don't move so its impossible.

**Comment by IR2110** [comment]
Thank you for your quick reply and for explaining your position.
I understand that maintaining a mod is a difficult task, and I respect your decision to prioritize its stability.
I will accept it gracefully. Keep up the great work!

**Comment by henkelmax** [comment]
It doesnt mean its difficult. It simply doesnt work
