### ISSUE TITLE
Sound disappearing

### ISSUE THREAD

**Issue by Ezekiely8** [henkelmax/sound-physics-remastered#181]
**Audio Stops Working After interacting with certain objects**
The audio stops working after interacting with doors, using flint and steel, trapdoors, eating food, spawning mobs, and more
the sound is fine if you don't interact with certain objects it takes a while for the sound to cut off entirely after interacting with objects.
The footsteps stop working first then eventually everything cuts out

**Steps to reproduce the issue**
1. Load world
2. Spam click a door or chest or spawn mobs
3. Walk around for a bit
4. Sound gradually cuts off no footsteps, no mob noises, no object noise only noise you can here is the underwater audio 

Audio works fine if you disable Sound physics in the config

**Versions**
- Minecraft version:1.20.1
- Fabric Api
- 0.91.0
- 1.1.2

**Comment by henkelmax** [comment]
You are not using the latest version of the mod. Please update and check if this still happens. Also please always provide log files.
