### ISSUE TITLE
no 1.12(.2) version!

### ISSUE THREAD

**Issue by Xyeenie** [henkelmax/sound-physics-remastered#182]
issue # 1 NO OLD VERSIONS ARE SUPPORTED!
i didn't see anywhere else to post this. but a version for us on 1.12.2 at the least would be amazing. 
thank you for this amazing mod and i hope to see an old version in the near future!
also if you have a better line of following you or a place to comment properly please reply with it before closing tysm ❤️‍🔥 .

**Comment by henkelmax** [comment]
Won't happen. If you want to play older versions, go to the original mod.

**Comment by Xyeenie** [comment]
booooo
