### ISSUE TITLE
Underwater sound still absent after update

### ISSUE THREAD

**Issue by Foozey** [henkelmax/sound-physics-remastered#183]
**Bug description**
I noticed your update 1.3.0 supposedly fixed the underwater sounds issue. However, the issue still exists in this version when paired with other mods (list below). I haven't identified any specific mods that may be the clash, but I'm going to post this in-case you're aware of anything already that's on the list.

**Steps to reproduce the issue**
1. Install Sound Physics Remastered forge-1.20.1-1.3.0
2. Test with other mod pairings (list below)
2. Go underwater and try to mine something
3. Observe no sound

**Expected behavior**
To go underwater and be able to hear things.

**Versions**
- 1.20.1
- Forge
- 47.2.17
- 1.3.0

**Other mods**
- Cloth Config v10 API
- Elytra Slot
- Clumps
- Sophisticated Core
- Open Parties and Claims
- Item Borders
- Apothic Attributes
- Gravestone Mod
- Architectury
- Tectonic
- Cycle Paintings
- Nether's Delight
- Controlling
- Better Advancements
- Resource Pack Overrides
- Lava Monster
- Xaero's Minimap
- ClearDespawn
- Cupboard utilities
- Farmer's Delight
- Ping Wheel
- Nullscape
- The Aether
- Dyed
- Resourcefulconfig
- Traveler's Titles
- Falling Leaves
- CoroUtil
- Better Animations Collection
- Placebo
- Moonlight Library
- Clean Swing Through Grass
- Legendary Tooltips
- Paxi
- YUNG's Better End Island
- Sound Physics Remastered
- Artifacts
- Nimble
- Yeetus Experimentus
- AmbientSounds
- Better Third Person
- Iceberg
- YUNG's Better Ocean Monuments
- Ars Creo
- ReBlured
- YUNG's Better Desert Temples
- Step
- Pick Up Notifier
- Radium
- Lootr
- ToolStats
- Mouse Tweaks
- YUNG's Menu Tweaks
- Geophilic
- Wither Skeleton Tweaks
- NetherPortalFix
- FriendlyFire
- Collective
- Patchouli
- Searchables
- The Gems Project
- Every Compat
- YUNG's Better Witch Huts
- MmmMmmMmmmmm
- Simple Voice Chat
- Enhanced Celestials
- CorgiLib
- Create
- Spice of Life: Carrot Edition
- Default Options
- Vein Mining
- LootBeams
- OkZoomer
- Snow Under Trees
- Creeper Overhaul
- Regions Unexplored
- YUNG's Extras
- Scuba Gear
- Amplified Nether
- Gateways To Eternity
- SuperMartijn642's Config Library
- Better Mods Button
- AppleSkin
- Guard Villagers
- Leap
- Comforts
- Better Spawner Control
- Simply Light
- Forge Config Screens
- YUNG's Better Nether Fortresses
- Waystones
- Nature's Compass
- Death Finder
- YUNG's Better Mineshafts
- YUNG's Better Strongholds
- AttributeFix
- Cake Chomps
- Sophisticated Backpacks
- Polymorph
- Merchant Markers
- No Trample
- Alex's Caves
- Completionist's Index
- Cherished Worlds
- Framework
- Highlighter
- Better Compatibility Checker
- Structure Gel API
- Bad Wither No Cookie Reloaded
- Serene Seasons
- Jump Over Fences
- DarkPaintings
- When Dungeons Arise
- Just Enough Items
- Entity Texture Features
- EnchantmentDescriptions
- CreativeCore
- Overflowing Bars
- Stack Refill
- Right Click Harvest
- Toast Control
- YUNG's API
- Carry On
- Oculus
- Diagonal Fences
- BetterF3
- Raised
- Waddles
- TexTrue's Embeddium Options
- DeathKnell
- Rare Ice
- William Wythers Overhauled Overworld [FORGE]
- Charm of Undying
- Sky Villages
- Bookshelf
- Diagonal Windows
- Goblin Traders
- Bottle Your Xp
- Sophisticated Storage
- Another Furniture
- Scaffolding Drops Nearby
- Name Pain
- Jade
- Embeddium
- Enderman Overhaul
- Model Gap Fix
- Decorative Blocks
- Visual Workbench
- Citadel
- clickadv mod
- Double Doors
- Xaero's World Map
- Tiny Item Animations
- YUNG's Better Jungle Temples
- Leaves Be Gone
- Aether: Lost Content
- Apotheosis
- Ars Nouveau
- Equipment Compare
- Void Totem
- Damage Indicator
- YUNG's Bridges
- Not Enough Recipe Book
- Explorer's Compass
- Dash
- SuperMartijn642's Core Lib
- TerraBlender
- Pop!
- Curios API
- EntityCulling
- SeasonHUD
- Tiny Skeletons
- 3dSkinLayers
- Dragon Mounts: Legacy
- FastFurnace
- Advancement Plaques
- Kiwi Library
- Mutant Monsters
- Balm
- Additional Lanterns
- Brazier
- Fast Suite
- Blossom
- Easy Elytra Takeoff
- Puzzles Lib
- Chat Heads
- YUNG's Better Dungeons
- MaxHealthFix
- Resourceful Lib
- Nyf's Spiders
- Fast Workbench
- Catalogue
- Ding
- Alex's Mobs
- Caelus API
- TrashSlot
- Stylish Effects
- Entity Model Features
- Prism
- GeckoLib 4
- NotEnoughAnimations Mod

**Comment by henkelmax** [comment]
You need to reset your config in order for it to work.
