### ISSUE TITLE
Block reflectivity/occlusion factor cleanup

### ISSUE THREAD

**Issue by DDunda** [henkelmax/sound-physics-remastered#184]
**Description**
These block factor menus in the settings have some issues as they are missing important sound-transparent block types, have many duplicate types, and no order at all.

Sound transparent blocks include fences, fence gates, iron bars, leaves (other than cherry and azalea, for some reason?), and spawners. These may be used decoratively in creative or survival but currently block all sound, e.g. cages, animal pens, fence walls.

Some duplicate options include several (but not all) wood types, only two leaf types, four hanging sign types, only two saplings, all variations of cut deepslate (unlike all other stone types), and some random other selections (i.e. gilded blackstone but not blackstone, suspicious gravel and sand but not gravel and sand).

It would be useful if players could add their own types from here and start with a menu that is not confusing.

**Versions**
- 1.20.1
- Forge 47.2.17
- 1.20.1-1.3.0

**Other mods**
Menus accessed with Catalogue (1.20.1-1.8.0) by MrCrayfish and Cloth Config API (11.1.106) by shedaniel.

**Comment by henkelmax** [comment]
Cloth configs menus are very limited. If you want more control over the blocks you want to add to the config, you need to edit the config file. The config file allows you to specify sound types, tags and specific blocks.
