### ISSUE TITLE
How do I reduce the effects for a mod's audio *without* completely cancelling it with the blacklist? not a bug, but no where else to ask.

### ISSUE THREAD

**Issue by JadianRadiator** [henkelmax/sound-physics-remastered#188]
Not a bug, but no where else to ask.
~~How do I add a second or multiple sounds to the audio blacklist?~~
How do I reduce the effects for a mod's audio *without* completely cancelling it with the blacklist?

**Comment by henkelmax** [comment]
Depends on what you want to do:
If you want to reduce reverb - Reduce the reflectivity values
If you want to reduce occlusion - Reduce the occlusion values

**Comment by JadianRadiator** [comment]
unfortunately your suggestion only applies to the block behavior  in reaction to sounds.
An what I am asking is to reduce sounds from only one mod without outright blacklisting .
