### ISSUE TITLE
sound bug

### ISSUE THREAD

**Issue by XRAZERGAMERX** [henkelmax/sound-physics-remastered#192]
### Bug description

if i open doors or click a button the sound bugs out

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

nothink

### Expected behavior

no more of these bugs

### Log files

https://www.mediafire.com/file/r3t3j2zf8yidyvg/latest.log/file (not sure if this is right)

### Screenshots

https://www.dropbox.com/scl/fi/qxns7lw77fjodz1u0nquq/Jdk-17-2024.02.22-16.57.14.01.mp4?rlkey=c5yxx98je9mksmf3mz1y59qkm&dl=0 (a video not a screenshot)

**Comment by henkelmax** [comment]
Please properly fill out the template. Also please include debug rays in your video.

**Comment by XRAZERGAMERX** [comment]
in the log files section im not sure if its right
