### ISSUE TITLE
Sounds get muffled when they should not get muffled.

### ISSUE THREAD

**Issue by LukeOnuke** [henkelmax/sound-physics-remastered#193]
### Bug description

As the title suggests the mod seems to muffle sounds when they go through any block, even if its something like a fence, or a chest.

Funnly enough I think this whole issue could be fixed by adding fences, trapdoors, doors and chests to `oclusion.properties`.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

0.15.7

### Steps to reproduce

1. Stand in such a way to obstruct the sound raycast between the player and the sound source. _(see figure 1.1 and 1.2)_
2. Listen to the muffled sounds

figure 1.1
![figure 1.1 - ](https://github.com/henkelmax/sound-physics-remastered/assets/57074484/656077e3-28ad-468d-aee8-4a544e191726)
figure 1.2
![figure 1.2](https://github.com/henkelmax/sound-physics-remastered/assets/57074484/4ef0d4eb-2777-48ae-8609-a4c4f51a60e6)

### Expected behavior

Expected behavior is that such sounds don't get muffled, its quite jarring.

### Log files

https://gist.github.com/LukeOnuke/52aa670d2da4cce3406149c1c3fe8b50

### Videos

i have no idea on how to enable debug rays for your mod, well oops. Anyways doubt a video would show much.

**Comment by atlev** [comment]
I know how this could be fixed.  If the block can trace a line to the player, ignore occlusion completely.  I work in a lot of small spaces and this mod is unusable for me.  Especially if the player is standing in a doorway.

**Comment by ChronicNameChanger** [comment]
I have noticed this as well. I have many chests next to each other, and it seems like the top most row plays sounds at full volume, but any chests below or ones you're not on the same axis as, are obscured.

https://github.com/henkelmax/sound-physics-remastered/assets/170038226/b35f29d5-6e2c-465b-a35f-dac721c08e20

As seen in this video.

**Comment by henkelmax** [comment]
This should also be fixed with 3b0dbd07518bb557d0f6a92a0cf82e43ae9a8b42

Feel free to reopen if the issue persists.
