### ISSUE TITLE
Addition of Reverb of Own Voice in Simple Voice Chat

### ISSUE THREAD

**Issue by slapelachie** [henkelmax/sound-physics-remastered#20]
**Is your feature request related to a problem? Please describe.**
Not a current problem, just a feature request.

**Describe the solution you'd like**
Requesting the ability to enable reverb for your own voice while using Simple Voice Chat, similar to the way [sound-physics-fabric](https://github.com/vlad2305m/Sound-Physics-Fabric) and [plasmo-voice](https://github.com/plasmoapp/plasmo-voice) have it implemented. See https://youtu.be/F7qdN3EIl4w for a clearer description of what I am asking.

This may have been mentioned in #18 with you rejecting it, however having the ability to toggle this option would be a good way to stop any annoyance. This feature adds quite a bit of depth to the world when entering caves and is fun to play around with in servers.

As you have forked the sound-physics-fabric this feature may already be implemented, if this is the case it is not working as intended.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by henkelmax** [comment]
I don't see a real use for this feature, as already discussed in #18

**Comment by henkelmax** [comment]
This is now added with 138d40941f3918409a33e10d6f5463a59e48088b
Although I see no reason why anyone would use it :D
