### ISSUE TITLE
Incompatible with latest create verision

### ISSUE THREAD

**Issue by Killercrab432** [henkelmax/sound-physics-remastered#200]
### Bug description

game does not run with the latest version of create

### Minecraft version

1.20.1

### Mod version

1.3.1

### Mod loader and version

fabric 0.15.7

### Steps to reproduce

download sound physics remastered 1.3.1
download create 0.5.1-f 
game will not start

### Expected behavior

for the game to work

### Log files

https://pastebin.com/em3jXB0x

### Videos

![image](https://github.com/henkelmax/sound-physics-remastered/assets/105161116/34ca066b-ebd7-40a7-90c9-f3f003680b98)

**Comment by henkelmax** [comment]
#172
