### ISSUE TITLE
Incorrect Audio Positioning when drinking/eating

### ISSUE THREAD

**Issue by peow** [henkelmax/sound-physics-remastered#202]
### Bug description

I made a video to exemplify the problem:
https://www.youtube.com/watch?v=dFv8tvq3vAo

basically the Sound Physics mod is making the audio that plays "inside" the Player buggy, where depending on how you move your camera or which way you walk, the sound cuts out or stays only on one side of the phone

--------------------------

In the video I start by showing what the sound effects are like **without** Sound Physics (from 0:00 seconds onwards)

Then I'll show what it looks like with Sound Physics **enabled** (from 0:31 seconds onwards)

I even tried to configure the mod, **disabling** Sound Physics' drinking and eating sound effects, through the file (apartir dos 1:40 segundos)
> */config/sound_physics_remastered/allowed_sounds.properties 
minecraft\:entity.generic.drink=false
minecraft\:entity.generic.eat=false*

-- but there was no change

-------------------

In the video I show that the Horn sound works correctly;
I don't know which other sounds also have this problem, so I couldn't test them.

If it is possible to fix this, I ask you to publish an update for **Fabric 1.20.1**, thank you

### Minecraft version

1.20.1

### Mod version

1.3.1

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

enable Sound Physics effects
use headphones so you can hear the stereo audio
try to eat or drink something in-game while walking sideways, or while walking and moving your camera

### Expected behavior

the sound effects that happen "inside" the Player do not play just on one side of the phone, and act like the Horn sound effect

### Log files

https://gist.github.com/peow/f953e2682baef4a10ae80498e43f4e90 I didn't make this log while recording the video, I made it just now just showing the 3 sounds (eating, drinking and playing the horn)

### Videos

https://www.youtube.com/watch?v=dFv8tvq3vAo

**Comment by Rhett008** [comment]
Also have this issue

**Comment by atlev** [comment]
Yep yep same here.

**Comment by szunakabeats** [comment]
has been a bug for a long time

**Comment by RyuSanPy** [comment]
same
