### ISSUE TITLE
Striders make no footstep sounds

### ISSUE THREAD

**Issue by djmrFunnyMan** [henkelmax/sound-physics-remastered#203]
### Bug description

Enough said. Striders make no foostep sounds when they walk on lava. (Lava has weird interactions with sound physics in general but that's another issue)

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

Ride a strider lol

### Log files

No

### Videos

![2024-04-11_19 15 34](https://github.com/henkelmax/sound-physics-remastered/assets/68905776/cd169400-40ec-4763-90fa-0a9820f639e2)

**Comment by henkelmax** [comment]
Please fill out the whole bug template properly.

**Comment by djmrFunnyMan** [comment]
Sorry I discovered this at 3am and had to make a quick report since I had no time. Now I'm not home for a few days so I have no access to a computer
