### ISSUE TITLE
Strider footstep sounds are not audiable with sound physics.

### ISSUE THREAD

**Issue by djmrFunnyMan** [henkelmax/sound-physics-remastered#204]
### Bug description

Strider footstep sounds are not audiable/very muffled compared to vanilla. 

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

Find a lava lake and ride a strider

### Expected behavior

Striders footstep sounds would be audiable

### Log files

https://gist.github.com/djmrFunnyMan/b6dd642fce82b77a3a6c569afbdd4f26

### Videos

(I had presence footsteps disabled alongside it's sound pack)

https://github.com/henkelmax/sound-physics-remastered/assets/68905776/ac80ce8c-9d29-4f19-aaa7-71d913f22937

**Comment by henkelmax** [comment]
Fixed with 3b0dbd07518bb557d0f6a92a0cf82e43ae9a8b42
