### ISSUE TITLE
Sound in the music category played at player position is affected.

### ISSUE THREAD

**Issue by Josh65-2201** [henkelmax/sound-physics-remastered#207]
### Bug description

Global music like Minecraft's default won't be affected but playing a sound from a resource pack at the player location (@s) even under the music category will be casing inconsistent playback

### Minecraft version

1.20.1

### Mod version

1.3.1

### Mod loader and version

Fabric

### Steps to reproduce

1. Get a resource pack with custom music (example pack https://modrinth.com/resourcepack/true-ending-ender-dragon-music/version/1.0)
2. Run the command `/playsound true_ending:music.dragon music @s`
3. Go behind a wall
4. Hear it muffled

### Expected behavior

Should not be affected like Minecraft's default music

### Log files

*

### Videos

![image](https://github.com/henkelmax/sound-physics-remastered/assets/26977075/6ca35b41-4bde-4857-bde7-c0930b132fba)
![image](https://github.com/henkelmax/sound-physics-remastered/assets/26977075/d4a9fb1b-4d46-4cb7-84f8-c06cd1be9f82)

**Comment by henkelmax** [comment]
You need to enable `update_moving_sounds` in the config.

**Comment by Josh65-2201** [comment]
I already have that enabled. but the sound also doesn't move anyway, It plays at the players position one time.

**Comment by henkelmax** [comment]
Isn't that also the case for vanilla then?

**Comment by Josh65-2201** [comment]
It does if I use that command to play the vanilla music, but not if Minecraft plays the music itself. If it intentional is there a way I can exclude anything under the music category, If not should I open a feature request for it?

**Comment by henkelmax** [comment]
That's completely intended by the mod. You should exclude the sound from being processed in the mods config.

**Comment by Josh65-2201** [comment]
So I tried closing Minecraft editing the file `allowed_sounds.properties` following the same naming as others in the file `true_ending\:music.dragon=false` but when opening Minecraft it gets removed from the file.

**Comment by Sorro123** [comment]
> it gets removed from the file.
I'm having a similar problem with the enhanced visuals explosion ringing sound
