### ISSUE TITLE
Loud noises are obstructed way too easily

### ISSUE THREAD

**Issue by djmrFunnyMan** [henkelmax/sound-physics-remastered#210]
### Bug description

This issue is a continuation of #197 .
Basically very loud noises get muffled by obstacles when it doesn't make sense for them to be. For example, explosions, thunder, raid horn, dragon roar, sonic boom (warden)

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

1. Summon a lightning bolt behind a wall.
2. Shoot an ender crystal with a bow without a direct line of sight

In all cases you will hear no noise.

### Expected behavior

The raid horn should be completely excluded from having sound physics.

As for the other sounds (thunder, explosions etc.) they should send out many extra rays in every direction that'll travel some distance, and then snap towards the player regardless of if they had something to reflect off off (they'll just change direction midair). Depending on how many of those rays get to the player that'll determine how much it's muffled.

### Log files

https://gist.github.com/djmrFunnyMan/ecb22dd22178fa103976ebdcc0b84bbf

### Videos

https://github.com/henkelmax/sound-physics-remastered/assets/68905776/6f7fb673-9249-40f7-a7d5-5018b0c3a888

https://github.com/henkelmax/sound-physics-remastered/assets/68905776/4678a26d-af84-4611-9f12-24e85c5e5e43

**Comment by djmrFunnyMan** [comment]
I closed #197 and created this because this is a larger issue how there's no proper handling of very loud noises. You excluded thunder and goat horn but explosions, thunder, ender dragon roar, sonic boom (warden) and whatever else is still affected. 

Loud noises go around obstacles very easily irl so these sounds getting blocked by a single unfortunately placed block is quite wrong.

**Comment by djmrFunnyMan** [comment]
So I ask for this to be reopened since https://github.com/henkelmax/sound-physics-remastered/commit/61785de4849b765f44a7f72209dc2c54d1d00e2b doesn't even cover all the sound events mentioned in this issue.

**Comment by henkelmax** [comment]
There is no concept of "loud" noises in the game. If you don't like how these sounds are handled, you can always exclude them using the config.
