### ISSUE TITLE
Latest Version also has Problems with latest Create Version

### ISSUE THREAD

**Issue by Cape-City** [henkelmax/sound-physics-remastered#212]
### Bug description

I get the following error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Sound Physics Remastered' (sound_physics_remastered) 1.20.1-1.4.0 (C:\Games\curseforge\minecraft\Instances\Create World\mods\sound-physics-remastered-fabric-1.20.1-1.4.0.jar).
More details:
	 - Mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 is incompatible with any version of mod 'Sound Physics Remastered' (sound_physics_remastered), but a matching version is present: 1.20.1-1.4.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.0

### Mod loader and version

0.15.11

### Steps to reproduce

Just have both mods installed simultaneously

### Log files

https://gist.github.com/Cape-City/d8709b4a014180b65a96335377d9abff

### Videos

Games crashes before starting anything ;)

**Comment by henkelmax** [comment]
https://github.com/Fabricators-of-Create/Create/commit/b12d4d839d3b5a3bb707e4a5a75c9055f8b5f274
