### ISSUE TITLE
Water Sounds Continually Overlap and Cause  Lag

### ISSUE THREAD

**Issue by AmazeingGames** [henkelmax/sound-physics-remastered#214]
### Bug description

Whenever there are multiple sources of water sounds playing at the same time the sounds will echo around and continue to build up until it starts to lag the game.

### Minecraft version

1.20.1

### Mod version

soundphysics-forge-1.20.1-1.1.2

### Mod loader and version

Forge 47.2.6

### Steps to reproduce

1. Create an 8x8 square fountain with a single water source 2 blocks up at the center of the fountain, with the outer wall being at least two blocks high so mobs can't jump out
2. Spawn many silverfish in the fountain
3. Watch as it starts to lag the game and produce large amounts of sound

### Expected behavior

When performing the test the sounds should play normally and not cause lag

### Log files

https://gist.github.com/AmazeingGames/adf5fed0168a03bf9b6f3d5a16ba99f7

### Videos

https://imgur.com/a/hnWmJWR

**Comment by henkelmax** [comment]
You are using a very outdated version of the mod. Please update and open another issue if it persists.
