### ISSUE TITLE
Game freezes with Valkrien Skies

### ISSUE THREAD

**Issue by nthxny** [henkelmax/sound-physics-remastered#217]
### Bug description

It seems that when Valk Skies ships unload when you run away or teleport out of range, it completely breaks the sound engine, lag spikes over 20 seconds.

Nothing in the logs, but I managed to get a Spark trace, and figured out that removing Sound Physics solved the problem (tested with four people, two of us removed the mod, and the other two crashed again)

### Minecraft version

1.20.1

### Mod version

v1.20.1-1.4.2

### Mod loader and version

Forge 47.2.23

### Steps to reproduce

Build a Valk Skies ship, fly/teleport out of range of it

### Log files

https://spark.lucko.me/leU9kUbUqF

### Videos

n/a

**Comment by henkelmax** [comment]
Please provide logs and ideally a video that shows the issue and how to reproduce it.

**Comment by henkelmax** [comment]
Closed due to inactivity.
