### ISSUE TITLE
Option for Fabric

### ISSUE THREAD

**Issue by JJoestarz** [henkelmax/sound-physics-remastered#218]
### Bug description

Hi, idk if it's a bug but the fabric version of the mod don't have any option to configure the mod .
I want to create a realistic RolePlay modpack and in the forge version you have a version " hear your self " ( Useful when you use a voice chat) and I can't have access to this option on fabric .
![Minecraft_ 1 20 1 06_06_2024 19_11_32](https://github.com/henkelmax/sound-physics-remastered/assets/171965823/31dc6e15-4c6e-48de-832c-0be2a604fc9c)

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.2

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Go to the mod list ( with the mod "mod menu" )
2. Find the mod in the list and you can see there is no option for configure him .
![Minecraft_ 1 20 1 06_06_2024 19_11_32](https://github.com/henkelmax/sound-physics-remastered/assets/171965823/ac0c5404-52c1-4dc3-8d5a-74d87a7a4193)

### Expected behavior

 I think fabric is different to forge but yet they use the same configuration mod " Cloth config API " but it doesn’t work , it might be the mod " mod menu " which interferes with the mod cloth config API and the mod sound physics .

### Log files

https://gist.github.com/

### Videos

I dont have a vidéo but i explain how to see the problem

**Comment by henkelmax** [comment]
Your logs are empty.

**Comment by henkelmax** [comment]
Just tested it and it works fine with the latest versions of all mods.

![image](https://github.com/henkelmax/sound-physics-remastered/assets/13237524/dc9f2603-77bc-4aa5-ad0b-b6e59696d35b)

**Comment by JJoestarz** [comment]
My bad, my "fabric config" didn’t have the latest version sorry for posting an innutile report and thank you for taking your time anyway!
