### ISSUE TITLE
Sound Physics Remastered Causes Audio Crackles

### ISSUE THREAD

**Issue by whytho42** [henkelmax/sound-physics-remastered#219]
### Bug description

Hello,

I really like this mod and how it improves on the sound of default Minecraft but recently I've been unable to play without the mod making the audio crackle and lag under load. An example is when I am running a sorting machine with many minecart hoppers running on tracks in water. I've also experienced it running in a lot of grass in a plains biome as well. I had this issue in my 1.20.4 world as well where it would make my audio crackle under high load. Would love to have this fixed!

thanks

### Minecraft version

1.21

### Mod version

1.21

### Mod loader and version

1.21

### Steps to reproduce

Running a multi-item sorter with many minecarts and other large redstone contraptions. I used [this](https://www.youtube.com/watch?v=tRj52w8dptc&t=2s&ab_channel=LummieThief) item sorter and [this](https://www.youtube.com/watch?v=9eHcvMi7HUw&ab_channel=RaPsCaLLioN1138) item sorter as well and experienced the issue both times. Also, seem to get it under high audio stress like running through a lot of grass. I also have physics, presence footsteps, and ambient sound mod installed as well.

### Expected behavior

no crackling sound under high load

### Log files

https://gist.github.com/whytho42/f6d77aee9aa6675dde12f686f9dfcb74

### Videos

https://github.com/henkelmax/sound-physics-remastered/assets/87866837/3dd7e885-8f1f-4ee6-bd91-4d8337fad2a3

**Comment by henkelmax** [comment]
Is there any way to reproduce this issue?
What are the specs of your PC?

**Comment by whytho42** [comment]
I just experience it when I encounter high loads of things making noises at once. My specs are I9-12900HX cpu, 32gb ram ddr5, 4080 GeForce laptop graphics

**Comment by henkelmax** [comment]
The specs are perfectly fine. This might be an audio driver issue, as noone had this issue before.

**Comment by whytho42** [comment]
I think it might be something with all the mods I have installed interacting with each other. My audio drivers are fine but whenever I install sound physics it makes the audio crackle worse.

**Comment by henkelmax** [comment]
If it happens with vanilla Minecraft too, its definitely not a mod issue.
