### ISSUE TITLE
Noises Playing way too far away

### ISSUE THREAD

**Issue by EyemSoReel** [henkelmax/sound-physics-remastered#223]
### Bug description

Jukeboxes playing across the map in our server

### Minecraft version

1.21

### Mod version

1.12-1.4.3

### Mod loader and version

Fabric 1.21

### Steps to reproduce

Playing on a multiplayer server using jukeboxes

### Expected behavior

sounds should only play within their respected areas

### Log files

There is none

### Videos

https://youtu.be/OcJ-RtaHKwk

**Comment by henkelmax** [comment]
Hey, 
I am not able to reproduce your issue. Can you provide a minimal reproducible example?
Did you enable moving sounds in the config?
Did you try to enable debug rendering?

**Comment by EyemSoReel** [comment]
Im sorry, I do have moving sounds enabled, if I disable it, the issue is even worse and I hear the song even more just sounds like its behind a wall. 

I dont know how to use debug rendering but if you walk me through it I can do what you need

**Comment by henkelmax** [comment]
> Im sorry, I do have moving sounds enabled, if I disable it, the issue is even worse and I hear the song even more just sounds like its behind a wall.

Hmm that seems to be a bug. Music discs should sound like in vanilla if this setting is disabled.

> One thing I found is when I turn off sound physics, the disc plays fully at far distances, its almost as if with the mod disabled, it gives up on keeping the sounds withing the reflection room and plays them elsewhere they would normally play.

Turning off sound physics should exactly do that. It should sound like you don't have the mod installed.

> Like it doesn't matter what settings I change in the mod, I can always here the disc playing outside of the building once i get far away enough.

That doesn't happen for me. Its either something you messed up in the config or a conflict with another mod. Try resetting all sound physics configs.

> I dont know how to use debug rendering but if you walk me through it I can do what you need

You can find the option is the settings screen in the debug tab or in the main config file: `render_sound_bounces`

**Comment by henkelmax** [comment]
I just tested it with moving sounds disabled and it sounds exactly like in vanilla. That has to be an incompatibility with another mod. Please check if you are able to reproduce any of that without other mods installed.

**Comment by EyemSoReel** [comment]
Okay sorry if I wasted your time, I guess it's something else causing the
issue, Im realizing the sounds with the mod disabled are playing super far
away, I don't know what would cause this, I didn't download any other sound
mods besides simple voice chat and sound physics... I guess I'll have to
have an AI go through it or something, thank you for your efforts and
patience.

amazing mod, thank you for creating it

**Comment by EyemSoReel** [comment]
I figured out the issue and I'm sorry it not being an issue with the mod,
It was because the custom music files we used for the servers resource pack
are in stereo, not mono.

Thank You again for everything, your mod is wonderful and I love it works
with the voice chat, me and my brother were losing each other in the
nether fortress and out of no where you'd hear echoes of "help meee" lol
