### ISSUE TITLE
Game taking too long at "Loading Terrain..." screen

### ISSUE THREAD

**Issue by yilnea** [henkelmax/sound-physics-remastered#225]
### Bug description

Game gets stuck at the "Loading Terrain..." screen when switching between worlds or joining a server, if it takes too long the game eventually crashes. The issue goes away when I disable the Sound Physics mod and loading becomes instant again. I play on a server with 8 different worlds that I often switch between so this can get pretty annoying.

### Minecraft version

1.21

### Mod version

1.4.3

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

Change worlds with the mod active.

### Log files

https://gist.github.com/yilnea/7b2c44902f2838fee622342239dc126e

### Videos

Now I'm unable to even join the server. the game gets stuck at the first "Loading terrain..." screen and crashes later so it's hard getting a clip right now.

**Comment by henkelmax** [comment]
Does this also happen on a fresh world with just the mod installed?

**Comment by yilnea** [comment]
Doesn't happen on a fresh singleplayer world without any other mods, but it still happens on the server.

**Comment by henkelmax** [comment]
Then please check if its caused by the world or the mods.

**Comment by henkelmax** [comment]
Closed due to inactivity

**Comment by enaye** [comment]
it would take me like 5 minutes to load into server (stuck on loading terrain)

loading terrain issue went away when i took off sound physics remastered

this was my mod list before taking off sound physics remastered:

	- aether 1.20.1-1.4.2-neoforge
		|-- cumulus_menus 1.20.1-1.0.0-neoforge
		|-- mixinextras 0.2.0-beta.9
		\-- nitrogen_internals 1.20.1-1.0.7-neoforge
	- aethersdelight 0.1.1-1.20.1
	- alexscaves 1.1.5
	- alexsmobs 1.22.9
	- ambientsounds 6.0.6
	- amendments 1.20-1.2.11
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.2
	- aquaculturedelight 1.0.0
	- architectury 9.2.14
	- armorstatues 8.0.6
	- astemirlib 1.11
	- balm 7.3.9
		\-- kuma_api 20.1.8
	- bclib 3.0.14
	- beautify 2.0.2
	- beo 4.1.0
	- better_climbing 3
	- betteradvancements 0.4.2.10
	- bettercombat 1.8.6+1.20.1
	- betterend 4.0.11
	- betterf3 7.0.2
	- bettermodsbutton 8.0.2
	- betternether 9.0.10
	- biomesoplenty 18.0.0.598
	- blue_endless_jankson 1.2.2
	- blue_skies 1.3.31
	- bno 9.1.1
	- born_in_chaos_v1 1.0.0
	- bosses_of_mass_destruction 1.1.2
	- bygonenether 1.3.2
	- caelus 3.2.0+1.20.1
	- castle_in_the_sky 1.20.1
	- cataclysm 1.99.5
	- cataclysmiccombat 1.3.4
	- cavedust 2.0.4
	- cerbons_api 1.1.0
	- charmofundying 6.5.0+1.20.1
		\-- spectrelib 0.13.15+1.20.1
	- chunkloaders 1.2.8a
	- citadel 2.6.0
	- cloth_config 11.1.118
	- combatroll 1.3.3+1.20.1
	- computercraft 1.113.0
	- conjurer_illager 1.1.6
	- connectivity 1.20.1-5.6
	- connectorextras 1.11.2+1.20.1
		|-- amecsapi 1.5.3+mc1.20-pre1
		|-- connectorextras_architectury_bridge 1.11.2+1.20.1
		|-- connectorextras_emi_bridge 1.11.2+1.20.1
		|-- connectorextras_energy_bridge 1.11.2+1.20.1
		|-- connectorextras_geckolib_fabric_compat 1.11.2+1.20.1
		|-- connectorextras_jei_bridge 1.11.2+1.20.1
		|-- connectorextras_kubejs_bridge 1.11.2+1.20.1
		|-- connectorextras_modmenu_bridge 1.11.2+1.20.1
			\-- modmenu 7.2.2
		|-- connectorextras_pehkui_bridge 1.11.2+1.20.1
		|-- connectorextras_rei_bridge 1.11.2+1.20.1
		|-- connectorextras_terrablender_bridge 1.11.2+1.20.1
		|-- forgeconfigapiport 8.0.0
		\-- reach_entity_attributes 2.4.0
	- connectormod 1.0.0-beta.45+1.20.1
	- controlling 12.0.2
	- coroutil 1.20.1-1.3.7
	- corundumguardian 2.2.0
	- cosmeticarmorreworked 1.20.1-v1a
	- crafttweaker 14.0.43
	- create 0.5.1.h
		\-- flywheel 0.6.11-13
	- create_enchantment_industry 1.2.9.d
		\-- create_dragon_lib 1.4.3
	- creativecore 2.11.37
	- creeperoverhaul 3.0.2
	- cupboard 1.20.1-2.7
	- curios 5.10.0+1.20.1
	- disenchanter 0.1.81.20
	- dramaticdoors 1.20.1-3.2.3
	- easymagic 8.0.1
	- easyshulkerboxes 8.0.2
		|-- puzzlesaccessapi 8.0.9
		\-- puzzlesapi 8.1.6
	- eeeabsmobs 1.20.1-0.95
	- embeddium 0.3.31+mc1.20.1
		\-- rubidium 0.7.1
	- endermanoverhaul 1.0.4
	- endrem 5.3.3-R-1.20.1
	- ends_delight 2.4
	- entity_model_features 2.2.4
	- entity_texture_features 6.2.3
	- equipmentcompare 1.3.7
	- everycomp 1.20-2.6.75
	- explorerscompass 1.20.1-1.3.3-forge
	- eyesoficeandfire 1.1.0-1.20.1
	- fabric_api 0.92.2+1.11.8+1.20.1
		|-- fabric_api_base 0.4.31+ef105b4977
		|-- fabric_api_lookup_api_v1 1.6.36+67f9824077
		|-- fabric_biome_api_v1 13.0.13+dc36698e77
		|-- fabric_block_api_v1 1.0.11+0e6cb7f777
		|-- fabric_block_view_api_v2 1.0.1+0767707077
		|-- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
		|-- fabric_client_tags_api_v1 1.1.2+5d6761b877
		|-- fabric_command_api_v1 1.2.34+f71b366f77
		|-- fabric_command_api_v2 2.2.13+561530ec77
		|-- fabric_content_registries_v0 4.0.11+a670df1e77
		|-- fabric_convention_tags_v1 1.5.5+fa3d1c0177
		|-- fabric_data_attachment_api_v1 1.0.0+30ef839e77
		|-- fabric_data_generation_api_v1 12.3.4+369cb3a477
		|-- fabric_dimensions_v1 2.1.54+8005d10d77
		|-- fabric_entity_events_v1 1.6.0+6274ab9d77
		|-- fabric_events_interaction_v0 0.6.2+0d0bd5a777
		|-- fabric_game_rule_api_v1 1.0.40+683d4da877
		|-- fabric_item_api_v1 2.1.28+4d0bbcfa77
		|-- fabric_item_group_api_v1 4.0.12+c9161c2d77
		|-- fabric_key_binding_api_v1 1.0.37+561530ec77
		|-- fabric_lifecycle_events_v1 2.2.22+afab492177
		|-- fabric_loot_api_v2 1.2.1+eb28f93e77
		|-- fabric_message_api_v1 5.1.9+52cc178c77
		|-- fabric_mining_level_api_v1 2.1.50+561530ec77
		|-- fabric_model_loading_api_v1 1.0.3+6274ab9d77
		|-- fabric_models_v0 0.4.2+7c3892a477
		|-- fabric_networking_api_v1 1.3.11+503a202477
		|-- fabric_object_builder_api_v1 11.1.3+2174fc8477
		|-- fabric_particles_v1 1.1.2+78e1ecb877
		|-- fabric_recipe_api_v1 1.0.21+514a076577
		|-- fabric_registry_sync_v0 2.3.3+1c0ea72177
		|-- fabric_renderer_api_v1 3.2.1+1d29b44577
		|-- fabric_renderer_indigo 1.5.2+b5b2da4177
		|-- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
		|-- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
		|-- fabric_rendering_v1 3.0.8+66e9a48f77
		|-- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
		|-- fabric_resource_loader_v0 0.11.10+bcd08ed377
		|-- fabric_screen_api_v1 2.0.8+45a670a577
		|-- fabric_screen_handler_api_v1 1.3.30+561530ec77
		|-- fabric_sound_api_v1 1.0.13+4f23bd8477
		|-- fabric_transfer_api_v1 3.3.5+631c9cd677
		\-- fabric_transitive_access_wideners_v1 4.3.1+1880499877
	- fallingleaves 2.1.0
	- fantasyfurniture 9.0.0
		|-- apexcore 10.0.0
		\-- commonality 7.0.0
	- farmersdelight 1.20.1-1.2.4
	- fastbench 8.0.4
	- fastfurnace 8.0.2
	- ferritecore 6.0.1
	- findme 3.2.1
	- flib 0.0.14
	- forge 47.3.7
	- forgeconfigscreens 8.0.2
	- framework 0.7.8
	- freecam 1.2.1+1.20
	- geckolib 4.4.9
	- gimm1q 0.6.11.20.1
	- graveyard 3.1
	- guardvillagers 1.20.1-1.6.7
	- ice_and_fire_spellbooks 2.2.0-1.20.1
	- iceandfire 2.1.13-1.20.1
	- iceberg 1.1.13
	- icterine 1.3.0
	- idas 1.10.1+1.20.1
	- integrated_api 1.5.1+1.20.1-forge
	- integrated_stronghold 1.1.1+1.20.1-forge
	- integrated_villages 1.0.1+1.20.1-forge
	- ironchests 5.0.2
	- irons_spellbooks 1.20.1-3.4.0
	- item_obliterator 2.3.0
	- jade 11.11.1+forge
	- jadeaddons 5.3.1+forge
	- jei 15.18.0.79
	- kotlinforforge 4.11.0
	- lionfishapi 1.9
	- lootr 0.7.34.85
	- mcwfurnitures 3.3.0
	- memoryleakfix 1.1.5
	- midnightlib 1.4.2
	- minecells 1.8.4patch1
	- minecraft 1.20.1
	- mob_catcher 1.3.1
	- modernfix 5.19.4+mc1.20.1
	- moonlight 1.20-2.12.20
	- moremobgriefingoptions 2.0.4
	- morevillagers 5.0.0
	- mousetweaks 2.25.1
	- mowziesmobs 1.6.4
	- naturescompass 1.20.1-1.11.2-forge
	- necronomicon 1.4.2
	- nerb 0.3
	- nethersdelight 1.20.1-4.0
	- notenoughanimations 1.7.6
	- nyfsspiders 2.1.1
	- oceansdelight 1.0.2-1.20
	- oculus 1.7.0
	- omega_config 1.2.3-1.18.1
	- owo 0.11.21.20
	- patchouli 1.20.1-84-FORGE
	- placebo 8.6.2
	- playeranimator 1.0.2-rc1+1.20
	- polymorph 0.49.5+1.20.1
	- puzzleslib 8.1.23
	- quark 4.0-460
	- quickstack 1.20.1-1
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.29
	- ribbits 1.20.1-Forge-3.0.0
	- saturn 0.1.3
	- scarecrowsterritory 1.1.11e
	- scguns 0.2.8
	- searchables 1.0.3
	- simplyswords 1.56.0-1.20.1
	- skinlayers3d 1.6.7
	- skyvillages 1.0.4
	- sliceanddice 3.2.1
	- smallships 2.0.0-b1.4
	- smartbrainlib 1.15
	- smoothboot 0.0.4
	- sophisticatedbackpacks 3.20.6.1064
	- sophisticatedcore 0.6.25.632
	- sophisticatedstorage 0.10.26.817
	- sound_physics_remastered 1.20.1-1.4.5
	- stalwart_dungeons 1.2.8
	- starlight 1.1.2+forge.1cda73c
	- storagedrawers 12.6.5
	- storagenetwork 1.10.0
	- structure_gel 2.16.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17+a
	- supplementaries 1.20-2.8.17
		\-- mixinsquared 0.1.1
	- taxfreelevels 1.3.13
	- terrablender 3.0.1.7
	- tlc 1.0.2
	- twilightforest 4.3.2508
	- twilighttweaks 1.2
	- visuality 2.0.2
	- waystones 14.1.5
	- weaponmaster_ydm 4.2.3
	- wunderlib 1.1.5
	- xaerominimap 24.4.0
	- xaeroworldmap 1.39.0
	- yungsapi 1.20-Forge-4.0.5
	- zeta 1.0-24
