### ISSUE TITLE
Immersive portals causing sounds to be heard through ground

### ISSUE THREAD

**Issue by Sorro123** [henkelmax/sound-physics-remastered#229]
### Bug description

https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1468 (all info is there)

### Minecraft version

1.20.4

### Mod version

1.2.3

### Mod loader and version

Fabric loader

### Steps to reproduce

1. Create a portal with immersive portals 
2. Listen out for sounds of mobs underground

### Expected behavior

Sounds are not audible through blocks

### Log files

N/A

### Videos

N/A

**Comment by henkelmax** [comment]
See #43 and #160
