### ISSUE TITLE
Sound from Entities that are not there.

### ISSUE THREAD

**Issue by TheRealDadbeard** [henkelmax/sound-physics-remastered#23]
I am using All the Mods 7 and added this one to it. Sometimes when I run around I hear an animal or zombie and when I dig for it the sounds just stops. Is there any way to debug this correctly?

soundphysics-forge-1.18.1-1.0.3
Minecraft 1.18.1
Forge 39.0.10

**Comment by henkelmax** [comment]
Please fill out the bug template
