### ISSUE TITLE
Some sounds only play casually

### ISSUE THREAD

**Issue by vico93** [henkelmax/sound-physics-remastered#231]
### Bug description

After updating to 1.21-1.4.5, i started noticing that some sounds, like block breaking (wood, workbench, stone...) and some [Presence Footsteps](https://modrinth.com/mod/presence-footsteps) step sounds often doesn't play, making the game far more silent than the normal.

Removing Sound Physics mod from the mods folder seems to fix this. Strangely, nothing on `latest.log` appears to indicate anything wrong code-wise.

### Minecraft version

1.21

### Mod version

1.21-1.4.5

### Mod loader and version

Fabric Loader 0.16.0

### Steps to reproduce

-

### Log files

-

### Videos

-

**Comment by henkelmax** [comment]
Please provide steps to reproduce these issues and include a video with debug rays enabled.

**Comment by vico93** [comment]
I took this video, but without the debug rays because i wasnt aware about how to enable this

https://github.com/user-attachments/assets/827e9982-b12e-4934-bd7c-ef1ea6e6bc83

**Comment by henkelmax** [comment]
Does this happen without any other mods installed?
Can you try resetting the sound physics config files?
You can enable the debug rays in the debug section of the mod settings.

**Comment by vico93** [comment]
Okay, i think you can ignore this issue.

The very same problem keep happening even with sound physics remastered removed.

**Comment by Fyoncle** [comment]
> Okay, i think you can ignore this issue.
> 
> The very same problem keep happening even with sound physics remastered removed.

Did you find the cause?

**Comment by vico93** [comment]
@Fyoncle still not, that's unfortunate.

But i figured out that F3+R can mitigate temporarially the problem
