### ISSUE TITLE
[Incompatibility???] Sounds Mod

### ISSUE THREAD

**Issue by Fyoncle** [henkelmax/sound-physics-remastered#232]
### Bug description

https://github.com/IMB11/Sounds/issues/68#
https://github.com/IMB11/Sounds/issues/77
Please read this two github issues for more information.
When either your mod or Make Bubbles pop removed, this error completely gets fixed for some reason. To reproduce you need BOTH Make Bubbles Pop and Sound Physics remastered installed alongside Sounds

### Minecraft version

1.20.1

### Mod version

1.4.5

### Mod loader and version

0.15.11

### Steps to reproduce

Stated above in the github issues.

### Expected behavior

To not lag.

### Log files

Given in the github issues above.

### Videos

Also on the github issues above.

**Comment by henkelmax** [comment]
This sounds like an issue with the other mod, as the issue does not happening with an older version of that mod.

**Comment by Fyoncle** [comment]
> This sounds like an issue with the other mod, as the issue does not happening with an older version of that mod.

Oh okay.

**Comment by Fyoncle** [comment]
> > This sounds like an issue with the other mod, as the issue does not happening with an older version of that mod.
> 
> Are you referring to Make Bubbles Pop or Sounds?

Probably Make Bubbles Pop since Sounds doesn't cause issues standalone without using your mod.

**Comment by IMB11** [comment]
> This sounds like an issue with the other mod, as the issue does not happening with an older version of that mod.

It would still help me to understand where this issue is coming from, Sounds doesn't actually touch anything related to the underlying sound system, yet Sound Physics Remastered cannot handle many sounds being played at once when Sounds is installed.

**Comment by IMB11** [comment]
Sounds does load ~30-40 custom sounds via a resource pack (sounds.json) - maybe thats the issue? I have the foggiest clue honestly.

**Comment by Fyoncle** [comment]
> Sounds does load ~30-40 custom sounds via a resource pack (sounds.json) - maybe thats the issue? I have the foggiest clue honestly.

Probably best way to find out is to try different methods of applying sounds and see if its fixes with the 2 mods installed together

**Comment by henkelmax** [comment]
Having a lot of sounds played is a general issue. SPR does very heavy processing on sounds, so thats expected. You can tweak the performance settings, but thats always at the cost of quality.

**Comment by IMB11** [comment]
The thing is, this low FPS occurs even when no sounds are playing at all.

**Comment by IMB11** [comment]
For any events that are played alot (item movement/scrolling etc.) there is a cooldown system which ensures that events within a short timeframe (100-350ms) are merged into one playSound call.

**Comment by IMB11** [comment]
I've looked into everything, and it seems that Sound Physics Remastered just... sucks in performance when Sounds is installed for no reason at all.

I'm going to spend more time tomorrow seeing if it may be the fact that SPR can't handle many sounds being loaded into memory via resource packs, rather than played at the same time.

**Comment by IMB11** [comment]
This issue should definitely be reopened though, as clearly it's not something on my part (that I can see, I've looked into literally everything, every possibility of where this might be occuring.)

**Comment by IMB11** [comment]
The only pain point I can think of is if SPR excessively retrieves block sound groups, which vanilla already does quite a bit, I could mess about with the caching system I have in place to see if it causes any improvements, but I highly doubt it

**Comment by henkelmax** [comment]
> I've looked into everything, and it seems that Sound Physics Remastered just... sucks in performance when Sounds is installed for no reason at all.
> 
> I'm going to spend more time tomorrow seeing if it may be the fact that SPR can't handle many sounds being loaded into memory via resource packs, rather than played at the same time.

SPR does not do anything when no sounds are played. It gets only triggered when a sound actually plays. A lot of sounds being loaded in memory would not affect the mod at all.
