### ISSUE TITLE
Long player sounds are cut short on death

### ISSUE THREAD

**Issue by ShadyInktail** [henkelmax/sound-physics-remastered#233]
### Bug description

Long player sounds supplied by resource packs are cut off when sound physics are enabled on the death screen. After the first second, the sound(s) stops abruptly. If played using /playsound, the sound continues as normal. No settings changes appears to correct it aside from disabling the mod entirely. The sounds still play correctly in version 1.20.4-1.3.1, 1.4.0, and 1.4.1. This issue also seems to affect version 1.20.4-1.4.2.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.4.5

### Mod loader and version

Fabric Loader 0.15.10

### Steps to reproduce

1. Enable a resource pack that has a player death sound longer than 1 second.
2. Make sure sound physics are enabled in the mod config.
3. In any way, kill the player.
4. The sounds that the player makes at death will be cut to the first second of it's duration, including the event for death and normal hurt sounds if applicable.

### Expected behavior

The death screen sound should play at the full duration with sound physics enabled, instead of ending abruptly after 1 second. Use mod version 1.20.4-1.3.1, 1.4.0, or 1.4.1 and repeat the reproduction steps for an example of expected behavior.

### Log files

https://pastebin.com/7uvTQE5S

### Videos

Sound Physics incorrect behavior on 1.20.4-1.4.2 or higher: https://youtu.be/KqKXWTb-los
Sound Physics correct behavior on 1.20.4-1.4.1 or lower (1.3.1 is used in demonstration): https://youtu.be/j5trgZ6j_yM

**Comment by henkelmax** [comment]
Minecraft 1.20.4 is no longer actively supported.
If this also happens in 1.19.2, 1.20.1 or 1.21 I'll reopen the issue.
Does this also happen without the mod? Because the mod does not change the length of played sounds.

**Comment by ShadyInktail** [comment]
Well I opened the issue with the 1.20.4 version because that's the version I am currently using and 1.20.4-1.4.2 is the first version the bug appears in. I have 1.19.2 and it does not happen there, and I actively used the mod all throughout 1.20 without a hitch. It does happen in 1.21-1.4.5, and if the mod is disabled in settings or by the launcher, the issue does not occur.

**Comment by henkelmax** [comment]
Does the issue also happen in versions prior to 1.4.0?

**Comment by ShadyInktail** [comment]
The issue does not happen in anything below 1.4.0. I previously used 1.2.1 and 1.3.1 before updating to 1.4.2, and it did not happen in either 1.2.1 or 1.3.1. The versions I used before noticing the issue are 1.2.1, 1.3.1, 1.4.0, and 1.4.1. Any version past 1.4.1 appears to have this issue.

**Comment by henkelmax** [comment]
Alright, it could be related to #172 then
