### ISSUE TITLE
Console/log spam

### ISSUE THREAD

**Issue by samve000** [henkelmax/sound-physics-remastered#236]
### Bug description

When I open a new world, the console starts spamming
```
Set environment filter0:: OpenAL error AL_INVALID_VALUE
Set environment filter1:: OpenAL error AL_INVALID_VALUE
```

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.5

### Mod loader and version

Fabric Loader 0.16.0

### Steps to reproduce

1. Install Sound Physics mod
2. Start a new world
3. Wait

### Expected behavior

Not for my log to get spammed with errors

### Log files

https://mclo.gs/udy2Pjc

### Videos

No video's needed, I was just standing still after spawning in my world.
![image](https://github.com/user-attachments/assets/5fb6148c-7542-4fc3-b1e3-98399fe6c8b3)

**Comment by henkelmax** [comment]
Which OS are you using?
Did you try updating your audio drivers?

**Comment by samve000** [comment]
I'm using Windows 11, the Intel® Driver & Support Assistant says all my drivers are up to date.

**Comment by henkelmax** [comment]
Unfortunately thats nothing I'm able to reproduce.
Does the same thing happen with just SPR installed?
Does it happen without any mods at all?

**Comment by samve000** [comment]
With just SPR installed nothing happens, there's probably something wrong with other mods not being compatible but idk which mods. I also realized that this problem only occurs when disabling a resource pack. I tried looking if there was a problem with one of the entity sound/model/texture features mods but they seem to be fine too.

**Comment by henkelmax** [comment]
Yeah then its an issue/incompatibility with another mod/datapack. please check which is causing it.
