### ISSUE TITLE
 Incompatible with Create Fabric

### ISSUE THREAD

**Issue by Mlig317** [henkelmax/sound-physics-remastered#238]
### Bug description

![image](https://github.com/user-attachments/assets/f60f49e8-d7ce-4b6a-ba79-4c69e77984e0)
Not sure where to report this incompatibility but the create mod team mentioned it was an issue with this mod and not with them. 

### Minecraft version

1.20.1

### Mod version

1,20.1.1.4.5

### Mod loader and version

fabric (latest)

### Steps to reproduce

create modpack with create fabric and sound physics remastered
launch modpack

### Log files

.

### Videos

.

**Comment by henkelmax** [comment]
#172
