### ISSUE TITLE
Muffled Sound from Entities that are not there

### ISSUE THREAD

**Issue by TheRealDadbeard** [henkelmax/sound-physics-remastered#24]
**Bug description**
There is muffled  sound coming for example a Chicken but I am seeing nothing. 

**Steps to reproduce the issue**
1. Run around until you hear a muffled sound but see no entity
2. Locate it then dig down
3. Sound stops
4. Go back up, fill up the hole sound continues muffled

**Expected behavior**
Have no sound play for nothing

**Log files**
I have no idea which on of my log files was where I had this issue. Had it happen in all of these play sessions.
[2022-01-05-5.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/7817320/2022-01-05-5.log.gz)
[2022-01-05-4.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/7817321/2022-01-05-4.log.gz)
[2022-01-05-3.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/7817322/2022-01-05-3.log.gz)

**Versions**
- Minecraft 1.18.1
- Forge 39.0.10
- Mod 1.0.3

**Other mods**
I am using All the Mods 7 Modpack v 0.2.19 with those added mods to it:
Simple Voice Chat 1.18.1-2.2.0
Sound Physics Remastered 1.18.1-1.0.3
Packing Tape 1.18-0.12.2
Carry on 1.18.1-1.17.0.5
ItemPhysic FULL v1.4.20_mc1.18.1
DoggyTalents 1.18.1-2.4.0
Entity Culling Fabric/Forge 1.3.3 FORGE
AmbientSounds v5.0.0_mc1.18.1
Falling Leaves
Not Enough Animations

**Comment by henkelmax** [comment]
This has already been fixed. Please reset the config to get it fixed.

**Comment by TheRealDadbeard** [comment]
> This has already been fixed. Please reset the config to get it fixed.

I am not upgrading. I started using 1.0.3,

**Comment by henkelmax** [comment]
> I am not upgrading. I started using 1.0.3.

Make sure every config value is the default.

> There is muffled sound coming for example a Chicken but I am seeing nothing

Of course you aren't seeing it when its muffled, it means it is behind blocks.

**Comment by TheRealDadbeard** [comment]
Should have worded it differently. I hear a muffled sound but after digging for it there is nothing. It just stops on block under the ground where it came from.

I will enable debug rendering the next time this happens. Is this a toggleable option? Or in the config?

**Comment by henkelmax** [comment]
> I will enable debug rendering the next time this happens. Is this a toggleable option? Or in the config?

Either cloth config GUI or the config file.

Also make sure you are not actually hearing sound reflecting off of a wall.

**Comment by TheRealDadbeard** [comment]
> > I will enable debug rendering the next time this happens. Is this a toggleable option? Or in the config?
> 
> Either cloth config GUI or the config file.
> 
> Also make sure you are not actually hearing sound reflecting off of a wall.

Ok. It just happens out in the open. Will try this next time.

**Comment by TheRealDadbeard** [comment]
Okay I enabled the debug view which didn't really help me but I recorded a short video of the issue.

https://filen.io/d/dee7d4c1-8719-45b5-8193-2fa6da50258b#!6xLhVX4WCPjr1CuEGe3YSiJazOZwPRPr

**Comment by TheRealDadbeard** [comment]
Okay so it seems that it echoes some entities that are above ground but a couple of block away. Had a muffled chicken sound but found two chickens above ground like 30 blocks away. I have the mod installed on the server too so maybe that is causing it?

**Comment by henkelmax** [comment]
I can't see anything wrong either in your video.

> I have the mod installed on the server too so maybe that is causing it?

Nope

**Comment by TheRealDadbeard** [comment]
> I can't see anything wrong either in your video.
> 
> > I have the mod installed on the server too so maybe that is causing it?
> 
> Nope

Huh what? You didn't listen and heard a muffled sound right were I stood and when I dug for it it dissapeared? And then when I came back up it played again a muffled monster sound.

**Comment by henkelmax** [comment]
I don't get why you dug down. The sound didn't came from there.

**Comment by TheRealDadbeard** [comment]
> I don't get why you dug down. The sound didn't come from there.
> 
> If you really want to test it. Create a creative world, where you fly, so the footstep sounds don't confuse you.

I came right from that point. Like literally from the ground.

**Comment by henkelmax** [comment]
> I came right from that point. Like literally from the ground. I am not confused by any footsteps.

Nope these sounds are the footstep sounds originating from your feet.

> Why are you so hard to work with? You mod has a bug.

Then please show me a minimal reproducible setup of the bug.
You just hear a muffled sound and called it a bug.

You don't even know where it comes from.

You are the one that's hard to work with. I can't even tell what's your issue. Normally when reporting a bug you should provide an exact setup to recreate the issue.

**Comment by TheRealDadbeard** [comment]
> > I came right from that point. Like literally from the ground. I am not confused by any footsteps.
> 
> Nope these sounds are the footstep sounds originating from your feet.
> 
> > Why are you so hard to work with? You mod has a bug.
> 
> Then please show me a minimal reproducible setup of the bug. You just hear a muffled sound and called it a bug.
> 
> You don't even know where it comes from.
> 
> You are the one that's hard to work with. I can't even tell what's your issue. Normally when reporting a bug you should provide an exact setup to recreate the issue.

?????????????????????????????


    Run around until you hear a muffled sound but see no entity
    Locate it then dig down
    Sound stops
    Go back up, fill up the hole sound continues muffled

**Comment by henkelmax** [comment]
I don't really understand the issue. Could you please recreate it in a minimal world (Like a void or superflat world) with no other sounds and make a video of it. And also please remove the ambient sounds. It's really hard to distinguish the sounds when you constantly have background sounds. And please also remove the shaders. It makes it really hard to see the debug lines.

**Comment by TheRealDadbeard** [comment]
> 

I will

**Comment by TheRealDadbeard** [comment]
First example:

Crocs are nearby but I hear them right beside me but muffled. I show it in the video where they are. This is the same that happened in the other video too.

https://filen.io/d/ee47d1bf-a941-4fa5-9ff6-ae45f75a003d#!CN13dvDywEwz6z54QMi5qJ3IqF9LSUas

I now try to reproduce this in a flatworld.

**Comment by TheRealDadbeard** [comment]
Does not seem to happen in a superflat world with only 2 block height. Trying higher

**Comment by TheRealDadbeard** [comment]
I managed to recreate it in a superflat world https://filen.io/d/73de8d9c-3498-4bb9-80d6-97283db8ac79#!QvBRPtDGrmZUN503dAqY4xe5UdHy2X69

**Comment by henkelmax** [comment]
I recreated the same situation in a superflat world. I can't seem to reproduce it. Please try if it happens without any other mods.

**Comment by TheRealDadbeard** [comment]
Just reproduced it. Only your mod. Forge 39.0.10

https://filen.io/d/c2946cb3-99a9-4a04-a103-7ac315b15d23#!QEBrkdmlcvzY1qdkwopdOFs2zqW7CLcV

**Comment by henkelmax** [comment]
Please set your difficulty to peaceful and remove all other sound sources. I can't see anything like this.

**Comment by TheRealDadbeard** [comment]
I cant anymore for real. You literally HEAR a slime sound next to me even if the next one is a couple of blocks away. 

Now you want me to remove anything that makes sound? What?????

**Comment by RobbenBande** [comment]
Can Confirm, i have the same Issue Here

**Comment by henkelmax** [comment]
> I cant anymore for real. You literally HEAR a slime sound next to me even if the next one is a couple of blocks away.
> 
> Now you want me to remove anything that makes sound? What????? That literally makes zero sense,
> 
> Please explain to me in detail how I should reproduce it when there is no sound. The whole purpose your mod exists, sounds.

Its not that I don't hear it. I want to understand why it happens. With 1000s of sounds you can't see it. With a single sound you can clearly see it.

**Comment by TheRealDadbeard** [comment]
Then just say that? There is clearly a communication barrier somewhere.

You literally told me to disable every sound. Just say you want me to spawn a couple of mobs in an empty field and test that out.

**Comment by TheRealDadbeard** [comment]
I can only reproduce it close to structures. Like the village in my video. I tried playing blocks anything and I can't repro it.

**Comment by TheRealDadbeard** [comment]
Peaceful near a village. I hear a villager echoing and a bat. There is no cave in the ground. It's a two block deep flatworld.

https://filen.io/d/45a3f1b9-0a06-431d-ad65-26f84d769f4d#!8U4fVKRZdc9DuelASfSwIMAnMFY611SK

**Comment by henkelmax** [comment]
> Edit: Me digging down and more showing the same bug

This is completely intended. The sound gets muffled when blocks are between you and the sound source. Everything is fine there.

**Comment by TheRealDadbeard** [comment]
> > Edit: Me digging down and more showing the same bug
> 
> This is completely intended. The sound gets muffled when blocks are between you and the sound source. Everything is fine there.
> 
> > I can only reproduce it close to structures. Like the village in my video. I tried playing blocks anything and I can't repro it.
> 
> Same with that.

What? What is fine about that? Hearing echoing sounds from sources that are not close? Dude I give up you mod has a bug but you are to dense to accept that.

HOLY SHIT

**Comment by henkelmax** [comment]
> What? What is fine about that? Hearing echoing sounds from sources that are not close? 

The whole issue was about the muffling of the sounds not the echo.

I think you are mixing up two things there.

**Comment by LuckyGolem** [comment]
I have the same issue. Since like 1 Week now.

**Comment by TheRealDadbeard** [comment]
Disablind "Sound Direction Evaluation" make the ghost sounds dissapear instantly.

**Comment by LuckyGolem** [comment]
Oh really? thank you but the Dev really needs to fix that soon!

**Comment by henkelmax** [comment]
Pretty sure its the same as #25

**Comment by TheRealDadbeard** [comment]
Same and exact issue I was talking about all the time and what is seen in my videos.

**Comment by henkelmax** [comment]
> Same and exact issue I was talking about all the time and what is seen in my videos.

The person that made the other issue had a very clear setup. I never understood what you wanted to tell me in your videos...

**Comment by TheRealDadbeard** [comment]
> > Same and exact issue I was talking about all the time and what is seen in my videos.
> 
> The person that made the other issue had a very clear setup. I never understood what you wanted to tell me in your videos...

Lol wtf haha. Literally the same. I am in a location and hear sounds from entities that are far away. It's shown in multiple videos.

But yeah just circlejerk on your fork. Whatever.
