### ISSUE TITLE
Incompat with Create's Eureka, VS2+Diesel, Sound issue I believe

### ISSUE THREAD

**Issue by Rhaptein** [henkelmax/sound-physics-remastered#240]
### Bug description

Very specific instance but oddly enough it freezes the game instead of crashing. I've tested and tested mods but this one was the culprit.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.5

### Mod loader and version

Forge 47.2.17

### Steps to reproduce

To reproduce;
Activate a diesel generator.
Turn on it's physics with eureka ship helm.
Then deassemble the whole build.
Game freezes and tries to pick up.

### Expected behavior

What is supposed to happen was for the build to place without freezing ofc, I've tried it with and without and it didn't fail freezing my game when this mod was active.
It's a weird bug but I'm going to assume there's too many sound events going on for the mod to handle after deassembling.

### Log files

https://gist.github.com/Rhaptein/69ba30ef1fbe529d0aff8ec20783598b

### Videos

https://github.com/user-attachments/assets/a38109ec-bc62-4d16-91d4-526c3529696e

**Comment by henkelmax** [comment]
> It's a weird bug but I'm going to assume there's too many sound events going on for the mod to handle after deassembling.

You should blacklist sounds that are spammed a lot. The mod does a lot of processing for every sound thats being played. It simply can't handle that.
