### ISSUE TITLE
Minor incompatibility with the Dynamic Surroundings Sound Pack resource pack in forge 1.20.1

### ISSUE THREAD

**Issue by GamingWithDudeAlt** [henkelmax/sound-physics-remastered#244]
### Bug description

There's a minor incompatibility with the dynamic surroundings sound pack resource pack where you can hear foot steps from mobs  that aren't near you (both vanilla and modded). It's not game breaking or anything but it can get annoying after an extended period of time.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.5

### Mod loader and version

Forge 47.3.0

### Steps to reproduce

1) Install the most recent version of this resource pack with the mod and enable the resource pack: https://www.curseforge.com/minecraft/texture-packs/dynamic-surroundings-remastered/files/all?page=1&pageSize=20&version=1.20.1&sortBy=dateCreated&sortOrder=desc

2) Go into a world and find a village.

3) Once you find a village, fly decently far away from it (about 35 - 60 blocks away from it should maybe be good) while making sure it's still within your render distance.

4) You should be able to hear the footsteps from the villagers (I was looking towards it so look towards it) despite you not being near them.

### Expected behavior

You shouldn't be able to hear the foot steps of the villagers or mobs from the same distance away as in vanilla Minecraft.

### Log files

[latest.log](https://github.com/user-attachments/files/16645425/latest.log)

### Videos

Sorry if the resolution ain't the best, and also sorry if I made it a little long: https://www.youtube.com/watch?v=zWb_G5ihY4A

**Comment by henkelmax** [comment]
This might be a bug with the resource pack itself. If the resource pack contains sound files that are stereo, the volume won't change with distance. Please check if this also happens without the mod.

**Comment by GamingWithDudeAlt** [comment]
I already tried before hand and this doesn't happen without the mod.

**Comment by henkelmax** [comment]
And you checked that the audio files are not stereo?

**Comment by henkelmax** [comment]
Please also tell me the exact sound where the issue is happening.

**Comment by GamingWithDudeAlt** [comment]
I'm not sure how to check the resource packs files. And what do you mean by "exact sound"?

**Comment by GamingWithDudeAlt** [comment]
Actually i figured out how to check the resource pack files, and the footsteps end in .ogg. I'm not sure if that's stereo or not though

**Comment by GamingWithDudeAlt** [comment]
Actually how would I check if a sound is stereo or not?

**Comment by henkelmax** [comment]
> I'm not sure how to check the resource packs files. And what do you mean by "exact sound"?

Whats the sound thats playing with the wrong distance?

**Comment by GamingWithDudeAlt** [comment]
> > I'm not sure how to check the resource packs files. And what do you mean by "exact sound"?
> 
> Whats the sound thats playing with the wrong distance?

Every footstep sound, including the vanilla ones.

**Comment by henkelmax** [comment]
Does that happen without any other mods installed?

**Comment by henkelmax** [comment]
Closed due to inactivity.

**Comment by henkelmax** [comment]
Minecraft does not support playing locational stereo sounds. This breaks minecrafts sound system.
