### ISSUE TITLE
Incompatible with create

### ISSUE THREAD

**Issue by xXFoundationXx** [henkelmax/sound-physics-remastered#245]
### Bug description

(Crash on start up)

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 with any version that is compatible with:
		 - sound_physics_remastered 1.20.1-1.4.5
More details:
	 - Mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 is incompatible with any version of mod 'Sound Physics Remastered' (sound_physics_remastered), but a matching version is present: 1.20.1-1.4.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Minecraft version

1.20.1

### Mod version

[create-1.20.1-0.5.1.f.jar] and [sound-physics-remastered-fabric-1.20.1-1.4.5.jar]

### Mod loader and version

Fabric - 0.16.2

### Steps to reproduce

Add sound physics, 
add create
start game
[Crash]

### Expected behavior

Crash on start up

### Log files

https://gist.github.com/xXFoundationXx/7edfe9d6f5c074c0be97853fbb7d3ddb

### Videos

![Fabric Loader 0 16 2 8_20_2024 6_38_56 AM](https://github.com/user-attachments/assets/1134c714-5929-47bf-a10c-51853e917c10)

**Comment by henkelmax** [comment]
See #172
