### ISSUE TITLE
Sound Physics Not Compatible

### ISSUE THREAD

**Issue by ItzBoltStrike** [henkelmax/sound-physics-remastered#247]
### Bug description

Sound Physics is not compatible with the new version of Create

 Create 0.5.1-fbuild.1417+mc1.20.1/
 

### Minecraft version

1.20.1

### Mod version

All versions

### Mod loader and version

Fabric Loader 0.16.3

### Steps to reproduce

1. Download Sound Physics
2. Download Create 0.5.1-fbuild.1417+mc1.20.1

### Expected behavior

Sound Physics should be compatible with Create

### Log files

https://gist.github.com/ItzBoltStrike/a2ca7cd99fe323e3b3cb90dcee65cbbb

### Videos

Look

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by henkelmax** [comment]
See #172
