### ISSUE TITLE
Echo issues in multiplayer

### ISSUE THREAD

**Issue by Trojankill** [henkelmax/sound-physics-remastered#249]
### Bug description

When my friend and I turn on echo, when we enter a mine or building that creates echo, instead of echo we hear a loud ringing in our headphones (we play with a sound physics mod and a simple voice chat mod, they have the latest version)
I use these mods in my 80+ mod build.
Some mods I use
Embeddium is embeddium++ rubiddium
enhacnedVisual
oculus
simple voice chat
sound physic remastered

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.5

### Mod loader and version

Forge 47.3.7

### Steps to reproduce

1 Login to Minecraft
2 Join server (local server)
3 Two or more people must enter the shaft.
4And say something into the microphone when it's on.

### Expected behavior

I expect someone to help me with the problem or I will wait for a ready configuration with a solution to the problem without disabling echo

### Log files

I don't see the point in sending the magazine, I'll send it if someone asks.

### Videos

There is no video yet, I will try to send it soon

**Comment by henkelmax** [comment]
Please send me your sound physics config.

**Comment by henkelmax** [comment]
> I don't see the point in sending the magazine, I'll send it if someone asks.

Magazine?

**Comment by Trojankill** [comment]
second

**Comment by Trojankill** [comment]
[2024-09-09-1.log](https://github.com/user-attachments/files/16933594/2024-09-09-1.log)

**Comment by Trojankill** [comment]
![Desktop Screenshot 2024 09 09 - 19 41 08 54](https://github.com/user-attachments/assets/8d62b8b0-30b8-4ceb-a0a1-b7bf777320c4)
![Desktop Screenshot 2024 09 09 - 19 41 12 17](https://github.com/user-attachments/assets/0af85f77-1c8e-4a1e-a1d8-be93ef6b9d5e)
![Desktop Screenshot 2024 09 09 - 19 41 20 22](https://github.com/user-attachments/assets/63742fff-1ad8-40c4-923b-869d08ef4439)

**Comment by Trojankill** [comment]
The rest of the settings are default.

**Comment by henkelmax** [comment]
Please just send me the config file. I can't read these screenshots.

**Comment by Trojankill** [comment]
There are 5 files that I can't upload.

**Comment by Trojankill** [comment]
file soundphysic.properties not support github

**Comment by Trojankill** [comment]
[soundphysics.zip](https://github.com/user-attachments/files/16933676/soundphysics.zip)

**Comment by Trojankill** [comment]
The configuration will be in a zip archive.

**Comment by henkelmax** [comment]
You have the voice chat integration enabled. Disable it and you won't get an echo.

**Comment by Trojankill** [comment]
Is there a way to get rid of the ringing and leave the echo?

**Comment by Trojankill** [comment]
I tried to use the echo in the lonely world, in the mine, but now there was no ringing.

**Comment by Trojankill** [comment]
Why does everything work fine in single player but not on the server?

**Comment by henkelmax** [comment]
This isn't an issue with your mod. This happens because the microphone picks up the speakers.

**Comment by Trojankill** [comment]
Damn, I'm stupid, thank you very much, sorry for wasting your time
