### ISSUE TITLE
Mob sounds offset

### ISSUE THREAD

**Issue by CaramelTurbine** [henkelmax/sound-physics-remastered#25]
**Issue**
For some reason, certain sounds processed versions seem to be really far from the source. Ive got an animal pen near my base, but i keep hearing the animals in the animal pen in different places through the world.

**Steps to reproduce the issue**
1. Create a collection of mobs in one small area to generate a lot of noise
2. walk roughly 40 blocks away in any cardinal direction (x OR z/ stay at the same y level )
3. All the sound is muffled so i think the block occlusion calcs are getting offset by a couple of chunks.

**Log files**
https://gist.github.com/CaramelTurbine/fdcf28ab99c9a011afe6cde235065a11

**Versions**
- Minecraft: 1.18.1
- Fabric: 0.12.12
- Mod version: 1.0.3

**Other mods**
(I had loads more mods on when i discovered this problem but i tried running it with most of them turned off for this test.)
- Cloth config
- fabric api
- mod menu (prospector)
- world blend snapshots (chylex)
- Terralith v2.0.9 (datapack)
- Amplified Nether (datapack)

**Comment by henkelmax** [comment]
This is completely intended. Sounds can bounce off of walls and appear to be coming from other directions. This sometimes doesn't sound realistic, so if you want to disable it, set `sound_direction_evaluation` to false in the config.

**Comment by CaramelTurbine** [comment]
I dont think Sound direction evaluation is unrealistic, i think its straight up broken.
I reproduced the issue in a new world. (using all my mods and none of my mods makes no difference)
Hopefully this video gives you a way of fixing this feature.

All my SFR settings are on default in the video.

https://www.youtube.com/watch?v=X9dGybdiZiQ

**Comment by henkelmax** [comment]
Interresting. Can you send me that world, so I can debug stuff on it?

**Comment by TheRealDadbeard** [comment]
Yeah literally the same issue that I am having

**Comment by LuckyGolem** [comment]
Yep same for me.

**Comment by CaramelTurbine** [comment]
[SoundTest.zip](https://github.com/henkelmax/sound-physics-remastered/files/7834056/SoundTest.zip)
heres the world i used

**Comment by henkelmax** [comment]
> [SoundTest.zip](https://github.com/henkelmax/sound-physics-remastered/files/7834056/SoundTest.zip)
> heres the world i used

Thanks! I will look into it.

**Comment by Alaric323** [comment]
Same here.  Inside a village with an Illager base a bit of a distance away.  Can hear the Illagers as if they were very close by, as if they were inside the village.

Perhaps the sound direction evaluation is working since it seems as if it's bouncing "off the roof" in this video, but there's no volume dropoff due to distance/the volume dropoff is bugged?

https://user-images.githubusercontent.com/4038592/148669550-17d37f14-962b-4e77-952a-e234cc5548e6.mp4
