### ISSUE TITLE
URGENT - In need of contact with creator of sound physics remastered. Need to add in my modpack and need permission from creator.

### ISSUE THREAD

**Issue by notbrycem** [henkelmax/sound-physics-remastered#251]
### Bug description

I could not find your contact info anywhere else so please return contact to this ticket. 

In need of contact with creator of sound physics remastered. Need to add in my modpack and need permission from creator.

### Minecraft version

1.21

### Mod version

1.4.6

### Mod loader and version

Fabril loader 0.16.0

### Steps to reproduce

Return email to madore1223@gmail.com

### Expected behavior

a follow up

### Log files

https://gist.github.com/.

### Videos

n/a

**Comment by henkelmax** [comment]
The mod has an open source license, so you don't need to ask for permission.
