### ISSUE TITLE
[Fabric 1.21.1 Modpack] Unreported exception thrown! java.lang.ExceptionInInitializerError: null 

### ISSUE THREAD

**Issue by suerion** [henkelmax/sound-physics-remastered#252]
### Bug description

Hey, we had a Modpack, that we try to play together, one of our Players get allways an error on joining minecraft.

Other Players could connect without issues

### Minecraft version

1.21.1

### Mod version

1.21.1-1.4.6

### Mod loader and version

Fabric 0.16.5

### Steps to reproduce

Start Client and Connect to server
After Connecting, the Players Game Crash

### Log files

https://mclo.gs/P5tQDWv

### Videos

No Video, Client Crash with Exception

**Comment by henkelmax** [comment]
I am not able to reproduce your issue. Please make sure this happens without any other mods and is reproducible.
