### ISSUE TITLE
Sounds sometimes don't play when there are a lot of sound sources

### ISSUE THREAD

**Issue by VindSole** [henkelmax/sound-physics-remastered#253]
### Bug description

I was in a world with lots of entities underground, and I noticed sounds just don't play sometimes, I don't remember this happening before. I tried blacklisting the entity sounds in the config, and while they were not reverberated and there was much less lag, the issue still occurs (player step sounds and breaking blocks were consistent in showing this behavior), I also turned on sound subtitles and they do appear fine even if the sound does not play. I tried on a new instance with only this mod and it still happens, only way to fix it is to disable SP in the config or remove the mod.

### Minecraft version

1.21.1

### Mod version

1.21.1-1.4.6

### Mod loader and version

Fabric Loader 0.16.5

### Steps to reproduce

1. Go underground (to better notice missing sounds) and spawn a lot of entities like cows or chicken
2. Sounds start being skipped, notably ones closer to player like stepping and breaking block sounds
3. Reduce entity sounds in settings to notice it better

### Expected behavior

All sounds play normaly, blacklisted sounds shouldn't affect reverberated sounds.

### Log files

https://gist.github.com/VindSole/fb1ebdbfb79ea791c9e90fd82dabb97b

### Videos

https://github.com/user-attachments/assets/5e871df5-5830-4421-b228-38a9c3001e9e

**Comment by henkelmax** [comment]
Processing of sounds with this mod does take a lot of resources, so you should avoid spamming a lot of sounds at once at all cost. The mod skips processing sounds if its getting overloaded which this cow farm definitely does.
