### ISSUE TITLE
Hear Self breaks sound physics

### ISSUE THREAD

**Issue by TysonTheEmber** [henkelmax/sound-physics-remastered#256]
### Bug description

Hear self breaks sound physics, crazy distortion, and volume spikes

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.5

### Mod loader and version

Forge 47.3.11

### Steps to reproduce

Install simple voice chat and sound physics remastered and turn on hear self

### Expected behavior

Clean echos and stable volume

### Log files

https://gist.github.com/TysonTheEmber/8146f9eb26060d192378a0b56e0923f8

### Videos

https://youtu.be/EB6RyE6t3hc

**Comment by henkelmax** [comment]
I tested it and it works perfectly fine. Make sure your mic isn't picking up your speaker.

**Comment by TysonTheEmber** [comment]
I use headphones and a good mic. Are you sure you tested it? and are you using outdated drivers or the like?(all my drivers are up to date)

**Comment by henkelmax** [comment]
What do you mean with correct conditions? I followed the steps to reproduce you provided. Even in caves, it sounds exactly like it should.

**Comment by TysonTheEmber** [comment]
https://youtu.be/M-2jchktKZs If you still cant reproduce this then I will ask my community if they can.

**Comment by henkelmax** [comment]
Yeah its really hard to fix an issue that I am not able to reproduce, sorry.

**Comment by TysonTheEmber** [comment]
Are you using windows??? If not mby make a VM and try it

**Comment by TysonTheEmber** [comment]
I had some others test it and it seems it might be something to do with my headphones. Will get back if I find the specific problem

**Comment by TysonTheEmber** [comment]
It was a issue with my headphones and the voicechat settings set to my headphones, I will have to contact the devs of voicechat prob

**Comment by TysonTheEmber** [comment]
![image](https://github.com/user-attachments/assets/0098692e-67e2-48f0-9746-3a029bbaf531)
I had to change it to nvidia broadcast

**Comment by henkelmax** [comment]
Thats an issue with your audio drivers then. Its not an issue with the voice chat mod.
