### ISSUE TITLE
Sound Physics Remastered: Moving Forward

### ISSUE THREAD

**Issue by thedocruby** [henkelmax/sound-physics-remastered#26]
It's time to face the truth: Sound Physics Remastered is an obsolete fork of an older version of Sound Physics. Since it was released, all of the features and bugfixes have been implemented in the base mod in one form or another, along with many new features that were never in the remastered version. In addition, Sound Physics Remastered is barely maintained past updating to 1.18 and fixing bugs, whereas Sound Physics is actively maintained and I am developing new features constantly. Sound Physics Remastered had a good run as a great fork of the mod, but it's time that it stepped out of the spotlight and let the newer features take their place

I'm not proposing that Sound Physics Remastered be removed entirely, only that the fabric version is removed. I never plan to port to Forge, so I don't mind if you maintain a Forge port of the mod. All i ask is that you link to the fabric version in your mod description, and I will link to your page as the forge version. That way, we don't lose users when they realize that you no longer provide a fabric version.

I considered somehow keeping the fabric version of this fork, but I quickly realized that no matter what else I did, it would continue to take away from the work i have put into this mod. I also considered the complete removal of Sound Physics Remastered, but I do recognize the fact that you did put a lot of work into this mod originally, and I think you deserve some credit for that, so I decided it was best that you continue to provide the forge version.

I believe this is a good compromise that gets us both something that we are happy with, If i am wrong in thinking that, or if you would like to change some of the terms of the arrangement, just let me know. Otherwise, say the word and I will hold up my end of the agreement.

**Comment by henkelmax** [comment]
This version of sound physics was never meant to replace the original one. This is just a fork optimized for simple voice chat.
When I created the fork, the original mod was an unoptimized mess with a huge load of bugs. I put a lot of work into it and I haven't looked at the original mod since then. But I will keep maintaining this fork. And since it has double the amount of downloads It definitely has a reason to stay, since people seem to prefer it.

**Comment by thedocruby** [comment]
@henkelmax The only reason people prefer it is because just the name of your mod implies that my mod is no longer maintained, which is honeslty fraud. If you look on the curseforge, the discord, and anywhere else, you will see that people who use my mod generally accept that it is better than yours. I can't help that people assume that your mod is better even though it is obsolete. I ask that you please see it from my point of view and realize that I work hard daily to make this mod the best it can be only to have my work ignored because of an old fork with a cool name. Again, I realize that you did put a lot of work into this, that is why I think it is only fair that you continue to provide a forge version, but please understand that the reason you are defending your mod is the same logic I am using to defend mine.

**Comment by henkelmax** [comment]
Why do you always call it obsolete?
It is working perfectly fine.
I am also not having any of your code in my repository, so it doesn't take any of your work. And honestly it is also barely using any of vlads code. The most important parts are still from sonic ether.

And calling it fraud is really rude. It is just stated that the original version is not optimized for voice chat.

**Comment by thedocruby** [comment]
Okay, you're right. I got overly frustrated for no good reason, and i sincerely apologize that i insulted your work with that frustration. Might i suggest at least a name change, to more accurately reflect the mod's true nature as you stated it:
> This is just a fork optimized for simple voice chat.
So maybe "Sound Physics Remastered" is at least a bit misleading, don't you agree? Maybe one of the folloing might suit it better:
- Sound Physics for Voice
- Sound Physics SVC
- Sound Physics Voice
- Sound Physics + Voice
Or maybe a more creative and original name, like these:
- Vocalized
- Sound Physics: Vocalized
- Virtual Voice
- Voxel Voice
- Voice Voxels
At this point I've given up on fighting you, and I'm just trying to help you improve like any other contributor. I hope you can see that now, and I apologize again for demeaning you with my harsh accusations of fraud and malevolence. That was a rash move and I should never have outburst like that. I hope you con forgive me.

Thanks,
~ Doc
