### ISSUE TITLE
UI Sounds muffled/affected by physics

### ISSUE THREAD

**Issue by emoace** [henkelmax/sound-physics-remastered#3]
**Bug description**
GUI sounds are muffled and/or respond to physics

**Steps to reproduce the issue**
1. Start the Game
2. Play for a bit
3. Enter the main menu
4. Click on buttons, you will hear that the click sounds are muffled

**Expected behavior**
Sounds that are out of gameplay would be unaffected by physics

**Log files**
https://gist.github.com/emoace/af14340053a08f84564009830aa9d74f

**Versions**
- Minecraft version 1.17.1
- Forge/Fabric version 11.7
- Mod version 1.0.1

**Other mods**
https://gist.github.com/emoace/bc47c1e3496e96a47098852609ec017f

**Comment by henkelmax** [comment]
Does this happen without any other mods?

**Comment by emoace** [comment]
https://github.com/henkelmax/sound-physics-remastered/issues/4

It does not happen with any other mods, Sound Physics works as intended.  The problem seems to be with another mod.
