### ISSUE TITLE
Horrible Performance

### ISSUE THREAD

**Issue by UltraBlackLinux** [henkelmax/sound-physics-remastered#32]
**Bug description**
This mod causes a lot of lag spikes: https://spark.lucko.me/3Kd6jS8inA
![2022-02-13_19-33](https://user-images.githubusercontent.com/62404294/153769405-15ad1e30-bd72-4a68-bdcb-1136f438d783.png)

**Steps to reproduce the issue**
... Just play

**Log files**
no errors in sight

**Versions**
- Minecraft version 1.18.1
- Fabric version 0.10.2
- Mod version 1.18.1

**Other mods**
I'm not quite sure, as the problem disappeared while I was remaining with two mods in the brute force stage, but it's either Smooth boot or TieFix

**Comment by UltraBlackLinux** [comment]
> Did you test the performance without sound physics? What happens if you just use sound physics?

Yes I did test the performance without sound physics and I wasn't (!) facing these lagspikes anymore.

**Comment by henkelmax** [comment]
Can you narrow down the mod that causes the issue with sound physics?

**Comment by UltraBlackLinux** [comment]
> Can you narrow down the mod that causes the issue with sound physics?

Again, it's either TieFix or Smooth Boot. The problem has since disappeared for some obscure reason, but maybe you can reproduce the same thing with one of these mods

**Comment by henkelmax** [comment]
Tested it with your mods and it works perfectly fine.
Since it's not happening for you anymore I would say I'll close the issue and if it happens again, you can just reopen it again.
