### ISSUE TITLE
Quark Mod + SPR causes crash when feeding Toretoise glowberries using the feeding trough 

### ISSUE THREAD

**Issue by Flyte-less** [henkelmax/sound-physics-remastered#37]
**Bug description**
The toretoise is a mob from quark that spawns underground and generates ores on it's back. The feeding trough is a block from the same mod that can be filled with food and feeds mobs around it automatically. Quark allows the feeding of toretoises using glowberries and supports the use of the feeding trough as well. Using this functionality while the sound physics remastered mod is loaded causes a game crash. Other mobs do not seem to be affected and the trough functions as intended for them.

**Steps to reproduce the issue**
1. Load a forge instance with Quark and Sound Physics Remastered loaded.
2. Create a new creative mode world.
3. Place a feeding trough on the ground and right click to add glowberries to it's inventory.
4. Spawn Toretoise right beside trough and wait for it to eat

**Expected behavior**
The game should not crash when the toretoise consumes a glowberry via a trough. This behavior is present when Sound Physics Remastered is not loaded.

**Log files**
https://gist.github.com/Flyte-less/11c5fec647f43b4ef4a765a704cf65c4

**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.0
- Mod version 1.18.2-1.0.5

**Other mods**
Only Quark and a required library for Quark were installed.
- Quark 3.2-353
- AutoRegLib 1.7-53

**Comment by henkelmax** [comment]
Should be fixed in the next version. But I strongly recommend reporting this issue to quark aswell, since no mod should play a sound that's `null`
