### ISSUE TITLE
Something is repeatedly wrong within the log

### ISSUE THREAD

**Issue by NealSavage** [henkelmax/sound-physics-remastered#38]
I don't know how to read minecraft logs and console outputs, and I don't know what it's doing, I really wish I could be more helpful.
https://pastebin.com/BfriRc00
Here's the section of the Multi MC console output that was fixed by me deleting the mod. It would constantly be spamming that, like, once every.. 5, 10 seconds.
The biggest possibility of a cause I can think of is that I have presence footsteps as well.

**Comment by henkelmax** [comment]
Please properly fill out the bug template and provide the full logs.

**Comment by NealSavage** [comment]
I gave you all the information that I do have. Aren't logs for when crashing, not general gameplay that has a severe problem but has not fully crashed?

**Comment by NealSavage** [comment]
Also, your template literally says do not paste the entire logs...?

**Comment by NealSavage** [comment]
I tried but the logs are too long for pastebin, I don't understand your website provided, and the new issue thing says it's too long if i paste it directly in. What do?

**Comment by NealSavage** [comment]
I'll just give some of the template information here. I'm on minecraft 1.18.2 fabric and the mod version is 1.0.5 I don't know the steps needed to produce.

**Comment by NealSavage** [comment]
My mods folder says it has 189 items in it
