### ISSUE TITLE
Publish to Modrinth

### ISSUE THREAD

**Issue by Brawaru** [henkelmax/sound-physics-remastered#39]
**Is your feature request related to a problem? Please describe.**

CurseForge has started enforcing third-party downloads restrictions which sparkled a lot of controversy and fights in Minecraft modding community, so people started looking for alternatives to CurseForge. One of these alternatives that gaining traction is Modrinth. Simple Voice Chat mod is already present over there (thanks for adding it, btw!), but Sound Physics Remastered is not, which is quite sad, because both mods make an amazing combo.

**Describe the solution you'd like**

It'd be cool if both mods were present on Modrinth. I know you were hesitant to publish Simple Voice Chat to Modrinth due to lack of monetisation options, which is very understandable, but you seem to have changed your mind since then, so maybe you can post Sound Physics Remastered there too, please? (. ❛ ᴗ ❛.) Or at least consider it when they add monetisation (they say they plan on it soon™).

**Describe alternatives you've considered**

- **Using CurseForge as is**. This might be an option for some, but I now quite afraid about empowering Overwolf and CurseForge any more knowing how badly they treat their own community, as shown by this enforcement before their launcher was even available on Linux, how they threatened launchers like PolyMC over guessing CDN link from project and file IDs.
- **Downloading mod manually**. This is possible with tools like packwiz (though not auto-updating), but not possible if you're posting a mod pack on Modrinth, for example, since there only so many domains they allow. Redistributing mod JAR in overrides would be a douche move and most probably not allowed.
- **Using other mod like this**. I know one but it's bad performance-wise and also not compatible with Simple Voice Chat.
- **Not using mod**. But.. but... it's so good to miss out on. T_T

**Additional context**

× none; but thank you for working on these projects, they truly are amazing additions to Minecraft experience (´▽`ʃ♡ƪ)

**Comment by henkelmax** [comment]
https://modrinth.com/mod/sound-physics-remastered
