### ISSUE TITLE
Extra Sounds' Inventory Sounds muffled/affected by physics

### ISSUE THREAD

**Issue by emoace** [henkelmax/sound-physics-remastered#4]
**Bug description**

**Steps to reproduce the issue**
1. Start the Game
2. Play for a bit
3. Open inventory
4. Move items around, you will hear that the sounds are muffled

**Expected behavior**
These sounds would appear to be unaffected by physics and/or they would be in close proximity to the player

**Log files**
https://gist.github.com/emoace/465503ea92ae6a1bda3aa1f916dc4be7

**Versions**
- Minecraft version 1.17.1
- Forge/Fabric version 0.11.7
- Mod version 1.0.1

**Other mods**
https://gist.github.com/emoace/bc47c1e3496e96a47098852609ec017f

**Comment by henkelmax** [comment]
There is noting do about that. The mod plays these sounds as a positioned sound in the world. Sound physics behaves exactly as it should. Maybe report this issue to their bug tracker.

Here's an example from extra sounds UI sound:
`On play sound - Source ID: 10 136.79202768323617, 15.0, 95.07857741307448 	Sound category: PLAYERS 	Sound name: block.note_block.hat`

And that's a vanilla Minecraft UI sound:
`On play sound - Source ID: 1 0.0, 0.0, 0.0 	Sound category: MASTER 	Sound name: ui.button.click`

As you can see; UI sounds shouldn't get played at a specific location.

**Comment by emoace** [comment]
I've done some testing and it seems that it is not Sound Physics, Extra Sounds, Simple Voice Chat, nor Charmonium.

Yes Sound Physics works as intended with no other mods, it even works as intended with Extra Sounds.  Not sure what is causing the issue but I'll close this.  Me and my friends are loving the mod on our server btw!
