### ISSUE TITLE
CurseForge missing 1.0.6 version for Fabric

### ISSUE THREAD

**Issue by PweSol** [henkelmax/sound-physics-remastered#40]
**Bug description**
There are only 1.0.6 latest builds for Forge and not for Fabric, I successfully built 1.0.6 version for Fabric from source and it's working fine. Are the new changes relevant only for the Forge version?

**Steps to reproduce the issue**
1. Go to https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered
2. No 1.0.6 version for Fabric (1.18.2). Only 1.0.5 when browsing the [Files](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered/files) tab

**Expected behavior**
1.0.6 version for Fabric?

**Log files**
N/A

**Versions**
- Minecraft version 1.18.2
- Fabric version N/A
- Mod version 1.0.6

**Other mods**
N/A

**Screenshots (Optional)**
[here](https://files.catbox.moe/alxteg.png) and [here](https://files.catbox.moe/6hdvj7.png)

**Comment by PweSol** [comment]
One more thing. The version compatibility is labeled to be 1.18.1. But I've been using it on 1.18.2 for a long time so it's most likely compatible and should probably be marked as such as well.

**Comment by henkelmax** [comment]
I didn't change anything

**Comment by PweSol** [comment]
Really? The page was showing "Game Version: 1.18.1" and the file that I downloaded is also also named 1.18.1. But now I refreshed it and it's showing as 1.18.2, including the file. Although there seems to be now two files; for 1.18.1 and 1.18.2.

But it's not an issue anymore so whatever.

**Comment by henkelmax** [comment]
I uploaded 1.17.1, 1.18.1 and 1.18.2
Each file takes a while to get approved by curse, as I already said.
