### ISSUE TITLE
Error in latest.log

### ISSUE THREAD

**Issue by NoShotz** [henkelmax/sound-physics-remastered#44]
**Bug description**
There is an error in the latest.log file

**Steps to reproduce the issue**
Start the game

**Expected behavior**
No error in latest.log file

**Log files**
https://pastebin.com/XEufE61w

**Versions**
- Minecraft version 1.19
- Forge/Fabric version 41.0.45
- Mod version 1.0.6

**Other mods**
3dskinlayers-forge-1.4.7-mc1.19
additionalredstone-1.19-1.0.3
AdvancementPlaques-1.19-1.4.4
AI-Improvements-1.19-0.5.0
appleskin-forge-mc1.19-2.4.0
Aquaculture-1.19-2.4.1
architectury-5.7.27-forge
areas_1.19.0-2.9
armorpointspp-forge-1.19-3.0.4
AttributeFix-Forge-1.19-15.0.1
autoplant-1.19-1.0.0
auudio_forge_1.0.3_MC_1.19
balm-4.2.0
beenfo-1.19-forge41.0.17-1.2
betteranimalmodels-1.19-5.6.0-forge
betteranimalsplus-1.19-11.0.6-forge
betterbiomeblend-1.19.0-1.3.6-forge
BetterCompatibilityChecker-1.0.1-build.28+mc1.19
BetterF3-1.3.1-Forge-1.19
bettermending-forge-1.1.2+1.19
BetterPingDisplay-1.19-1.1
BetterThirdPerson-Forge-1.19-1.8.1
BiomesOPlenty-1.19-17.0.0.136
blockui-1.19-0.0.52-ALPHA
Bookshelf-Forge-1.19-14.0.5
BorderlessWindow-1.19-1.5.0
caelus-forge-1.19-3.0.0.3
catalogue-1.6.1-1.19
chat_heads-0.6.0-forge-1.19
clear-skies-forge-mc119-2.0.94
clickadv-1.19-2.5
cloth-config-7.0.72-forge
Clumps-forge-1.19-9.0.0+3
collective-1.19.0-4.28
configured-1.5.3-1.19
Controlling-forge-1.19-10.0+1
Copperized-1.19-2.3
corail_woodcutter-1.19-2.4.0
corpse-1.19-1.0.4
Craftable Horse Armour  Saddle-1.19-1.9
craftingtweaks-forge-1.19-15.0.0
CreativeCore_FORGE_v2.7.1_mc1.19
curios-forge-1.19-5.1.0.2
customsignposts-1.19-1.0.1
cyanide-forge-1.19-3.0.0
debugify-2.2.0-forge-1.19
DeLogger-4.1.0-build.5+mc1.19
drippyloadingscreen_forge_1.6.4_MC_1.19
durabilitytooltip-1.1.1-forge-mc1.19
Durabuilt1.19(Forge)vs1.0.2
dyed-forge-1.19-1.0.2
dynamic_asset_generator-forge-1.19-0.6.4
dynamiclights-1.19.1
EnchantmentDescriptions-Forge-1.19-11.0.4
Enhanced-Farming-1.19-1.4.3
entityculling-forge-1.5.2-mc1.19
EquipmentCompare-1.19-1.3.0
erodingstoneentities_1.19.0-2.5
excavated_variants-forge-1.19-0.6.3
Fallingleaves-1.19-1.3.0-alpha+20220611-1631
fancymenu_forge_2.8.0_MC_1.19
ferritecore-5.0.0-forge
firstperson-forge-2.1.0-mc1.19
flatbedrock-1.4.3-build.11+mc1.19
fm_audio_extension_forge_1.1.0_MC_1.19
goblintraders-1.7.2-1.19
handoveryouritems_1.19.0-1.4
hiddenrecipebook_1.19.0-2.4
hourglass-1.19-1.2.1.0
Iceberg-1.19-1.0.44
incontrol-1.19-7.0.0
inventoryessentials-forge-1.19-5.0.0
ItemPhysic_FORGE_v1.6.1_mc1.19
jei-1.19-forge-11.0.0.206
JustEnoughProfessions-forge-1.19-2.0.0
kleeslabs-forge-1.19-12.0.0
konkrete_forge_1.3.3_MC_1.19
krypton-0.2.0
kubejs-forge-1900.5.5-build.16
lazydfu-1.0-1.19+
LegendaryTooltips-1.19-1.2.5
LibX-1.19-4.0.3
loadmyresources_1.0.1_MC_1.19
macawsbridgesbop-1.19-1.0
macawsroofsbop-1.19-1.0
MaxHealthFix-Forge-1.19-6.0.1
mcw-bridges-2.0.3-mc1.19
mcw-fences-1.0.5-mc1.19
mcw-furniture-3.0.0-mc1.19
mcw-lights-1.0.3-mc1.19
mcw-paintings-1.0.3-mc1.19
mcw-paths-1.0.0-mc1.19
mcw-roofs-2.1.2-mc1.19
mcw-trapdoors-1.0.5-mc1.19
mcw-windows-2.0.3-mc1.19
mcwfencesbop-1.19-1.1
mcwifipnp-1.5.6-1.19-forge
modernworldcreation_forge_1.0.0_MC_1.19
morevillagers-forge-1.19-4.0.1
MouseTweaks-forge-mc1.19-2.22
multi-piston-1.19-1.2.11-ALPHA
NekosEnchantedBooks-1.19-1.7.0
netherportalfix-forge-1.19-10.0.0
netherportalspread_1.19.0-5.7
notenoughanimations-forge-1.6.0-mc1.19
notenoughcrashes-4.1.6+1.19-forge
NyfsQuiver-1.19-0.7.1
oculus-mc1.19-1.2.5
radon-0.8.2
randomvillagenames_1.19.0-1.6
rhino-forge-1802.1.14-build.186
rubidium-0.6.0a
SereneSeasons-1.19-8.0.0.17
shutupexperimentalsettings-1.0.5
smallernetherportals_1.19.0-1.9
smoothboot-mc1.19-1.0.1
snowundertrees-1.19-1.2.1
soundphysics-forge-1.19-1.0.6
structurize-1.19-1.0.417-ALPHA
sulfurpotassiummod-1.19-2.3.3+Forge
supermartijn642configlib-1.1.4-forge-mc1.19
TerraBlender-forge-1.19-2.0.0.113
ToolBelt-1.19-1.19.0
trashslot-forge-1.19-12.0.0
treeharvester_1.19.0-5.1
uiinputundo-1.2
villagebellrecipe_1.19.0-1.4
villagernames_1.19.0-3.5
villagespawnpoint_1.19.0-1.9
waveycapes-forge-1.2.0-mc1.19
whats-that-slot-forge-1.3.0+1.19
WorldHandler-1.19-3.1.3
xptome-1.19-2.1.5

**Comment by henkelmax** [comment]
Please post the full logs of that session and also please try if that also happens without any other mods installed.

**Comment by henkelmax** [comment]
Alright, can you please narrow down which mod in combination with soundphysics is causing the error?

**Comment by NoShotz** [comment]
Considering this appears in the error I'm guessing this mod
`at de.keksuccino.drippyloadingscreen.customization.items.v2.audio.ACIHandler.onRenderOverlay(ACIHandler.java:67) ~[drippyloadingscreen_forge_1.6.4_MC_1.19.jar%23190!/:1.0.0]`

Will confirm in a bit

**Comment by NoShotz** [comment]
Yep, [this mod](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen) is causing the issue

**Comment by henkelmax** [comment]
Alright, that mod is causing sound physics code to be invoked before it being initialized. It's never a good idea to do custom stuff in the loading screen. 

This will be a wontfix, sorry.

**Comment by NoShotz** [comment]
No problem, I'll just keep that setting disabled as I wasn't using that setting anyways.
