### ISSUE TITLE
What does HRTF in 1.19 mean for the future of this project?

### ISSUE THREAD

**Issue by iblowmymind** [henkelmax/sound-physics-remastered#45]
Hello,

As you might now, 1.19 introduced a Directional Audio (HRTF) feature available in Audio Settings. What does this feature mean for the future of Sound Physics Remastered, does it conflict with any of the features available within the mod, and should I enable it when SPR is installed?

**Comment by henkelmax** [comment]
It doesn't conflict with anything.
Besides that, HRTF doesn't even work in 1.19: https://bugs.mojang.com/browse/MC-249275

**Comment by iblowmymind** [comment]
Weird. When I turn it on my audio output slightly decreases and I can actually differentiate spatial planes as I should. Which would indicate it's maybe working?

**Comment by henkelmax** [comment]
At least on windows it doesn't (In 99% of all cases). But this thread is not there to discuss about that.

**Comment by iblowmymind** [comment]
True, thanks for the reply anyway!
