### ISSUE TITLE
Sounds that start far away remain attenuated even when approaching the source

### ISSUE THREAD

**Issue by Ethiarpus** [henkelmax/sound-physics-remastered#47]
**Bug description**
When a long sound is started from behind a wall or corner, it does not de-attenuate properly (high-ends stay damped) when you approach the source of the noise

**Steps to reproduce the issue**
1. Find or make a cave-like structure.
2. Note your current coordinates
3. run `/playsound minecraft:music_disc.pigstep ambient @a [coordinates] `
4. Move behind a corner and notice that the sound continues to play in a way that sounds physically accurate: Low-ends travel through the rock and high-ends are only audible in echoes off the walls
5. Stop all sounds
6. Run the same command again, with the same coordinates as before, but *remain standing behind the corner*: `/playsound minecraft:music_disc.pigstep ambient @a [coordinates]`
7. Notice that the high-end is no longer echoing off the walls
8. Approach the source of the sound

**Expected behavior**
Sound attenutation should be updated periodically as the player moves around in the world

**Log files**
N/A; no crash report

**Versions**
- Minecraft version: 1.19.0
- Forge/Fabric version: Fabric 0.14.8
- Mod version: `soundphysics-fabric-1.19-1.0.6.jar`

**Other mods**
```
architectury-5.7.28-fabric.jar  kubejs-fabric-1900.5.5-build.27.jar   SimpleDiscordLink-fabric-1.19-1.3.0.jar  
cloth-config-7.0.72-fabric.jar  lithium-fabric-mc1.19-0.8.0.jar       soundphysics-fabric-1.19-1.0.6.jar
entitymodifiers-1.2.0.jar       phosphor-fabric-mc1.19.x-0.8.1.jar    textile_backup-2.4.0-1.19.jar
fabric-api-0.57.0+1.19.jar      rhino-fabric-1802.1.14-build.190.jar  voicechat-fabric-1.19-2.2.47.jar
worldedit-mod-7.2.11-beta-01.jar
```

**Comment by PixelatedBruh** [comment]
Any chance of this being looked into again. Discs still have no reverb with moving sounds enabled.
