### ISSUE TITLE
Does Sound Physics Effects Performance? | Is there a config for low-end PCs?

### ISSUE THREAD

**Issue by Rajbir98** [henkelmax/sound-physics-remastered#51]
**Question**
Does Sound Physics Effects Performance?
Is there a config for low-end PCs?

**Request**
Please provide me with a low-end PC config
Please remove the "bug" label

**Comment by henkelmax** [comment]
Install cloth config and adjust the performance settings.

**Comment by henkelmax** [comment]
Also please don't use bug reports for questions.
