### ISSUE TITLE
Cloth Config Not showing

### ISSUE THREAD

**Issue by HummusOverlord** [henkelmax/sound-physics-remastered#53]
Bug Description: With Cloth Config and Mod Menu both installed, the config menu for soundphysics is still not showing, however other mod's config menu do show. 

Fabric verions: 0.11.0. 
MC version: 1.19
Mod version 1.0.11

Cloth config version: 7.073

No other  mods instaled besides necessary fabric mods etc

**Comment by henkelmax** [comment]
> Fabric verions: 0.11.0.

You need at least Fabric loader `0.14.6` for the 1.19 version of the mod.
You also need ModMenu to open the config GUI.
