### ISSUE TITLE
when updated to 1.19.1, my framerates in nether started droping to 1 fps. 

### ISSUE THREAD

**Issue by twojamama1** [henkelmax/sound-physics-remastered#55]
when 1.19.1 came out i updated this mod from 1.19 to 1.19.1 and my framerates in nether started droping to 1 fps. without this mod minecraft works normally and i have abaut 100 fps. please fix this (p.s. it was on newest version of forge and on minecraft version 1.19.1)

Thats all i have.

**Comment by henkelmax** [comment]
Please fill out the bug template and provide logs.

**Comment by twojamama1** [comment]
ok but minecraft didnt crash so how i am going to upload logs?

**Comment by henkelmax** [comment]
Logs are always there. You might be thinking of crash reports.

**Comment by twojamama1** [comment]
**Bug description**
when 1.19.1 came out i updated this mod from 1.19 to 1.19.1 and my framerates in nether started droping to 1 fps. without this mod minecraft works normally and i have abaut 100 fps.

**Steps to reproduce the issue**
1. Go to nether.
2. See error

**Log files**
Where do i find logs?

**Versions**
- Minecraft version 1.19.1
- Forge version 42.0.1
- Mod version 1.0.11

**Other mods**
Ambient Sounds
Bookshelf
Catalouge
Configured
CreativeCore
DynamicLights
EnchantmentDescriptions
Jade
Jei
Just Zoom
Konkrete
MusicPlayer
Oculus
Rubidium
U Team Core
Xaero's Minimap
Xaero's World Map
(I tested without other mods if this issiue still appears and yes it still appears without other mods)
 
**Screenshots**
https://cdn.discordapp.com/attachments/915232532918841404/1002989181099855912/unknown.png

**Comment by henkelmax** [comment]
does this also happen without ambient sounds?
Also, don't forget the logs.

**Comment by twojamama1** [comment]
yes it happens without ambients sounds.
logs... where do i find them? becaouse idk i am reporting a bug like this for the first time

**Comment by henkelmax** [comment]
`logs/latest.log`

**Comment by twojamama1** [comment]
ok! wait a moment.

**Comment by twojamama1** [comment]
when i created this log i only had sound physics running
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/9227043/latest.log)

**Comment by henkelmax** [comment]
Nothing unusual in the logs...
I'm trying to reproduce it myself.

**Comment by twojamama1** [comment]
but this log was made when I had all my mods on
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/9227049/latest.log)

**Comment by twojamama1** [comment]
ok. i am wating

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/181935897-e5b78b54-9b89-4d33-a83b-9689a5c02b70.png)

I'm getting the usual frame rates.
Just to double check, can you try running your game without any mods?
Can you also try joining a new world?

**Comment by twojamama1** [comment]
i checked without any mods 10 times and still the same and ok i'm gonna do the new world

**Comment by henkelmax** [comment]
> i checked without any mods 10 times and still the same and ok i'm gonna do the new world

So it happens without sound physics aswell?

**Comment by twojamama1** [comment]
yes

**Comment by henkelmax** [comment]
Then it isn't an issue of the sound physics mod.

**Comment by twojamama1** [comment]
wait no no

**Comment by twojamama1** [comment]
without sound physics it dosent happend

**Comment by twojamama1** [comment]
I was wrong

**Comment by twojamama1** [comment]
can you come back???

**Comment by henkelmax** [comment]
Calm down!

Did you use the same version back in 1.19?

**Comment by twojamama1** [comment]
The same version of mod? i think no

**Comment by henkelmax** [comment]
Can you try that?

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/181936449-515156be-eddc-48d5-a418-9890be6ad823.png)
Also tried it in the nether btw. Also no frame drops.

**Comment by twojamama1** [comment]
i just checked and on new world it dosent happen

**Comment by henkelmax** [comment]
Weird. You might want to tone down the performance settings in the config menu. If you have many sound sources, it might be a little bit too heavy for lower spec pcs.

**Comment by twojamama1** [comment]
my pereformance settings is on medium and my pc specs is really good

**Comment by twojamama1** [comment]
its 2 years old computer

**Comment by henkelmax** [comment]
Medium? I'm talking about the sound physics settings.

**Comment by twojamama1** [comment]
wait. there is one??

**Comment by twojamama1** [comment]
where????

**Comment by henkelmax** [comment]
Either in the config, or via cloth config.

Just install cloth config for forge and click on the config button in the mods menu on the title screen.

**Comment by twojamama1** [comment]
i have something familliar called ,,configured" and i dont have the config button
![image](https://user-images.githubusercontent.com/110301374/181936746-0309cd16-f6b4-4162-8993-6392d30df343.png)

**Comment by twojamama1** [comment]
but in other mods (like jade) i have the config button.

![image](https://user-images.githubusercontent.com/110301374/181936782-2d27a193-9167-4952-a627-065cba6aba18.png)

**Comment by henkelmax** [comment]
It won't work without cloth config.

**Comment by twojamama1** [comment]
ok i gonna try (p.s. sorry for my bad english but i live in poland. i am trying my best)

**Comment by twojamama1** [comment]
what do i do now?
![image](https://user-images.githubusercontent.com/110301374/181936961-ece91a97-3f02-49a3-ba67-869aadf6f1b3.png)

**Comment by henkelmax** [comment]
Go to performance and set 
- environment evaluation ray count to 16
- environment evaluation ray bounces to 2
- maximum occlusion rays to 8
- sound direction evaluation to no
- and redirect non occluded sounds to no


that should be better for performance

**Comment by twojamama1** [comment]
i did that and its still happening
i have an idea. maybe i will send you link to my save and you will check why its happening?

**Comment by henkelmax** [comment]
I don't have the time for that. It looks like a performance issues. Just avoid a lot of sounds.

**Comment by twojamama1** [comment]
but its happening all over the nether

**Comment by twojamama1** [comment]
what is happening. why its happening only on my world

**Comment by twojamama1** [comment]
i think i found what is causing this problem. When something is triggering an echo or something associated with sound physics it creates a lag spike and because there are a lot of sounds in the nether it creates a lot of lag

**Comment by twojamama1** [comment]
and on the new world there was still a lige spike but less becouse this was new world

**Comment by twojamama1** [comment]
i just asked my friend if he have the same problem with lag spickes on this version and he said yes. this proves it's the fault of some fashion bug causing lag spickes

**Comment by henkelmax** [comment]
If you found a way to reliably reproduce the bug, let me know and I'll reopen the issue.

**Comment by twojamama1** [comment]
i cant find anything. i tried so many ways and nothing is working. i think that you need to repair this in next update. i know that its happening becouse of lag spickes and it cant be fixed without fumbling in the code of this mod.

**Comment by twojamama1** [comment]
i am waiting for the next update. if this not get fixed i am reopening this

**Comment by henkelmax** [comment]
It won't get fixed if I can't reproduce it. I can't fix a bug that I can't reproduce!
