### ISSUE TITLE
Large performace drop from 1.19 to 1.19.1 when experiencing many sounds.

### ISSUE THREAD

**Issue by Dahkahtah** [henkelmax/sound-physics-remastered#56]
Apologies if this is not considered a bug or if this is merely a result of changes on Mojang's side.

**Bug description**
Performance (specifically FPS) has been reduced between recent versions of the mod, noticed around large piston-based redstone machine and recreated using a large array of noteblocks

This can be mitigated by using Mod Menu & Cloth Config to change the settings to reduce performance impact in 1.19.1, but I thought it worthwhile to document the difference in the mod's performance nonetheless.

**Steps to reproduce the issue**
You can view my video to view the exact process I used to produce this issue, though I'm sure the effects will vary by computer.
https://youtu.be/3OPNwm-MUtU
(Timestamps for when the worlds load are in the pinned comment)
1. Create a scenario where minecraft is producing many sounds at once
2. Compare performance between version 1.0.6 for 1.19 and 1.0.11 for 1.19.1

**Log files**
[1.19 log file](https://gist.github.com/Dahkahtah/9b3a931cd27061a975e5a68f899dc5cf)
[1.19.1 log file](https://gist.github.com/Dahkahtah/5bfd37c3114774ea47b812d5e0e4c0b7)

**Versions**
- Minecraft version: 1.19.1
   - Forge/Fabric version: 0.14.8
   - Mod version: 1.0.11
- Minecraft version: 1.19
   - Forge/Fabric version: 0.14.8
   - Mod version: 1.0.6

**Other mods**
No other mods were installed.

**Screenshots (Optional)**
Here are two screenshots (from the video mentioned above) that show performance differences between the two versions

1.19.1/1.0.11 F3 Menu:
![1.19.1/1.0.11 F3 Menu](https://user-images.githubusercontent.com/63128704/183147209-3d1a93c0-f420-4d94-ac90-69b03d4d5209.png)

1.19/1.0.6 F3 Menu:
![1.19/1.0.6 F3 Menu](https://user-images.githubusercontent.com/63128704/183147147-566b8dbb-3a90-4e07-8bbe-3fe5a925f701.png)

**End Note**
I fell in love with the mod when I was first recommended it when playing on a server with voice chat, experiencing the reverberation makes caving in this game much more rich and immersive.  I appreciate all the work you do to maintain and update it!

**Comment by henkelmax** [comment]
Does this also happen in 1.19-1.0.11?

**Comment by Dahkahtah** [comment]
Yes, 1.19-1.0.11 also has reduced performance
1.19-1.0.10 does not
![vlcsnap-2022-08-05-13h04m01s222](https://user-images.githubusercontent.com/63128704/183153643-82c83a6b-5634-4c90-9924-6fb4841ef5b2.png)

**Comment by henkelmax** [comment]
Alright, thanks for letting me know. I'll look into it.

**Comment by henkelmax** [comment]
I can't really see any difference between those versions...

1.19-1.0.10
![image](https://user-images.githubusercontent.com/13237524/183242013-5ab4d8c4-db50-4da8-98a9-5af02853181e.png)


1.19.1-1.0.11
![image](https://user-images.githubusercontent.com/13237524/183241932-c292ff71-5ade-4581-8b3e-5d09d2c895a9.png)

**Comment by Dahkahtah** [comment]
Strange, thanks for looking into it.  I'll try to isolate what else could be causing this issue on my device.

**Comment by henkelmax** [comment]
Your issue might be related to #57. Please try if it still happens with version 1.0.12

**Comment by The-L3mur** [comment]
Can also reproduce. 1.0.10 has no lag, but 1.10.11 and onwards do.

Tested on 1.19, fabric 0.14.9, and mod versions 1.0.10 and 1.0.13. No other mods installed.

**Comment by Disguys** [comment]
It is also felt especially strongly on farms, there are no special drawdowns at 1.19, but at 1.19.2 fps sagging to 1.

1.19 with Sound Physics Remastered 1.0.10 - https://youtu.be/JSsNP7QlFRM
1.19.2 with Sound Physics Remastered 1.0.13 - https://youtu.be/FU6DkZU4QQ4

**Comment by henkelmax** [comment]
I might have found the cause. Please update to 1.0.14 and disable this config option:

![image](https://user-images.githubusercontent.com/13237524/185551504-3e4d7324-b768-4bf9-9d11-28e30d9b2357.png)

**Comment by Disguys** [comment]
Yea, it works, thanks.
Maybe it would be better to disable this default parameter in fashion?

**Comment by henkelmax** [comment]
I'm gonna work on a proper fix
