### ISSUE TITLE
[BUG] Muffles and distorts the sound of Thunder

### ISSUE THREAD

**Issue by Tsoccerguy3** [henkelmax/sound-physics-remastered#59]
**Bug description**

Thunder is muffled and distorted , not realistic . Thunder sound is already directional and has already built in effects from recording actual thunder from storm and lightning strikes . Maybe bypass the filters with the thunder sound and do not cull . If you figure out a way to make it better than it is that would be good , As it is it sounds weird

**Comment by henkelmax** [comment]
Please fill out the bug template properly.

**Comment by henkelmax** [comment]
https://github.com/henkelmax/sound-physics-remastered/blob/e83fa966e53c8d93756824a7614375cd07a0a114/common/src/main/java/com/sonicether/soundphysics/config/AllowedSoundConfig.java#L103

Already is disabled.

**Comment by Tsoccerguy3** [comment]
I mean no disrespect. On Neoforge 1.21.7 with the current commit , Thunder gets disabled. I see the lightning . Tested with just the mod and no resource packs. It can work randomly but something is defiantly wrong. This happens on our server. Paper 1.21.7 build 26. Maybe different packets are sent for thunder , Neoforge vs Paper, Spigot.

All I can do is allow you to test on our server. Resource pack will auto download.
proteus.fragify.net:25575

/warp GoldenCity
Test with the mod only and with out the mod. 
Leave the ship , walk down the dock , there are gold blocks that will take you down though the ruins. exit the ruins and begin walking across the large sandstone bridge towards the city, There is a trigger there that will start the lightning effect. It will trigger again when you leave the bridge .

**Comment by Tsoccerguy3** [comment]
Tested with 1.21.8 Neoforge and only sound-physics-remastered. It is still silencing thunder . The trigger blocks are hidden underground and the craftbook plugin on our server handles them. I guess the Paper packets that are sent to the client include x,y,z location and SP is processing this sound event as underground. I guess thunder sound event is being still processed even though you have it disabled, something is still active.

**Comment by henkelmax** [comment]
Did you make sure to reset your config?
Did you try with the mod installed on the server?

**Comment by henkelmax** [comment]
If you have a mod that changes how sounds are played, the mod won't detect it as weather sounds.

**Comment by henkelmax** [comment]
Ok, this seems to be a bug in minecraft:
https://bugs.mojang.com/browse/MC/issues/MC-46634
It seems that thunder wasn't treated as weather sound.
It will be fixed in the next minecraft release.
