### ISSUE TITLE
Help with sound blacklist regex / limit the number of sounds that could be played at the same time

### ISSUE THREAD

**Issue by Shepiock** [henkelmax/sound-physics-remastered#60]
**Is your feature request related to a problem? Please describe.**
I wanted to disable the sound of the pigmens, because when too many of them are aggroing me in the nether, the performance starts to drop seriously due to the reverberation and the large number of sounds.

**Describe the solution you'd like**
I would like to better understand how to add a sound to the blacklist, and why not add an option to limit the number of sounds that could be played at the same time with the effects to help regain performance? Or at least a quick shortcut to disable Sound Physics to save fps when it gets to laggy

**Additional context**
In the nether, especially because of the Amplified Nether datapack, the nether is a huge resonance chamber and that's why when a lot of sounds are played at the same time, the performance drops to the point where it becomes unplayable. Other than that, I haven't had to deal with this problem while playing normally: without doing farms with a lot of entities.

**Comment by henkelmax** [comment]
For regexes, I generally recommend
https://regex101.com/
and
https://www.debuggex.com/

You basically just need to configure your regex that it matches the sound ID.
This is the default regex for example: `(.*rain.*)|(.*lightning_bolt.*)`.
The first part filters everything that has the word `rain` in the sound ID.
The second one everything with `lightning_bolt` in the ID

You can find out the sound ids by looking at the suggestions in the `/playound` command.
![image](https://user-images.githubusercontent.com/13237524/185311594-24385293-69d0-4f78-818a-221b5bd61f1e.png)

![image](https://user-images.githubusercontent.com/13237524/185312042-b332d983-faea-4c48-bbcd-ecfc43e9a214.png)

These for example are the ids for pigmen sounds, you could remove them by adding `(.*zombified_piglin.*)` to the regex.
