### ISSUE TITLE
No Sound when using Open JDK 17 (prereq/documentation bug?)

### ISSUE THREAD

**Issue by BrainSlugs83** [henkelmax/sound-physics-remastered#61]
**Bug description**

When using the MS Build of Open JDK 17 (x64), if the mod is installed; with the default configuration -- I get no sound outside of the menus.

When using Oracle JDK 18, if the mod is installed; with the default configuration -- sound works.

If I uninstall the mod, sound comes back (regardless of which JDK is in use).

(*Note: To clarify I understand that limitations may exist that requires the Oracle version of Java to be installed; and that's fine -- but you should document this requirement in the mod's description -- if it had been documented, it would have saved me a lot of time today.*)

**Steps to reproduce the issue**
1. Install "Sound Physics Remastered" (I tried versions 1.19-1.0.10 and 1.19-1.0.14). 
    a. Cloth Config v6 (7.0.74)
    b. Fabric API (0.57.0+1.19)
    c. Open JDK 17 (MS Build; x64)
3. Run Minecraft.
4. Mine a stone chunk using a pickaxe, notice all sound is muted.
5. Verify configuration settings look sane.  They do.
6. Uninstall mod and try again.
7. All sound is back to normal.
8. Switch to Oracle JDK 18, and reinstall the mod.
9. Mod is working and sound is present.

**Expected behavior**
The prerequisite for the *Oracle* version of the JDK should be documented in the Mod's description page.

**Log files**
Unnecessary -- anyone can install [Open JDK 17](https://www.microsoft.com/openjdk) and repro this issue.

**Comment by henkelmax** [comment]
I am using OpenJDK 17 but not microsofts. This might be a bug in the MS JDK if it only happens with the Microsoft JDK. There is no java version specific code in the mod. 
For now I'd just suggest using another JDK build.

**Comment by BrainSlugs83** [comment]
> This might be a bug in the MS JDK if it only happens with the Microsoft JDK.

@henkelmax -- Interesting -- for reference which Open JDK build and version are you using? (And what OS?)

I would like to verify that this is the case.

> For now I'd just suggest using another JDK build.

For sure! -- Though, I'd still prefer to see the documentation updated if you're amenable to it, as I believe this could save people time troubleshooting if they run into this issue.
