### ISSUE TITLE
Some sounds don't have reverb

### ISSUE THREAD

**Issue by odvigajlo** [henkelmax/sound-physics-remastered#62]
Note Block, Bell, Goat Horn, Jukebox Sounds doesn't have any physics applied

**Steps to reproduce the issue**
1. Open Minecraft With Mod Installed
2. Enter World
3. Play Any Of Listed Sounds: "Note Block, Bell, Goat Horn, Music Disk"

**Expected behavior**
These sounds should have physics applied too

**Versions**
- 1.19.2
- Fabric
- 1.0.15

**Comment by henkelmax** [comment]
This is disabled by default due to performance reasons. You'll have to enable moving sounds in the performance settings.

**Comment by odvigajlo** [comment]
> This is disabled by default due to performance reasons. You'll have to enable moving sounds in the performance settings.

Thanks you alot!
