### ISSUE TITLE
Mod interaction

### ISSUE THREAD

**Issue by Sala-Man** [henkelmax/sound-physics-remastered#64]
**Bug description**
I have noticed this for the last couple of versions but ignored it and just played without SPR. Game stutters with [Effective](https://www.curseforge.com/minecraft/mc-mods/effective) installed, finally managed to get a good example of it building a guardian farm in creative after i updated my mods and figured out what was causing it. In the past it has also happened around my base on land (Caused by flowing water or something underground? I don't know).

**Log files**
I'll include the [log](https://github.com/henkelmax/sound-physics-remastered/files/9483813/latest.log) but i don't think it will be of much help.

**Versions**
- Farbric 0.14.9-1.19.2
- SPR 1.0.12
- Effective 1.2.2.
- Clothconfig 8.0.75
- Fabric api 0.60.0
- Modmenu 4.0.6

**Other mods**
- cloth config
- fabric api
- modmenu
- effective

**Video** 
[Building guardian farm with soul sand bubble elevators.](https://streamable.com/rgyh7b)

**Comment by henkelmax** [comment]
This has already been fixed in the latest version.

**Comment by Sala-Man** [comment]
> This has already been fixed in the latest version.

Yea found the new version on modrinth, so curseforge doesn't have the latest versions, i'll keep that in mind next time. Thanks.

**Comment by henkelmax** [comment]
Curseforge has them as well, you just need to look in the files section and press "view all"

**Comment by Sala-Man** [comment]
Ah true, i always forget about that. Usually don't bother with alpha versions if i can avoid it. Well anyway, glad i can use the mod again, thanks!
