### ISSUE TITLE
Config changes on every boot

### ISSUE THREAD

**Issue by AfterRebelion** [henkelmax/sound-physics-remastered#66]
**Is your feature request related to a problem? Please describe.**
The first time you load Sound Physics Remastered, it generates a config file, as expected.
However, on next loads, even though nothing changes, some values are moved around.
When tracking config changes for my server modpack using Git, this gets annoying really fast, as this mod has 3 config files, and generates noise related to other mods that were updated with real changes that I want to track.

**Describe the solution you'd like**
Save config in secuential order, so values remain always on the same position in the config.
Something similar to `preserveInsertionOrder()` in Forge Config

**Describe alternatives you've considered**
Ignore tracking of this mods config, since it only affects clientside.

**Additional context**
![imagen](https://user-images.githubusercontent.com/559819/191207477-74187638-0004-4ee1-a6a1-58e9fb1be598.png)

**Comment by henkelmax** [comment]
This mod utilizes javas `Properties`. These unfortunately update the last time they were accessed. But there is nothing I can do about that without external libraries.
