### ISSUE TITLE
Barrier Blocks Reflect Sound

### ISSUE THREAD

**Issue by verlixis** [henkelmax/sound-physics-remastered#69]
Barrier blocks reflect sound, there is also no config for barrier block's sound absorption. This is highly noticeable in custom adventure maps where barrier blocks are largely used, causing unwanted reverbs in a seemingly open space.

**Expected behavior**
Barrier blocks should be ignored by default.

**Versions**
- Minecraft version 1.19.2
- Forge/Fabric version 0.14.9
- Mod version 1.0.15

**Comment by henkelmax** [comment]
You can reduce the reflectivity of that block in the config, but sound won't pass through solid objects in the world.

**Comment by verlixis** [comment]
> You can reduce the reflectivity of that block in the config, but sound won't pass through solid objects in the world.

Wow! That was a quick reply, thanks.
I don't seem to be able to find the barrier block in the config list, could you elaborate further?

Also, barrier blocks are not supposed to be solid objects, they are fully transparent and are simply forcing entities from going in and out, yes? So, they can be considered as "air" blocks.

**Comment by Macintosh-Fan** [comment]
Any way this can still be fixed in 2024?
