### ISSUE TITLE
Crashing upon loading

### ISSUE THREAD

**Issue by JoostGames23** [henkelmax/sound-physics-remastered#7]
**Bug description**

Whenever I try to boot the game with the mod in the mods directory I get back to the start screen with the exit code: 0 (see screenshot below). I try booting it alone (as in the only mod in the mods folder) but that one doesn't work aswell. 

**Steps to reproduce the issue**
1. insert the mod in your mods directory
2. Launch minecraft and press play
3. crash happends (check logs and see whats wrong)
4. back to start screen with exit code: 0 

**Expected behavior**

I've expected the mod to load without any errors. 

**Log files**

https://gist.github.com/JoostGames23/825f6507bd48ed158dd03528bc0bf375

**Versions**
- Minecraft version: snapshot 21w42a
- Forge/Fabric version: fabric-loader-0.12.5-21w42a
- Mod version: soundphysics-fabric-1.18-pre1-1.0.0

**Other mods**
- 3dskinlayers-fabric-1.2.1
- axolotl-item-fix-1.1.3
- CameraOverhaul-1.3.0-fabric-universal
- cloth-config-6.0.39-fabric
- dark-loading-screen-1.6.11
- EntityCulling-Fabric-1.3.3
- fabric-api-0.41.2+1.18
- fallingleaves-1.7.4+1.17.1
- iris-and-sodium-mc21w43a-1.1.3-prerev.c347131-dirty
- lambdynamiclights-2.0.2+1.17
- lazydfu-0.1.2
- modmenu-3.0.0
- NoFog-1.17.1b1-Fabric
- notenoughanimations-fabric-1.4.0-mc1.18-pre1
- okzoomer-5.0.0-beta.2+1.17

**Screenshots (Optional)**
With soundphysics in the mods directory:
![image](https://user-images.githubusercontent.com/61411999/141525768-298d45d0-5b30-4db2-8b0f-1601c545e69c.png)

Without the soundphysics in the mods directory:
![image](https://user-images.githubusercontent.com/61411999/141525944-4507d1ac-1ec2-47b6-8b4d-5b108ae36cd3.png)

**Comment by henkelmax** [comment]
Version `1.18-pre1-1.0.0` is for `1.18-pre1` like the name states.
