### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by dankcatlord** [henkelmax/sound-physics-remastered#71]
**Is your feature request related to a problem? Please describe.**
When I increase the sound bounces, I experience lag spikes.

**Describe the solution you'd like**
I propose that the audio is processed on a separate thread so that the mod won't block the main process.

**Describe alternatives you've considered**

**Comment by henkelmax** [comment]
Thats not possible since the mod needs a lot of data from the Minecraft world, which is **not** thread safe. Some stuf already runs in a separate thread, but unfortunately the stuff that causes the most lag is not thread safe.
