### ISSUE TITLE
Lag spikes and Micro-freeze (Log spam) 1.18.2

### ISSUE THREAD

**Issue by ShadowSharkWolf** [henkelmax/sound-physics-remastered#73]
**Bug description**

I'm getting lots of lag spikes within the game as well as small amount of freezing up within the game Frames go from 200 down to 170 to 190 to 60 and from 60 to 35

**Steps to reproduce the issue**
1. Go to Minecraft
2. Click on new game
3. Go into the game within a new world

**Expected behavior**
I was more or less expecting there to be not so much lag spikes

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [This](https://gist.github.com/ShadowSharkWolf/cd2c1dca770e036c037a233f525f1f89). (With the mods I used)
You can use [This](https://gist.github.com/ShadowSharkWolf/355448a02e888b8a108f6acd2392a69c). (With just this mod with fabric api and cloth config)
**Versions**
- Minecraft version 1.18.2
- Fabric version 0.14.9
- Mod version 0.5.5

**Other mods**

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
You are using sound physics and not sound physics remastered.

**Comment by ShadowSharkWolf** [comment]
Ah I see. Thanks for helping me with that confusion. Silly me...
