### ISSUE TITLE
Causes stuttering in a certain area

### ISSUE THREAD

**Issue by Aces-and-Jacks** [henkelmax/sound-physics-remastered#75]
**Bug description**
Loaded into a world and noticed the there was stuttering when I walked in a certain area where I spawned at. Leaving that specific area caused the stuttering to stop. 

**Steps to reproduce the issue**
Haven't been able to reproduce the issue, but I have the world the issue is caused on

**Expected behavior**
No stuttering

**Log files**
https://mclo.gs/iGtBAGU

**Versions**
- Minecraft version: 1.19.2
- Fabric version: 0.14.10
- Mod version: 1.19.2-1.0.15

**Other mods**
already tested with the other mods and it's only caused by this one

**Screenshots (Optional)**
Got a video instead: https://youtu.be/xD5PcWQwvZ4

**Comment by henkelmax** [comment]
> Log files
https://mclo.gs/iGtBAGU

The logs you sent have sound physics fabric installed, not sound physics remastered.

**Comment by Aces-and-Jacks** [comment]
link goes here https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered

**Comment by henkelmax** [comment]
Are you using a mod that adds other sounds to minecraft?
If yes, please try running the game without that mod.

I also need your config.

**Comment by Aces-and-Jacks** [comment]
where would the config be?

**Comment by henkelmax** [comment]
in the config folder

**Comment by Aces-and-Jacks** [comment]
oh...missed that folder
[sound_physics_remastered.zip](https://github.com/henkelmax/sound-physics-remastered/files/9922308/sound_physics_remastered.zip)

there was a sound physics remastered folder in the config so I compressed it

**Comment by Aces-and-Jacks** [comment]
also here's another log incase the other one was out dated https://mclo.gs/35h1KZA

**Comment by henkelmax** [comment]
Set `update_moving_sounds` to `false`
