### ISSUE TITLE
Performance Bottleneck

### ISSUE THREAD

**Issue by haubna** [henkelmax/sound-physics-remastered#77]
A user reported to me that in combination with the Physics Mod + explosions they get huge lag spikes. I guess due to large amounts of sounds played (max. 2 per minecraft tick = 40 per second). I will lower the amount of sound effects that can be played when the sound physics remastered mod is installed so it reduces/eliminates the lag spikes but I thought I would share where the bottleneck is located with you.

Here is the spark profile: https://spark.lucko.me/5tap27zG76
![stack](https://user-images.githubusercontent.com/7816894/200114908-2bf9ee61-843f-41af-9712-9eb07f95e76f.png)

**Comment by henkelmax** [comment]
You can exclude sounds with a regex. The config entry is called `sound_blacklist_regex`.

**Comment by haubna** [comment]
Yup I am aware of that. An API to play regular sound effects instead of raytraced ones for mod devs would be helpful.
