### ISSUE TITLE
Sound Physics Remastered 1.18 pre-1 crashes on startup

### ISSUE THREAD

**Issue by SweepSwap** [henkelmax/sound-physics-remastered#8]
**Bug description**
The Game Crashes on startup using soundphysics-fabric-1.18-pre1-1.0.0

**Steps to reproduce the issue**
Install Fabric Loader Version 0.12.5
Install Soundphysics
Start the Game
Game Crashes

**Log Files:**
https://gist.github.com/SweepSwap/3b55d8f8c921109d3a49e86cac17915b

**Comment by henkelmax** [comment]
Does the game crash without the mod?

**Comment by henkelmax** [comment]
Thanks for reporting this issue! The fixed version should be available on curseforge in a couple of minutes.
