### ISSUE TITLE
Compatibility: Computercraft Speakers

### ISSUE THREAD

**Issue by Martmists-GH** [henkelmax/sound-physics-remastered#80]
**Is your feature request related to a problem? Please describe.**
Using the current version of SPR and CC:R for 1.18, speakers can be heard through walls as if they were not there.

**Describe the solution you'd like**
Make the CC:R Speakers act the same as other sounds in the game.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by henkelmax** [comment]
Try enabling moving sounds in the config. But be aware that this might create a lot of lag.

**Comment by Martmists-GH** [comment]
Where can I find this option? I don't see it in-game nor in the .properties file

**Comment by henkelmax** [comment]
`update_moving_sounds` in the config file

**Comment by Martmists-GH** [comment]
Adding the property did nothing, and after restarting the game the line is gone from the properties file.

**Comment by henkelmax** [comment]
Which mod version are you using?

**Comment by Martmists-GH** [comment]
v1.18.2-1.0.6

**Comment by henkelmax** [comment]
Yeah, this version doesn't support that. You need to update to 1.19.2.

**Comment by Martmists-GH** [comment]
So there are no plans to backport this to 1.19.2? The modpack we're on can't be updated to 1.19.2 anytime soon due to waiting for mods to update.

**Comment by henkelmax** [comment]
No. There won't be backports (at least by me).
