### ISSUE TITLE
Sound occlusion removes almost all sound around corners

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [henkelmax/sound-physics-remastered#81]
**Bug description**
If you build something really loud (like a lightning generator) and stand around a corner the sound almost completely disappears. All my settings were at default and I have no other mods that change the sound physics. It actually also works just by turning the camera so you can't see it anymore. I doubled the amount of rays used to calculate the sounds but I had to increase it to absurd levels to hear anything at all. I think the occlusion is too much because it's only 1 layer of blocks between me and the really loud sounds.

I turned on debug draw and none of the lines reach my player.

**Steps to reproduce the issue**
1. Build really loud sound generator
2. Build a wall (I used a building)
3. Stand just behind the wall
4. Can't hear the sound

**Expected behavior**
The sound should propagate around the corner and sound a bit muffled, not be completely gone. I think the rays should be able to propagate through blocks more. 

**Log files**
No errors
I also don't know where the debug logs are.

**Versions**
- 1.19.2
- Fabric-0.14.9-1.19.2
- 1.0.15

**Other mods**
* Animatica (no changes to sound)
* ArmorHotSwap (no changes to sound)
* Auditory (adds sounds but doesn't change sound physics)
* CaffieneConfig (idk what it does)
* Carpet Mod (no changes to sound)
* Colormatic (no changes to sound)
* Continuity (no changes to sound)
* Distant Horizons (no changes to sound)
* Enhanced Block Entities (no changes to sound)
* Entity-Culling-Fabric (no changes to sound)
* FerriteCore (no changes to sound)
* Indium (no changes to sound)
* Iris (no changes to sound)
* LambDynamicLights (no changes to sound)
* LazyDFU (no changes to sound)
* Litematica (no changes to sound)
* Lithium (no changes to sound)
* MaLiLib (no changes to sound)
* memory Leak Fix (no changes to sound) (yes its capitalized that way)
* Mixin Conflict Helper (no changes to sound)
* Mod Menu (no changes to sound)
* Replay Mod (no changes to sound)
* Simple armor hud (no changes to sound)
* SlimeChunkF3 (no changes to sound)
* Smooth Boot (maybe has an effect)
* Sodium (no changes to sound)
* Sound Physics Remastered
* Starlight (no changes to sound)
* WI Zoom (no changes to sound)
* WorldEdit (no changes to sound)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/67865358/205455687-f1a6a9d3-9c47-475a-9088-80177c6491fa.png)
Very loud from here
![image](https://user-images.githubusercontent.com/67865358/205455718-6b4b0864-8463-44c3-aee9-06900b6da125.png)
Literally can't hear it here

**Comment by henkelmax** [comment]
Please include screenshots with debug rendering enabled. You find this in the debug section of the settings GUI of the mod.

**Comment by definitely-nobody-is-here** [comment]
If I set up a bell to ring constantly outside my house and walk around inside it goes from really loud to completely silent.

**Comment by definitely-nobody-is-here** [comment]
Screenshots with debug rendering enabled. Both environment rays and occlusion ray counts have been doubled.
![image](https://user-images.githubusercontent.com/67865358/205463937-77933fc9-c2e9-4a47-bbeb-6603340b5345.png)
Sound bounces, no occlusion rays, can hear
![image](https://user-images.githubusercontent.com/67865358/205463957-a3f12890-8b89-4a71-928d-241d5dd9a9ae.png)
Occlusion rays, no sound bounces, can hear
![image](https://user-images.githubusercontent.com/67865358/205464005-7742fb2f-b9fb-48ec-8768-fa79c60758e1.png)
Sound bounces, no occlusion rays, cannot hear
![image](https://user-images.githubusercontent.com/67865358/205463987-a00ef469-ba62-4d45-a8fd-f66ded3caee0.png)
Occlusion rays, no sound bounces, cannot hear

Some extra rays exist because of the villagers.
also I'm using bells instead of channeling tridents and lightning rods.

**Comment by henkelmax** [comment]
Can you send a recording of this?

**Comment by definitely-nobody-is-here** [comment]
I increased the number of rays by a lot and it helps the issue a little bit, I have to be further around the wall to not hear it, but the performance isn't as good anymore.

**Comment by henkelmax** [comment]
That's the thing. There are only a limited number of rays. There will always be specific situations where it sounds weird, but there is simply not enough performance to do it perfectly.

**Comment by definitely-nobody-is-here** [comment]
I would suggest making loud sounds like lightning always play without any processing, so situations like this where you're far away but realistically should still hear the sound don't happen as easily.
