### ISSUE TITLE
Directional Sound settings are ignored

### ISSUE THREAD

**Issue by Chuzume** [henkelmax/sound-physics-remastered#84]
**Bug description**
From the vanilla sound setting, even with turning Directional Sound ON behaves the same as turning it off.

**Steps to reproduce the issue**
1. Go to Sound Setting
2. Turn on "Directional Sound"
3. Make some sound

**Expected behavior**
At least it should have the same sound behave as vanilla if the mod action was turned off

**Log files**
https://gist.github.com/Chuzume/022174ac6e32ba3ef65017264c90a53a

**Versions**
- Minecraft 1.19.3
- Fabric 0.14.11
- soundphysics-fabric-1.19.3-1.0.17

**Other mods**
- Fabric-api-0.68.1

**Comment by henkelmax** [comment]
I don't really get your issue. Can you describe it in more detail?

**Comment by Chuzume** [comment]
When "Directional Sound" is turned on in the vanilla Minecraft settings, the sound becomes more directional, but when this MOD is enabled, it behaves the same as when this setting is turned off.
It's hard to explain it better than this.

**Comment by Chuzume** [comment]
When I'm not using this mod, it's definitely working ... but OK.

**Comment by henkelmax** [comment]
Yes, that was not my point.
