### ISSUE TITLE
Insane performance hit

### ISSUE THREAD

**Issue by Ev3rgarden** [henkelmax/sound-physics-remastered#85]
Performance tests:
Hi!
I did some performance test on the "benchmark v3 map" to test the impact of the mod. Standard settings for both test with directional sound on and around 25 mobs around me.
A clean install of MC 1.19.3 (newest fabric version API and Sodium) without the mod gives me after 3 minutes an average of 230fps (lowest 180, peak 280) and with the mod after 3 minutes average of 50fps (lowest 28, peak 66) 

I used version fabric 1.19.3 - 1.0.17 of the mod.

Hardware:
i5 12600k
RX 6600 AMD
16GB ram 3200
Win11

**Comment by henkelmax** [comment]
Please fill out the bug template and send me your config file.

**Comment by henkelmax** [comment]
2c67c6395cac5d4b5801ef860c3917a29c5dc08c
