### ISSUE TITLE
Avoidable stuttering when using updateMovingSounds=true

### ISSUE THREAD

**Issue by briansemrau** [henkelmax/sound-physics-remastered#86]
**Bug description**
When playing with `update_moving_sounds=true`, I get significant stuttering (~60ms frame time vs 16ms median)

**Versions**
- Minecraft version: 1.19.2
- Mod version: 1.0.16
- Fabric

I was wondering why this was happening, so I glanced at the source code:
https://github.com/henkelmax/sound-physics-remastered/blob/374d58e3a04dd306c79b3ba92015668eaf3d177d/common/src/main/java/com/sonicether/soundphysics/mixin/SoundSystemMixin.java#L38-L47

Yeah, that'll do it. This should be reworked to stagger sound updates across every tick.

Suggested fix:
```diff
- if (minecraft.level != null && minecraft.level.getGameTime() % 5 == 0) {
+ if (minecraft.level != null && (minecraft.level.getGameTime() + sound.getId().hashCode()) % 5 == 0) {
```

**Comment by henkelmax** [comment]
Yes, we are aware of that issue but we haven't investigated that yet. Your solution looks good! I personally wouldn't use the ID of the sound as it might be the same for sounds that get played multiple times. 
Do you want to make a PR or should I do it?

**Comment by briansemrau** [comment]
Ah, I quickly assumed that `getId` would return a UUID, not a name. My bad. I suppose a randomized int could be added to SoundInstance as a mixin.

I don't have the built tools set up to test any solution locally, so feel free to make the PR if you like.

**Comment by henkelmax** [comment]
No worries. Thank you for investigating the issue :)

**Comment by henkelmax** [comment]
It's now up on curse and modrinth. I also added a config value for the actual interval (5 by default).

**Comment by briansemrau** [comment]
That was fast! I'll give it a whirl.

**Comment by henkelmax** [comment]
Turns out the has code of the sound instance itself is the best fit, since it stays the same for every individual sound.
