### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PweSol** [henkelmax/sound-physics-remastered#87]
I'm sure you know about the [Resounding](https://github.com/thedocruby/resounding) mod. Is it possible to implement some of the features it has to this mod? Previously I didn't think it would be necessary or worthwhile after reading its FAQ, but now I reconsidered. Since that mod doesn't seem to be being worked on anymore and likely won't be finished anytime soon, I think it would be nice if we got some of its features or performance improvements in a mod that actually is maintained, like this one.

**Comment by henkelmax** [comment]
If you want specific features to be added, you can create a PR. I personally won't copy stuff from other mods.

**Comment by PweSol** [comment]
Oh I didn't mean to copy anything. But it has interesting ideas that you could inspire from. For example, before you said that making this mod multi-threaded would be impossible, yet the Resounding mod proved making such sound system multi-threaded is possible.

If I knew how to mod, I would have tried making such PR :D
