### ISSUE TITLE
No audio processing of jukebox music discs

### ISSUE THREAD

**Issue by rght925h** [henkelmax/sound-physics-remastered#89]
Audio played by the jukebox when a disc is inserted doesn't seem to be processed by the sound physics plugin. Could that be changed? 
Not sure if this is intentional; if so, please ignore this, of course.

Currently on Sound Physics Remastered 1.19.3-1.0.18 for Fabric. 

Absolutely wonderful mod, thank you!! :)

**Comment by henkelmax** [comment]
Enable moving sounds in the config.

**Comment by MyBedIsInAWall** [comment]
i cant find moving sounds in config
im using latest 1.18.2 if that helps
![image](https://user-images.githubusercontent.com/109745730/229306103-70ab6775-1679-4b8f-8672-490a493008e4.png)

**Comment by henkelmax** [comment]
Yeah that version doesn't receive any updates anymore.

**Comment by MyBedIsInAWall** [comment]
oh okay
