### ISSUE TITLE
Delay with hearing yourself

### ISSUE THREAD

**Issue by KrisonaMoon** [henkelmax/sound-physics-remastered#91]
**Bug description**

**Steps to reproduce the issue**
click hear your self to yes

**Expected behavior**
i was hoping for no delay when i speak using the voice chat mod. when i use it with the mod it delays by 3 seconds.
I wanted to have my voice to have the effect of the reverb and stuff like the other members when they speak to show up on my streams and so i can hear my self with the effect. 

**Versions**
- Minecraft version 1.19.2
- Fabric version 
- Mod version 1.0.11

**Other mods**
voice mod  

![image](https://user-images.githubusercontent.com/118490270/213251353-b9a980bd-41f9-4f94-b8de-759b2606d1c5.png)

**Comment by henkelmax** [comment]
You can reduce the playback delay in the voice chat settings, but this will lead to audio issues. This delay is not rally avoidable unfortunately.

**Comment by K4LCIFER** [comment]
Is it necessary to hear oneself? I feel like the reverb effect from reflections is what is gives the effect. I don't think it's necessary to play back your own voice. Simple voice chat, for example, only plays back your own voice when you are testing to see if it's working.
