### ISSUE TITLE
Crash during loading server

### ISSUE THREAD

**Issue by CPSRYAN** [henkelmax/sound-physics-remastered#92]
I have a bloated modpack that I need to debloat, it crashes during loading. It's crashed whilst interacting with Sound Physics Remastered so I removed it to check. It still crashed on both the server and client. I had just added Valkryean Skies for 1.18, along with Kotlin and Eureka. My guess is an error due to Kotlin. I made a pack with a minimal amount of mods (See list below) to test it and it didn't crash on the client, however on attempting a test server it did crash with the attached crash log. I tried removing the configs for the mod to see if I had changed something and caused the issue but no dice.

1) Install set of mods
2) Install forge server 40.2.0
3) Preferrably use same startup arguments
4) During startup, observe crash

I would prefer it to not crash, but coding is hard and I'm not smart enough to figure out the problem

Crash reports and log files will be attached to the report, unless I mess it up somehow.

1.18.2
Forge 40.2.0
soundphysics-forge-1.18.2-1.0.6

Testing pack was:
create-1.18.2-0.5.0.h
eureka-1.1.0-beta5
jei-1.18.2-forge-10.2.1.1002
kotlinforforge-3.9.1-all
soundphysics-forge-1.18.2-1.0.6
valkyrienskies-118-2.1.0-beta9
voicechat-forge-1.18.2-2.3.27
flywheel-forge-1.18.2-0.6.8.a.jar (Client only, not server. Tested anyway with same result)

[2023-01-21-18.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/10473480/2023-01-21-18.log.gz)
[debug-1.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/10473481/debug-1.log.gz)
[2023-01-22-1.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/10473482/2023-01-22-1.log.gz)
[crash-reports.zip](https://github.com/henkelmax/sound-physics-remastered/files/10473483/crash-reports.zip)
[crash-2023-01-22_00.17.55-fml.txt](https://github.com/henkelmax/sound-physics-remastered/files/10473484/crash-2023-01-22_00.17.55-fml.txt)

**Comment by CPSRYAN** [comment]
Appears to be during the loading of the config, only line I can understand mentions "cast filter" which I would guess has to do with the raycasting for occlusion and stuff? Also, nice automation, very cool ;D

**Comment by CPSRYAN** [comment]
Oops, realised I forgot to include my client logs for the non-crash
[2023-01-22-1.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/10473501/2023-01-22-1.log.gz)
[2023-01-22-2.log.gz](https://github.com/henkelmax/sound-physics-remastered/files/10473502/2023-01-22-2.log.gz)

**Comment by CPSRYAN** [comment]
Tried the server without Sound Physics installed, but with Ferrite Core, it crashed. Realised I could manually crash the client with f3+c to get a crash log for more info
[crash-2023-01-22_01.32.36-client.txt](https://github.com/henkelmax/sound-physics-remastered/files/10473523/crash-2023-01-22_01.32.36-client.txt)

**Comment by henkelmax** [comment]
> Tried the server without Sound Physics installed, but with Ferrite Core, it crashed.

If thats the case then the issue is not the sound physics mod.

**Comment by CPSRYAN** [comment]
Sorry, shouldn't have mentioned that, it's a separate issue. I have a habit of writing down chronologically to get my thoughts in order

**Comment by henkelmax** [comment]
Ok, if it doesn't crash on its own, please find out which mod in combination with this mod causes the crash.

Also the 1.18 version of the mod is no longer actively developed, so there won't be a fix for this if its caused by sound physics.

**Comment by CPSRYAN** [comment]
My guess is a problem with mixin, I was too tired to test it last night. Problem only occurred once I added Valkryien Skies and the necessary mods. Will test it later. Fair enough about not maintaining, will try and find an alternative perhaps

**Comment by CPSRYAN** [comment]
Turns out the crash is an interaction with Valkryien Skies, probably how the raycast looks at blocks when the ships are quantumn blocks, aka there but not there. Absolutely love your mod, hope it is something that can be fixed on their end since it's no longer maintained ;-;

**Comment by CPSRYAN** [comment]
Looking into it, a fix seems to be planned, as the sound physics appear to be the problem in that mod. It is planned to move the sound physics from serverside to clientside from what I can tell? Sorry for the trouble, have a great day!
