### ISSUE TITLE
Large decrease in performance when near many mobs

### ISSUE THREAD

**Issue by chorbintime** [henkelmax/sound-physics-remastered#93]
**Bug description**

**Steps to reproduce the issue**
1. Install Better MC Forge 1.19.2
2. Spawn a lot of cows, in an enclosure surrounded by carpet 
3. Notice large hit in performance

**Expected behavior**
I'm guessing that each individual cow moo is bouncing in its own way, and is also influenced by the carpet. This cause a major decrease in performance.

**Log files**
Do not have them. I am filing this on behalf of another user. 

**Versions**
- 1.19.2
- Forge 43.2.0
- 1.0.18

**Other mods**
Better MC Forge 1.19.2 modpack, 217~ other mods. 

**Screenshots (Optional)**
Available on the original issue. 

I've made this issue using the information gathered from https://github.com/LunaPixelStudios/Better-MC/issues/1010
I do not have the complete information, and the original poster should instead be asked. I can also test on my own if necessary but I am somewhat busy.

**Comment by henkelmax** [comment]
This has been fixed in 1.1.0

**Comment by WorLDz1337** [comment]
Nice! When to expect a release [FORGE] 1.19.2-1.1.0 on Curseforge?

**Comment by Maypul** [comment]
Was also looking for this for 1.19.2 forge
