### ISSUE TITLE
Goofy jukebox sound positioning

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/sound-physics-remastered#95]
**Bug description**
The music doesn't sounds to come from the playing jukebox, and trying to block the source literally makes it move to another location. Word is not enough, I'll link a video below. (I used a DISCO custom disc but even vanilla discs have the same problem too)

It worths a mention that also did a little test with a mod called [Vibes](https://modrinth.com/mod/vibes), introducing a portable gadget that plays music discs and can be thrown on the ground/put inside containers and keep working properly. I thought that the mod could have a disasterous compatibility with Sound Physics Remastered, but they actually worked pretty fine together, the location of the sound source can be accurately calculated by SPR.

**Steps to reproduce the issue**
Shown in the video.

**Expected behavior**
The sound stays where the jukebox is with reverb/lowpass stuff working as intended.

**Log files**
No logs.

**Versions**
- Minecraft version 1.19.2
- Fabric version 1.14.14
- Mod version 1.0.18

**Other mods**
[Mod list](https://mclo.gs/IgeThZH)

**Video**
https://clipchamp.com/watch/PNuDCBWn2bF

You can see from the video that the occlusion works weirdly, and in the second half part of the video the source even slipped blocks away from the jukebox.

**Comment by henkelmax** [comment]
This is completely normal. The sound bounces off of something and thus is sounding as it would come from another direction. If you want to find out why exactly, you can enable debug ray rendering in the cloth config options. If you don't want the direction to be changed you can disable the direction evaluation in the config.

**Comment by ChromaPIE** [comment]
Gotta say, though it's still feels weird when putting ears on the jukebox and hearing sound coming from inside the wall next to me, when i enable the debug and see thousands of colorful lines killing the framerate showing how sounds are calculated, i dont want to disable the option now. Thanks for the support anyway, think imma try to get used to it.
