### ISSUE TITLE
Create Steam engone stuttering. 

### ISSUE THREAD

**Issue by TofuHell** [henkelmax/sound-physics-remastered#96]
**Bug description**
When a steam engine is built the game stutters very badly the faster and more outputs there are on the steam engine (most probably due to the sound physics being overwhelmed) 

**Steps to reproduce the issue**
1. Make a Steam Engine
2. Add lots of outputs.

**Expected behavior**
Simply no stutter. 

**Log files**
https://gist.github.com/TofuHell/ac9423ca6e69980e87041765b914dd53

**Versions**
- 1.19.2
- 43.2.0
- Sound Physics Remastered 1.0.18

**Other mods**
- Flywheel 0.6.8.a
- Create 0.5.0.i

**Screenshots (Optional)**
https://youtu.be/frBHpbYm_44

**Comment by henkelmax** [comment]
You can blacklist sounds. This is recommended for every sound thats spammed a lot, since this causes a lot of performance issues.
For a better performance use the latest version of the mod.

**Comment by TofuHell** [comment]
May i ask for help with the regex for blacklisting the steam engine?

**Comment by henkelmax** [comment]
As I already said. Please use the latest version of the mod. There is no regex in the latest version of the mod. There is a separate config file for excluding sounds.
