### ISSUE TITLE
Hear self option on Forge for Simple Voice Chat

### ISSUE THREAD

**Issue by squoshi** [henkelmax/sound-physics-remastered#97]
**Is your feature request related to a problem? Please describe.**
The Fabric version seems to have an option to hear yourself when using Simple Voice Chat. I tried adding said configuration on Forge to the file and it didn't work.

**Describe the solution you'd like**
To add a hear-self option on Forge.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by henkelmax** [comment]
The code base for both versions of the mod is exactly the same. It should work the same way as with fabric.

**Comment by henkelmax** [comment]
No. Sorry
